// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct AccessCar {
    pub car_id: u64,
    pub customer_id: String,
    pub car_number: String,
    pub status: i8,
    pub register_time: __sdk::Timestamp,
    pub remark: Option<String>,
    pub park_id: u64,
    pub created_at: __sdk::Timestamp,
    pub updated_at: Option<__sdk::Timestamp>,
}

impl __sdk::InModule for AccessCar {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `AccessCar`.
///
/// Provides typed access to columns for query building.
pub struct AccessCarCols {
    pub car_id: __sdk::__query_builder::Col<AccessCar, u64>,
    pub customer_id: __sdk::__query_builder::Col<AccessCar, String>,
    pub car_number: __sdk::__query_builder::Col<AccessCar, String>,
    pub status: __sdk::__query_builder::Col<AccessCar, i8>,
    pub register_time: __sdk::__query_builder::Col<AccessCar, __sdk::Timestamp>,
    pub remark: __sdk::__query_builder::Col<AccessCar, Option<String>>,
    pub park_id: __sdk::__query_builder::Col<AccessCar, u64>,
    pub created_at: __sdk::__query_builder::Col<AccessCar, __sdk::Timestamp>,
    pub updated_at: __sdk::__query_builder::Col<AccessCar, Option<__sdk::Timestamp>>,
}

impl __sdk::__query_builder::HasCols for AccessCar {
    type Cols = AccessCarCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        AccessCarCols {
            car_id: __sdk::__query_builder::Col::new(table_name, "car_id"),
            customer_id: __sdk::__query_builder::Col::new(table_name, "customer_id"),
            car_number: __sdk::__query_builder::Col::new(table_name, "car_number"),
            status: __sdk::__query_builder::Col::new(table_name, "status"),
            register_time: __sdk::__query_builder::Col::new(table_name, "register_time"),
            remark: __sdk::__query_builder::Col::new(table_name, "remark"),
            park_id: __sdk::__query_builder::Col::new(table_name, "park_id"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
        }
    }
}

/// Indexed column accessor struct for the table `AccessCar`.
///
/// Provides typed access to indexed columns for query building.
pub struct AccessCarIxCols {
    pub car_id: __sdk::__query_builder::IxCol<AccessCar, u64>,
    pub customer_id: __sdk::__query_builder::IxCol<AccessCar, String>,
    pub park_id: __sdk::__query_builder::IxCol<AccessCar, u64>,
}

impl __sdk::__query_builder::HasIxCols for AccessCar {
    type IxCols = AccessCarIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        AccessCarIxCols {
            car_id: __sdk::__query_builder::IxCol::new(table_name, "car_id"),
            customer_id: __sdk::__query_builder::IxCol::new(table_name, "customer_id"),
            park_id: __sdk::__query_builder::IxCol::new(table_name, "park_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for AccessCar {}
