// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AddOrganizationMemberArgs {
    pub organization_id: u64,
    pub center_user_id: u64,
    pub member_role: String,
}

impl From<AddOrganizationMemberArgs> for super::Reducer {
    fn from(args: AddOrganizationMemberArgs) -> Self {
        Self::AddOrganizationMember {
            organization_id: args.organization_id,
            center_user_id: args.center_user_id,
            member_role: args.member_role,
        }
    }
}

impl __sdk::InModule for AddOrganizationMemberArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `add_organization_member`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait add_organization_member {
    /// Request that the remote module invoke the reducer `add_organization_member` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`add_organization_member:add_organization_member_then`] to run a callback after the reducer completes.
    fn add_organization_member(
        &self,
        organization_id: u64,
        center_user_id: u64,
        member_role: String,
    ) -> __sdk::Result<()> {
        self.add_organization_member_then(organization_id, center_user_id, member_role, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `add_organization_member` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn add_organization_member_then(
        &self,
        organization_id: u64,
        center_user_id: u64,
        member_role: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl add_organization_member for super::RemoteReducers {
    fn add_organization_member_then(
        &self,
        organization_id: u64,
        center_user_id: u64,
        member_role: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            AddOrganizationMemberArgs {
                organization_id,
                center_user_id,
                member_role,
            },
            callback,
        )
    }
}
