// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::utility_bill_input_type::UtilityBillInput;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AddEleBillArgs {
    pub bill_id: u64,
    pub input: UtilityBillInput,
}

impl From<AddEleBillArgs> for super::Reducer {
    fn from(args: AddEleBillArgs) -> Self {
        Self::AddEleBill {
            bill_id: args.bill_id,
            input: args.input,
        }
    }
}

impl __sdk::InModule for AddEleBillArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `add_ele_bill`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait add_ele_bill {
    /// Request that the remote module invoke the reducer `add_ele_bill` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`add_ele_bill:add_ele_bill_then`] to run a callback after the reducer completes.
    fn add_ele_bill(&self, bill_id: u64, input: UtilityBillInput) -> __sdk::Result<()> {
        self.add_ele_bill_then(bill_id, input, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `add_ele_bill` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn add_ele_bill_then(
        &self,
        bill_id: u64,
        input: UtilityBillInput,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl add_ele_bill for super::RemoteReducers {
    fn add_ele_bill_then(
        &self,
        bill_id: u64,
        input: UtilityBillInput,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(AddEleBillArgs { bill_id, input }, callback)
    }
}
