// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::utility_bill_input_type::UtilityBillInput;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct AmountBillInput {
    pub project_name: String,
    pub tenant_name: Option<String>,
    pub public_bank_account: Option<String>,
    pub private_bank_account: Option<String>,
    pub ele_fee_cents: i64,
    pub water_fee_cents: i64,
    pub receive_fee_cents: i64,
    pub factory_rent_cents: i64,
    pub management_fee_cents: i64,
    pub invoice_tax_cents: i64,
    pub total_fee_cents: i64,
    pub service_fee_cents: i64,
    pub garbage_fee_cents: i64,
    pub extra_ele_fee_cents: i64,
    pub basic_ele_fee_cents: i64,
    pub basic_ele_capacity_centi_kw: Option<i64>,
    pub basic_ele_price_scaled: Option<i64>,
    pub receipt_amount_cents: i64,
    pub penalty_fee_cents: Option<i64>,
    pub service_rate_basis_points: Option<i64>,
    pub garbage_rate_basis_points: Option<i64>,
    pub penalty_rate_basis_points: Option<i64>,
    pub extra_ele_rate_basis_points: Option<i64>,
    pub penalty_item: Option<String>,
    pub extra_ele_item: Option<String>,
    pub ele_item: Option<String>,
    pub water_item: Option<String>,
    pub extra_project_item: Option<String>,
    pub tax_rate_json: Option<String>,
    pub remark: Option<String>,
    pub receipt_time: Option<__sdk::Timestamp>,
    pub tenant_id: Option<u64>,
    pub park_id: Option<u64>,
    pub carryover_fee_cents: i64,
    pub carryover_item: Option<String>,
    pub consumed_carryover_item_ids: Vec<u64>,
    pub ele_bills: Vec<UtilityBillInput>,
    pub water_bills: Vec<UtilityBillInput>,
}

impl __sdk::InModule for AmountBillInput {
    type Module = super::RemoteModule;
}
