// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ApiLog {
    pub log_id: u64,
    pub customer_id: String,
    pub method: String,
    pub path: Option<String>,
    pub referer_path: String,
    pub item_name: Option<String>,
    pub username: String,
    pub user_id: u64,
    pub request_time: __sdk::Timestamp,
    pub created_at: __sdk::Timestamp,
    pub updated_at: Option<__sdk::Timestamp>,
}

impl __sdk::InModule for ApiLog {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `ApiLog`.
///
/// Provides typed access to columns for query building.
pub struct ApiLogCols {
    pub log_id: __sdk::__query_builder::Col<ApiLog, u64>,
    pub customer_id: __sdk::__query_builder::Col<ApiLog, String>,
    pub method: __sdk::__query_builder::Col<ApiLog, String>,
    pub path: __sdk::__query_builder::Col<ApiLog, Option<String>>,
    pub referer_path: __sdk::__query_builder::Col<ApiLog, String>,
    pub item_name: __sdk::__query_builder::Col<ApiLog, Option<String>>,
    pub username: __sdk::__query_builder::Col<ApiLog, String>,
    pub user_id: __sdk::__query_builder::Col<ApiLog, u64>,
    pub request_time: __sdk::__query_builder::Col<ApiLog, __sdk::Timestamp>,
    pub created_at: __sdk::__query_builder::Col<ApiLog, __sdk::Timestamp>,
    pub updated_at: __sdk::__query_builder::Col<ApiLog, Option<__sdk::Timestamp>>,
}

impl __sdk::__query_builder::HasCols for ApiLog {
    type Cols = ApiLogCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ApiLogCols {
            log_id: __sdk::__query_builder::Col::new(table_name, "log_id"),
            customer_id: __sdk::__query_builder::Col::new(table_name, "customer_id"),
            method: __sdk::__query_builder::Col::new(table_name, "method"),
            path: __sdk::__query_builder::Col::new(table_name, "path"),
            referer_path: __sdk::__query_builder::Col::new(table_name, "referer_path"),
            item_name: __sdk::__query_builder::Col::new(table_name, "item_name"),
            username: __sdk::__query_builder::Col::new(table_name, "username"),
            user_id: __sdk::__query_builder::Col::new(table_name, "user_id"),
            request_time: __sdk::__query_builder::Col::new(table_name, "request_time"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
        }
    }
}

/// Indexed column accessor struct for the table `ApiLog`.
///
/// Provides typed access to indexed columns for query building.
pub struct ApiLogIxCols {
    pub customer_id: __sdk::__query_builder::IxCol<ApiLog, String>,
    pub log_id: __sdk::__query_builder::IxCol<ApiLog, u64>,
}

impl __sdk::__query_builder::HasIxCols for ApiLog {
    type IxCols = ApiLogIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ApiLogIxCols {
            customer_id: __sdk::__query_builder::IxCol::new(table_name, "customer_id"),
            log_id: __sdk::__query_builder::IxCol::new(table_name, "log_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ApiLog {}
