// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AppendCrawlerTaskLogArgs {
    pub task_id: u64,
    pub level: String,
    pub stage: String,
    pub message: String,
    pub detail_json: Option<String>,
}

impl From<AppendCrawlerTaskLogArgs> for super::Reducer {
    fn from(args: AppendCrawlerTaskLogArgs) -> Self {
        Self::AppendCrawlerTaskLog {
            task_id: args.task_id,
            level: args.level,
            stage: args.stage,
            message: args.message,
            detail_json: args.detail_json,
        }
    }
}

impl __sdk::InModule for AppendCrawlerTaskLogArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `append_crawler_task_log`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait append_crawler_task_log {
    /// Request that the remote module invoke the reducer `append_crawler_task_log` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`append_crawler_task_log:append_crawler_task_log_then`] to run a callback after the reducer completes.
    fn append_crawler_task_log(
        &self,
        task_id: u64,
        level: String,
        stage: String,
        message: String,
        detail_json: Option<String>,
    ) -> __sdk::Result<()> {
        self.append_crawler_task_log_then(task_id, level, stage, message, detail_json, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `append_crawler_task_log` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn append_crawler_task_log_then(
        &self,
        task_id: u64,
        level: String,
        stage: String,
        message: String,
        detail_json: Option<String>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl append_crawler_task_log for super::RemoteReducers {
    fn append_crawler_task_log_then(
        &self,
        task_id: u64,
        level: String,
        stage: String,
        message: String,
        detail_json: Option<String>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            AppendCrawlerTaskLogArgs {
                task_id,
                level,
                stage,
                message,
                detail_json,
            },
            callback,
        )
    }
}
