// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Attendance {
    pub attendance_id: u64,
    pub customer_id: String,
    pub punch_in: __sdk::Timestamp,
    pub punch_out: Option<__sdk::Timestamp>,
    pub status: Option<i8>,
    pub longitude_e_15: i64,
    pub latitude_e_15: i64,
    pub user_id: Option<u64>,
    pub username: String,
    pub punch_in_source: Option<String>,
    pub punch_out_source: Option<String>,
}

impl __sdk::InModule for Attendance {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Attendance`.
///
/// Provides typed access to columns for query building.
pub struct AttendanceCols {
    pub attendance_id: __sdk::__query_builder::Col<Attendance, u64>,
    pub customer_id: __sdk::__query_builder::Col<Attendance, String>,
    pub punch_in: __sdk::__query_builder::Col<Attendance, __sdk::Timestamp>,
    pub punch_out: __sdk::__query_builder::Col<Attendance, Option<__sdk::Timestamp>>,
    pub status: __sdk::__query_builder::Col<Attendance, Option<i8>>,
    pub longitude_e_15: __sdk::__query_builder::Col<Attendance, i64>,
    pub latitude_e_15: __sdk::__query_builder::Col<Attendance, i64>,
    pub user_id: __sdk::__query_builder::Col<Attendance, Option<u64>>,
    pub username: __sdk::__query_builder::Col<Attendance, String>,
    pub punch_in_source: __sdk::__query_builder::Col<Attendance, Option<String>>,
    pub punch_out_source: __sdk::__query_builder::Col<Attendance, Option<String>>,
}

impl __sdk::__query_builder::HasCols for Attendance {
    type Cols = AttendanceCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        AttendanceCols {
            attendance_id: __sdk::__query_builder::Col::new(table_name, "attendance_id"),
            customer_id: __sdk::__query_builder::Col::new(table_name, "customer_id"),
            punch_in: __sdk::__query_builder::Col::new(table_name, "punch_in"),
            punch_out: __sdk::__query_builder::Col::new(table_name, "punch_out"),
            status: __sdk::__query_builder::Col::new(table_name, "status"),
            longitude_e_15: __sdk::__query_builder::Col::new(table_name, "longitude_e_15"),
            latitude_e_15: __sdk::__query_builder::Col::new(table_name, "latitude_e_15"),
            user_id: __sdk::__query_builder::Col::new(table_name, "user_id"),
            username: __sdk::__query_builder::Col::new(table_name, "username"),
            punch_in_source: __sdk::__query_builder::Col::new(table_name, "punch_in_source"),
            punch_out_source: __sdk::__query_builder::Col::new(table_name, "punch_out_source"),
        }
    }
}

/// Indexed column accessor struct for the table `Attendance`.
///
/// Provides typed access to indexed columns for query building.
pub struct AttendanceIxCols {
    pub attendance_id: __sdk::__query_builder::IxCol<Attendance, u64>,
    pub customer_id: __sdk::__query_builder::IxCol<Attendance, String>,
}

impl __sdk::__query_builder::HasIxCols for Attendance {
    type IxCols = AttendanceIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        AttendanceIxCols {
            attendance_id: __sdk::__query_builder::IxCol::new(table_name, "attendance_id"),
            customer_id: __sdk::__query_builder::IxCol::new(table_name, "customer_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Attendance {}
