// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct AttendanceLocationInput {
    pub location_name: String,
    pub address: Option<String>,
    pub longitude_e_15: i64,
    pub latitude_e_15: i64,
    pub radius_metres: i32,
    pub is_enabled: bool,
    pub remark: Option<String>,
}

impl __sdk::InModule for AttendanceLocationInput {
    type Module = super::RemoteModule;
}
