// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::attendance_device_input_type::AttendanceDeviceInput;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct AttendancePunchInput {
    pub punch_time: __sdk::Timestamp,
    pub longitude_e_15: i64,
    pub latitude_e_15: i64,
    pub device: AttendanceDeviceInput,
}

impl __sdk::InModule for AttendancePunchInput {
    type Module = super::RemoteModule;
}
