// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CompleteTenantProvisioningJobArgs {
    pub job_id: u64,
    pub lock_owner: String,
}

impl From<CompleteTenantProvisioningJobArgs> for super::Reducer {
    fn from(args: CompleteTenantProvisioningJobArgs) -> Self {
        Self::CompleteTenantProvisioningJob {
            job_id: args.job_id,
            lock_owner: args.lock_owner,
        }
    }
}

impl __sdk::InModule for CompleteTenantProvisioningJobArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `complete_tenant_provisioning_job`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait complete_tenant_provisioning_job {
    /// Request that the remote module invoke the reducer `complete_tenant_provisioning_job` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`complete_tenant_provisioning_job:complete_tenant_provisioning_job_then`] to run a callback after the reducer completes.
    fn complete_tenant_provisioning_job(
        &self,
        job_id: u64,
        lock_owner: String,
    ) -> __sdk::Result<()> {
        self.complete_tenant_provisioning_job_then(job_id, lock_owner, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `complete_tenant_provisioning_job` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn complete_tenant_provisioning_job_then(
        &self,
        job_id: u64,
        lock_owner: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl complete_tenant_provisioning_job for super::RemoteReducers {
    fn complete_tenant_provisioning_job_then(
        &self,
        job_id: u64,
        lock_owner: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            CompleteTenantProvisioningJobArgs { job_id, lock_owner },
            callback,
        )
    }
}
