// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ConfirmCarryoverBatchArgs {
    pub batch_id: u64,
}

impl From<ConfirmCarryoverBatchArgs> for super::Reducer {
    fn from(args: ConfirmCarryoverBatchArgs) -> Self {
        Self::ConfirmCarryoverBatch {
            batch_id: args.batch_id,
        }
    }
}

impl __sdk::InModule for ConfirmCarryoverBatchArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `confirm_carryover_batch`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait confirm_carryover_batch {
    /// Request that the remote module invoke the reducer `confirm_carryover_batch` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`confirm_carryover_batch:confirm_carryover_batch_then`] to run a callback after the reducer completes.
    fn confirm_carryover_batch(&self, batch_id: u64) -> __sdk::Result<()> {
        self.confirm_carryover_batch_then(batch_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `confirm_carryover_batch` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn confirm_carryover_batch_then(
        &self,
        batch_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl confirm_carryover_batch for super::RemoteReducers {
    fn confirm_carryover_batch_then(
        &self,
        batch_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(ConfirmCarryoverBatchArgs { batch_id }, callback)
    }
}
