// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct CrawlerTaskLog {
    pub log_id: u64,
    pub customer_id: String,
    pub task_id: u64,
    pub level: String,
    pub stage: String,
    pub message: String,
    pub detail_json: Option<String>,
    pub created_at: __sdk::Timestamp,
}

impl __sdk::InModule for CrawlerTaskLog {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `CrawlerTaskLog`.
///
/// Provides typed access to columns for query building.
pub struct CrawlerTaskLogCols {
    pub log_id: __sdk::__query_builder::Col<CrawlerTaskLog, u64>,
    pub customer_id: __sdk::__query_builder::Col<CrawlerTaskLog, String>,
    pub task_id: __sdk::__query_builder::Col<CrawlerTaskLog, u64>,
    pub level: __sdk::__query_builder::Col<CrawlerTaskLog, String>,
    pub stage: __sdk::__query_builder::Col<CrawlerTaskLog, String>,
    pub message: __sdk::__query_builder::Col<CrawlerTaskLog, String>,
    pub detail_json: __sdk::__query_builder::Col<CrawlerTaskLog, Option<String>>,
    pub created_at: __sdk::__query_builder::Col<CrawlerTaskLog, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for CrawlerTaskLog {
    type Cols = CrawlerTaskLogCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        CrawlerTaskLogCols {
            log_id: __sdk::__query_builder::Col::new(table_name, "log_id"),
            customer_id: __sdk::__query_builder::Col::new(table_name, "customer_id"),
            task_id: __sdk::__query_builder::Col::new(table_name, "task_id"),
            level: __sdk::__query_builder::Col::new(table_name, "level"),
            stage: __sdk::__query_builder::Col::new(table_name, "stage"),
            message: __sdk::__query_builder::Col::new(table_name, "message"),
            detail_json: __sdk::__query_builder::Col::new(table_name, "detail_json"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
        }
    }
}

/// Indexed column accessor struct for the table `CrawlerTaskLog`.
///
/// Provides typed access to indexed columns for query building.
pub struct CrawlerTaskLogIxCols {
    pub customer_id: __sdk::__query_builder::IxCol<CrawlerTaskLog, String>,
    pub log_id: __sdk::__query_builder::IxCol<CrawlerTaskLog, u64>,
    pub stage: __sdk::__query_builder::IxCol<CrawlerTaskLog, String>,
    pub task_id: __sdk::__query_builder::IxCol<CrawlerTaskLog, u64>,
}

impl __sdk::__query_builder::HasIxCols for CrawlerTaskLog {
    type IxCols = CrawlerTaskLogIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        CrawlerTaskLogIxCols {
            customer_id: __sdk::__query_builder::IxCol::new(table_name, "customer_id"),
            log_id: __sdk::__query_builder::IxCol::new(table_name, "log_id"),
            stage: __sdk::__query_builder::IxCol::new(table_name, "stage"),
            task_id: __sdk::__query_builder::IxCol::new(table_name, "task_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for CrawlerTaskLog {}
