// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct CrawlerTaskItem {
    pub item_id: u64,
    pub customer_id: String,
    pub source_id: u64,
    pub last_task_id: u64,
    pub source_ref_type: Option<String>,
    pub source_ref_id: Option<u64>,
    pub source_url: String,
    pub url_hash: String,
    pub status: String,
    pub retry_count: u32,
    pub max_retry_count: u32,
    pub next_retry_at: Option<__sdk::Timestamp>,
    pub last_http_status: Option<i32>,
    pub last_error: Option<String>,
    pub skip_reason: Option<String>,
    pub published_at: Option<__sdk::Timestamp>,
    pub last_started_at: Option<__sdk::Timestamp>,
    pub last_finished_at: Option<__sdk::Timestamp>,
    pub last_success_at: Option<__sdk::Timestamp>,
    pub response_hash: Option<String>,
    pub parsed_payload_json: Option<String>,
    pub created_at: __sdk::Timestamp,
    pub updated_at: __sdk::Timestamp,
}

impl __sdk::InModule for CrawlerTaskItem {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `CrawlerTaskItem`.
///
/// Provides typed access to columns for query building.
pub struct CrawlerTaskItemCols {
    pub item_id: __sdk::__query_builder::Col<CrawlerTaskItem, u64>,
    pub customer_id: __sdk::__query_builder::Col<CrawlerTaskItem, String>,
    pub source_id: __sdk::__query_builder::Col<CrawlerTaskItem, u64>,
    pub last_task_id: __sdk::__query_builder::Col<CrawlerTaskItem, u64>,
    pub source_ref_type: __sdk::__query_builder::Col<CrawlerTaskItem, Option<String>>,
    pub source_ref_id: __sdk::__query_builder::Col<CrawlerTaskItem, Option<u64>>,
    pub source_url: __sdk::__query_builder::Col<CrawlerTaskItem, String>,
    pub url_hash: __sdk::__query_builder::Col<CrawlerTaskItem, String>,
    pub status: __sdk::__query_builder::Col<CrawlerTaskItem, String>,
    pub retry_count: __sdk::__query_builder::Col<CrawlerTaskItem, u32>,
    pub max_retry_count: __sdk::__query_builder::Col<CrawlerTaskItem, u32>,
    pub next_retry_at: __sdk::__query_builder::Col<CrawlerTaskItem, Option<__sdk::Timestamp>>,
    pub last_http_status: __sdk::__query_builder::Col<CrawlerTaskItem, Option<i32>>,
    pub last_error: __sdk::__query_builder::Col<CrawlerTaskItem, Option<String>>,
    pub skip_reason: __sdk::__query_builder::Col<CrawlerTaskItem, Option<String>>,
    pub published_at: __sdk::__query_builder::Col<CrawlerTaskItem, Option<__sdk::Timestamp>>,
    pub last_started_at: __sdk::__query_builder::Col<CrawlerTaskItem, Option<__sdk::Timestamp>>,
    pub last_finished_at: __sdk::__query_builder::Col<CrawlerTaskItem, Option<__sdk::Timestamp>>,
    pub last_success_at: __sdk::__query_builder::Col<CrawlerTaskItem, Option<__sdk::Timestamp>>,
    pub response_hash: __sdk::__query_builder::Col<CrawlerTaskItem, Option<String>>,
    pub parsed_payload_json: __sdk::__query_builder::Col<CrawlerTaskItem, Option<String>>,
    pub created_at: __sdk::__query_builder::Col<CrawlerTaskItem, __sdk::Timestamp>,
    pub updated_at: __sdk::__query_builder::Col<CrawlerTaskItem, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for CrawlerTaskItem {
    type Cols = CrawlerTaskItemCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        CrawlerTaskItemCols {
            item_id: __sdk::__query_builder::Col::new(table_name, "item_id"),
            customer_id: __sdk::__query_builder::Col::new(table_name, "customer_id"),
            source_id: __sdk::__query_builder::Col::new(table_name, "source_id"),
            last_task_id: __sdk::__query_builder::Col::new(table_name, "last_task_id"),
            source_ref_type: __sdk::__query_builder::Col::new(table_name, "source_ref_type"),
            source_ref_id: __sdk::__query_builder::Col::new(table_name, "source_ref_id"),
            source_url: __sdk::__query_builder::Col::new(table_name, "source_url"),
            url_hash: __sdk::__query_builder::Col::new(table_name, "url_hash"),
            status: __sdk::__query_builder::Col::new(table_name, "status"),
            retry_count: __sdk::__query_builder::Col::new(table_name, "retry_count"),
            max_retry_count: __sdk::__query_builder::Col::new(table_name, "max_retry_count"),
            next_retry_at: __sdk::__query_builder::Col::new(table_name, "next_retry_at"),
            last_http_status: __sdk::__query_builder::Col::new(table_name, "last_http_status"),
            last_error: __sdk::__query_builder::Col::new(table_name, "last_error"),
            skip_reason: __sdk::__query_builder::Col::new(table_name, "skip_reason"),
            published_at: __sdk::__query_builder::Col::new(table_name, "published_at"),
            last_started_at: __sdk::__query_builder::Col::new(table_name, "last_started_at"),
            last_finished_at: __sdk::__query_builder::Col::new(table_name, "last_finished_at"),
            last_success_at: __sdk::__query_builder::Col::new(table_name, "last_success_at"),
            response_hash: __sdk::__query_builder::Col::new(table_name, "response_hash"),
            parsed_payload_json: __sdk::__query_builder::Col::new(
                table_name,
                "parsed_payload_json",
            ),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
        }
    }
}

/// Indexed column accessor struct for the table `CrawlerTaskItem`.
///
/// Provides typed access to indexed columns for query building.
pub struct CrawlerTaskItemIxCols {
    pub customer_id: __sdk::__query_builder::IxCol<CrawlerTaskItem, String>,
    pub item_id: __sdk::__query_builder::IxCol<CrawlerTaskItem, u64>,
    pub last_task_id: __sdk::__query_builder::IxCol<CrawlerTaskItem, u64>,
    pub source_id: __sdk::__query_builder::IxCol<CrawlerTaskItem, u64>,
    pub status: __sdk::__query_builder::IxCol<CrawlerTaskItem, String>,
}

impl __sdk::__query_builder::HasIxCols for CrawlerTaskItem {
    type IxCols = CrawlerTaskItemIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        CrawlerTaskItemIxCols {
            customer_id: __sdk::__query_builder::IxCol::new(table_name, "customer_id"),
            item_id: __sdk::__query_builder::IxCol::new(table_name, "item_id"),
            last_task_id: __sdk::__query_builder::IxCol::new(table_name, "last_task_id"),
            source_id: __sdk::__query_builder::IxCol::new(table_name, "source_id"),
            status: __sdk::__query_builder::IxCol::new(table_name, "status"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for CrawlerTaskItem {}
