// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CreateMenuArgs {
    pub name: String,
    pub menu_type: String,
    pub path: String,
    pub component: Option<String>,
    pub parent_id: Option<u64>,
}

impl From<CreateMenuArgs> for super::Reducer {
    fn from(args: CreateMenuArgs) -> Self {
        Self::CreateMenu {
            name: args.name,
            menu_type: args.menu_type,
            path: args.path,
            component: args.component,
            parent_id: args.parent_id,
        }
    }
}

impl __sdk::InModule for CreateMenuArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `create_menu`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait create_menu {
    /// Request that the remote module invoke the reducer `create_menu` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`create_menu:create_menu_then`] to run a callback after the reducer completes.
    fn create_menu(
        &self,
        name: String,
        menu_type: String,
        path: String,
        component: Option<String>,
        parent_id: Option<u64>,
    ) -> __sdk::Result<()> {
        self.create_menu_then(name, menu_type, path, component, parent_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `create_menu` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn create_menu_then(
        &self,
        name: String,
        menu_type: String,
        path: String,
        component: Option<String>,
        parent_id: Option<u64>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl create_menu for super::RemoteReducers {
    fn create_menu_then(
        &self,
        name: String,
        menu_type: String,
        path: String,
        component: Option<String>,
        parent_id: Option<u64>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            CreateMenuArgs {
                name,
                menu_type,
                path,
                component,
                parent_id,
            },
            callback,
        )
    }
}
