// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::company_lead_input_type::CompanyLeadInput;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CreateCompanyLeadArgs {
    pub input: CompanyLeadInput,
}

impl From<CreateCompanyLeadArgs> for super::Reducer {
    fn from(args: CreateCompanyLeadArgs) -> Self {
        Self::CreateCompanyLead { input: args.input }
    }
}

impl __sdk::InModule for CreateCompanyLeadArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `create_company_lead`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait create_company_lead {
    /// Request that the remote module invoke the reducer `create_company_lead` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`create_company_lead:create_company_lead_then`] to run a callback after the reducer completes.
    fn create_company_lead(&self, input: CompanyLeadInput) -> __sdk::Result<()> {
        self.create_company_lead_then(input, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `create_company_lead` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn create_company_lead_then(
        &self,
        input: CompanyLeadInput,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl create_company_lead for super::RemoteReducers {
    fn create_company_lead_then(
        &self,
        input: CompanyLeadInput,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(CreateCompanyLeadArgs { input }, callback)
    }
}
