// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CreateCustomerArgs {
    pub customer_id: String,
    pub name: String,
    pub db_name: Option<String>,
}

impl From<CreateCustomerArgs> for super::Reducer {
    fn from(args: CreateCustomerArgs) -> Self {
        Self::CreateCustomer {
            customer_id: args.customer_id,
            name: args.name,
            db_name: args.db_name,
        }
    }
}

impl __sdk::InModule for CreateCustomerArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `create_customer`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait create_customer {
    /// Request that the remote module invoke the reducer `create_customer` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`create_customer:create_customer_then`] to run a callback after the reducer completes.
    fn create_customer(
        &self,
        customer_id: String,
        name: String,
        db_name: Option<String>,
    ) -> __sdk::Result<()> {
        self.create_customer_then(customer_id, name, db_name, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `create_customer` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn create_customer_then(
        &self,
        customer_id: String,
        name: String,
        db_name: Option<String>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl create_customer for super::RemoteReducers {
    fn create_customer_then(
        &self,
        customer_id: String,
        name: String,
        db_name: Option<String>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            CreateCustomerArgs {
                customer_id,
                name,
                db_name,
            },
            callback,
        )
    }
}
