// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CreateOrganizationArgs {
    pub city: String,
    pub company_short_name: String,
}

impl From<CreateOrganizationArgs> for super::Reducer {
    fn from(args: CreateOrganizationArgs) -> Self {
        Self::CreateOrganization {
            city: args.city,
            company_short_name: args.company_short_name,
        }
    }
}

impl __sdk::InModule for CreateOrganizationArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `create_organization`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait create_organization {
    /// Request that the remote module invoke the reducer `create_organization` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`create_organization:create_organization_then`] to run a callback after the reducer completes.
    fn create_organization(&self, city: String, company_short_name: String) -> __sdk::Result<()> {
        self.create_organization_then(city, company_short_name, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `create_organization` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn create_organization_then(
        &self,
        city: String,
        company_short_name: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl create_organization for super::RemoteReducers {
    fn create_organization_then(
        &self,
        city: String,
        company_short_name: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            CreateOrganizationArgs {
                city,
                company_short_name,
            },
            callback,
        )
    }
}
