// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::invitation_input_type::InvitationInput;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CreateTenantInvitationArgs {
    pub customer_id: String,
    pub input: InvitationInput,
}

impl From<CreateTenantInvitationArgs> for super::Reducer {
    fn from(args: CreateTenantInvitationArgs) -> Self {
        Self::CreateTenantInvitation {
            customer_id: args.customer_id,
            input: args.input,
        }
    }
}

impl __sdk::InModule for CreateTenantInvitationArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `create_tenant_invitation`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait create_tenant_invitation {
    /// Request that the remote module invoke the reducer `create_tenant_invitation` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`create_tenant_invitation:create_tenant_invitation_then`] to run a callback after the reducer completes.
    fn create_tenant_invitation(
        &self,
        customer_id: String,
        input: InvitationInput,
    ) -> __sdk::Result<()> {
        self.create_tenant_invitation_then(customer_id, input, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `create_tenant_invitation` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn create_tenant_invitation_then(
        &self,
        customer_id: String,
        input: InvitationInput,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl create_tenant_invitation for super::RemoteReducers {
    fn create_tenant_invitation_then(
        &self,
        customer_id: String,
        input: InvitationInput,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            CreateTenantInvitationArgs { customer_id, input },
            callback,
        )
    }
}
