// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::factory_floor_input_type::FactoryFloorInput;
use super::factory_input_type::FactoryInput;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CreateFactoryWithFloorsArgs {
    pub input: FactoryInput,
    pub floors: Vec<FactoryFloorInput>,
}

impl From<CreateFactoryWithFloorsArgs> for super::Reducer {
    fn from(args: CreateFactoryWithFloorsArgs) -> Self {
        Self::CreateFactoryWithFloors {
            input: args.input,
            floors: args.floors,
        }
    }
}

impl __sdk::InModule for CreateFactoryWithFloorsArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `create_factory_with_floors`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait create_factory_with_floors {
    /// Request that the remote module invoke the reducer `create_factory_with_floors` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`create_factory_with_floors:create_factory_with_floors_then`] to run a callback after the reducer completes.
    fn create_factory_with_floors(
        &self,
        input: FactoryInput,
        floors: Vec<FactoryFloorInput>,
    ) -> __sdk::Result<()> {
        self.create_factory_with_floors_then(input, floors, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `create_factory_with_floors` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn create_factory_with_floors_then(
        &self,
        input: FactoryInput,
        floors: Vec<FactoryFloorInput>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl create_factory_with_floors for super::RemoteReducers {
    fn create_factory_with_floors_then(
        &self,
        input: FactoryInput,
        floors: Vec<FactoryFloorInput>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(CreateFactoryWithFloorsArgs { input, floors }, callback)
    }
}
