// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CreateCenterUserArgs {
    pub username: String,
    pub real_name: String,
    pub phone: Option<String>,
}

impl From<CreateCenterUserArgs> for super::Reducer {
    fn from(args: CreateCenterUserArgs) -> Self {
        Self::CreateCenterUser {
            username: args.username,
            real_name: args.real_name,
            phone: args.phone,
        }
    }
}

impl __sdk::InModule for CreateCenterUserArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `create_center_user`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait create_center_user {
    /// Request that the remote module invoke the reducer `create_center_user` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`create_center_user:create_center_user_then`] to run a callback after the reducer completes.
    fn create_center_user(
        &self,
        username: String,
        real_name: String,
        phone: Option<String>,
    ) -> __sdk::Result<()> {
        self.create_center_user_then(username, real_name, phone, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `create_center_user` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn create_center_user_then(
        &self,
        username: String,
        real_name: String,
        phone: Option<String>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl create_center_user for super::RemoteReducers {
    fn create_center_user_then(
        &self,
        username: String,
        real_name: String,
        phone: Option<String>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            CreateCenterUserArgs {
                username,
                real_name,
                phone,
            },
            callback,
        )
    }
}
