// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::finance_input_type::FinanceInput;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CreateFinanceArgs {
    pub input: FinanceInput,
}

impl From<CreateFinanceArgs> for super::Reducer {
    fn from(args: CreateFinanceArgs) -> Self {
        Self::CreateFinance { input: args.input }
    }
}

impl __sdk::InModule for CreateFinanceArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `create_finance`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait create_finance {
    /// Request that the remote module invoke the reducer `create_finance` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`create_finance:create_finance_then`] to run a callback after the reducer completes.
    fn create_finance(&self, input: FinanceInput) -> __sdk::Result<()> {
        self.create_finance_then(input, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `create_finance` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn create_finance_then(
        &self,
        input: FinanceInput,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl create_finance for super::RemoteReducers {
    fn create_finance_then(
        &self,
        input: FinanceInput,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(CreateFinanceArgs { input }, callback)
    }
}
