// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::elevator_asset_input_type::ElevatorAssetInput;
use super::uploaded_maintenance_image_input_type::UploadedMaintenanceImageInput;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CreateElevatorAssetArgs {
    pub input: ElevatorAssetInput,
    pub uploads: Vec<UploadedMaintenanceImageInput>,
}

impl From<CreateElevatorAssetArgs> for super::Reducer {
    fn from(args: CreateElevatorAssetArgs) -> Self {
        Self::CreateElevatorAsset {
            input: args.input,
            uploads: args.uploads,
        }
    }
}

impl __sdk::InModule for CreateElevatorAssetArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `create_elevator_asset`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait create_elevator_asset {
    /// Request that the remote module invoke the reducer `create_elevator_asset` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`create_elevator_asset:create_elevator_asset_then`] to run a callback after the reducer completes.
    fn create_elevator_asset(
        &self,
        input: ElevatorAssetInput,
        uploads: Vec<UploadedMaintenanceImageInput>,
    ) -> __sdk::Result<()> {
        self.create_elevator_asset_then(input, uploads, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `create_elevator_asset` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn create_elevator_asset_then(
        &self,
        input: ElevatorAssetInput,
        uploads: Vec<UploadedMaintenanceImageInput>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl create_elevator_asset for super::RemoteReducers {
    fn create_elevator_asset_then(
        &self,
        input: ElevatorAssetInput,
        uploads: Vec<UploadedMaintenanceImageInput>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(CreateElevatorAssetArgs { input, uploads }, callback)
    }
}
