// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Customer {
    pub customer_id: String,
    pub name: String,
    pub city: Option<String>,
    pub company_short_name: Option<String>,
    pub code: Option<String>,
    pub status: i8,
    pub db_name: Option<String>,
    pub created_at: __sdk::Timestamp,
    pub updated_at: Option<__sdk::Timestamp>,
}

impl __sdk::InModule for Customer {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Customer`.
///
/// Provides typed access to columns for query building.
pub struct CustomerCols {
    pub customer_id: __sdk::__query_builder::Col<Customer, String>,
    pub name: __sdk::__query_builder::Col<Customer, String>,
    pub city: __sdk::__query_builder::Col<Customer, Option<String>>,
    pub company_short_name: __sdk::__query_builder::Col<Customer, Option<String>>,
    pub code: __sdk::__query_builder::Col<Customer, Option<String>>,
    pub status: __sdk::__query_builder::Col<Customer, i8>,
    pub db_name: __sdk::__query_builder::Col<Customer, Option<String>>,
    pub created_at: __sdk::__query_builder::Col<Customer, __sdk::Timestamp>,
    pub updated_at: __sdk::__query_builder::Col<Customer, Option<__sdk::Timestamp>>,
}

impl __sdk::__query_builder::HasCols for Customer {
    type Cols = CustomerCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        CustomerCols {
            customer_id: __sdk::__query_builder::Col::new(table_name, "customer_id"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            city: __sdk::__query_builder::Col::new(table_name, "city"),
            company_short_name: __sdk::__query_builder::Col::new(table_name, "company_short_name"),
            code: __sdk::__query_builder::Col::new(table_name, "code"),
            status: __sdk::__query_builder::Col::new(table_name, "status"),
            db_name: __sdk::__query_builder::Col::new(table_name, "db_name"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
        }
    }
}

/// Indexed column accessor struct for the table `Customer`.
///
/// Provides typed access to indexed columns for query building.
pub struct CustomerIxCols {
    pub customer_id: __sdk::__query_builder::IxCol<Customer, String>,
}

impl __sdk::__query_builder::HasIxCols for Customer {
    type IxCols = CustomerIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        CustomerIxCols {
            customer_id: __sdk::__query_builder::IxCol::new(table_name, "customer_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Customer {}
