// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::dashboard_revenue_pulse_type::DashboardRevenuePulse;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct DashboardOverview {
    pub customer_id: String,
    pub factory_count: u64,
    pub tenant_count: u64,
    pub occupied_area_centi_square_metres: i64,
    pub receivable_cents: i64,
    pub received_cents: i64,
    pub outstanding_cents: i64,
    pub outstanding_bill_count: u64,
    pub investment_count: u64,
    pub pending_reimbursement_count: u64,
    pub employee_count: u64,
    pub revenue_pulse: Vec<DashboardRevenuePulse>,
}

impl __sdk::InModule for DashboardOverview {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `DashboardOverview`.
///
/// Provides typed access to columns for query building.
pub struct DashboardOverviewCols {
    pub customer_id: __sdk::__query_builder::Col<DashboardOverview, String>,
    pub factory_count: __sdk::__query_builder::Col<DashboardOverview, u64>,
    pub tenant_count: __sdk::__query_builder::Col<DashboardOverview, u64>,
    pub occupied_area_centi_square_metres: __sdk::__query_builder::Col<DashboardOverview, i64>,
    pub receivable_cents: __sdk::__query_builder::Col<DashboardOverview, i64>,
    pub received_cents: __sdk::__query_builder::Col<DashboardOverview, i64>,
    pub outstanding_cents: __sdk::__query_builder::Col<DashboardOverview, i64>,
    pub outstanding_bill_count: __sdk::__query_builder::Col<DashboardOverview, u64>,
    pub investment_count: __sdk::__query_builder::Col<DashboardOverview, u64>,
    pub pending_reimbursement_count: __sdk::__query_builder::Col<DashboardOverview, u64>,
    pub employee_count: __sdk::__query_builder::Col<DashboardOverview, u64>,
    pub revenue_pulse: __sdk::__query_builder::Col<DashboardOverview, Vec<DashboardRevenuePulse>>,
}

impl __sdk::__query_builder::HasCols for DashboardOverview {
    type Cols = DashboardOverviewCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        DashboardOverviewCols {
            customer_id: __sdk::__query_builder::Col::new(table_name, "customer_id"),
            factory_count: __sdk::__query_builder::Col::new(table_name, "factory_count"),
            tenant_count: __sdk::__query_builder::Col::new(table_name, "tenant_count"),
            occupied_area_centi_square_metres: __sdk::__query_builder::Col::new(
                table_name,
                "occupied_area_centi_square_metres",
            ),
            receivable_cents: __sdk::__query_builder::Col::new(table_name, "receivable_cents"),
            received_cents: __sdk::__query_builder::Col::new(table_name, "received_cents"),
            outstanding_cents: __sdk::__query_builder::Col::new(table_name, "outstanding_cents"),
            outstanding_bill_count: __sdk::__query_builder::Col::new(
                table_name,
                "outstanding_bill_count",
            ),
            investment_count: __sdk::__query_builder::Col::new(table_name, "investment_count"),
            pending_reimbursement_count: __sdk::__query_builder::Col::new(
                table_name,
                "pending_reimbursement_count",
            ),
            employee_count: __sdk::__query_builder::Col::new(table_name, "employee_count"),
            revenue_pulse: __sdk::__query_builder::Col::new(table_name, "revenue_pulse"),
        }
    }
}
