// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct DeleteEleBillArgs {
    pub ele_id: u64,
}

impl From<DeleteEleBillArgs> for super::Reducer {
    fn from(args: DeleteEleBillArgs) -> Self {
        Self::DeleteEleBill {
            ele_id: args.ele_id,
        }
    }
}

impl __sdk::InModule for DeleteEleBillArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `delete_ele_bill`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait delete_ele_bill {
    /// Request that the remote module invoke the reducer `delete_ele_bill` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`delete_ele_bill:delete_ele_bill_then`] to run a callback after the reducer completes.
    fn delete_ele_bill(&self, ele_id: u64) -> __sdk::Result<()> {
        self.delete_ele_bill_then(ele_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `delete_ele_bill` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn delete_ele_bill_then(
        &self,
        ele_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl delete_ele_bill for super::RemoteReducers {
    fn delete_ele_bill_then(
        &self,
        ele_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(DeleteEleBillArgs { ele_id }, callback)
    }
}
