// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct DeviceAsset {
    pub asset_id: u64,
    pub customer_id: String,
    pub park_id: u64,
    pub factory_id: u64,
    pub device_class: String,
    pub device_type: String,
    pub device_name: String,
    pub device_code: String,
    pub location: String,
    pub vendor: Option<String>,
    pub model: Option<String>,
    pub external_device_id: Option<String>,
    pub commissioned_on: Option<String>,
    pub remark: Option<String>,
    pub is_deleted: bool,
    pub created_at: __sdk::Timestamp,
    pub updated_at: Option<__sdk::Timestamp>,
    pub gateway_id: u64,
    pub channel_no: u32,
}

impl __sdk::InModule for DeviceAsset {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `DeviceAsset`.
///
/// Provides typed access to columns for query building.
pub struct DeviceAssetCols {
    pub asset_id: __sdk::__query_builder::Col<DeviceAsset, u64>,
    pub customer_id: __sdk::__query_builder::Col<DeviceAsset, String>,
    pub park_id: __sdk::__query_builder::Col<DeviceAsset, u64>,
    pub factory_id: __sdk::__query_builder::Col<DeviceAsset, u64>,
    pub device_class: __sdk::__query_builder::Col<DeviceAsset, String>,
    pub device_type: __sdk::__query_builder::Col<DeviceAsset, String>,
    pub device_name: __sdk::__query_builder::Col<DeviceAsset, String>,
    pub device_code: __sdk::__query_builder::Col<DeviceAsset, String>,
    pub location: __sdk::__query_builder::Col<DeviceAsset, String>,
    pub vendor: __sdk::__query_builder::Col<DeviceAsset, Option<String>>,
    pub model: __sdk::__query_builder::Col<DeviceAsset, Option<String>>,
    pub external_device_id: __sdk::__query_builder::Col<DeviceAsset, Option<String>>,
    pub commissioned_on: __sdk::__query_builder::Col<DeviceAsset, Option<String>>,
    pub remark: __sdk::__query_builder::Col<DeviceAsset, Option<String>>,
    pub is_deleted: __sdk::__query_builder::Col<DeviceAsset, bool>,
    pub created_at: __sdk::__query_builder::Col<DeviceAsset, __sdk::Timestamp>,
    pub updated_at: __sdk::__query_builder::Col<DeviceAsset, Option<__sdk::Timestamp>>,
    pub gateway_id: __sdk::__query_builder::Col<DeviceAsset, u64>,
    pub channel_no: __sdk::__query_builder::Col<DeviceAsset, u32>,
}

impl __sdk::__query_builder::HasCols for DeviceAsset {
    type Cols = DeviceAssetCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        DeviceAssetCols {
            asset_id: __sdk::__query_builder::Col::new(table_name, "asset_id"),
            customer_id: __sdk::__query_builder::Col::new(table_name, "customer_id"),
            park_id: __sdk::__query_builder::Col::new(table_name, "park_id"),
            factory_id: __sdk::__query_builder::Col::new(table_name, "factory_id"),
            device_class: __sdk::__query_builder::Col::new(table_name, "device_class"),
            device_type: __sdk::__query_builder::Col::new(table_name, "device_type"),
            device_name: __sdk::__query_builder::Col::new(table_name, "device_name"),
            device_code: __sdk::__query_builder::Col::new(table_name, "device_code"),
            location: __sdk::__query_builder::Col::new(table_name, "location"),
            vendor: __sdk::__query_builder::Col::new(table_name, "vendor"),
            model: __sdk::__query_builder::Col::new(table_name, "model"),
            external_device_id: __sdk::__query_builder::Col::new(table_name, "external_device_id"),
            commissioned_on: __sdk::__query_builder::Col::new(table_name, "commissioned_on"),
            remark: __sdk::__query_builder::Col::new(table_name, "remark"),
            is_deleted: __sdk::__query_builder::Col::new(table_name, "is_deleted"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
            gateway_id: __sdk::__query_builder::Col::new(table_name, "gateway_id"),
            channel_no: __sdk::__query_builder::Col::new(table_name, "channel_no"),
        }
    }
}

/// Indexed column accessor struct for the table `DeviceAsset`.
///
/// Provides typed access to indexed columns for query building.
pub struct DeviceAssetIxCols {
    pub asset_id: __sdk::__query_builder::IxCol<DeviceAsset, u64>,
    pub customer_id: __sdk::__query_builder::IxCol<DeviceAsset, String>,
    pub factory_id: __sdk::__query_builder::IxCol<DeviceAsset, u64>,
    pub park_id: __sdk::__query_builder::IxCol<DeviceAsset, u64>,
}

impl __sdk::__query_builder::HasIxCols for DeviceAsset {
    type IxCols = DeviceAssetIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        DeviceAssetIxCols {
            asset_id: __sdk::__query_builder::IxCol::new(table_name, "asset_id"),
            customer_id: __sdk::__query_builder::IxCol::new(table_name, "customer_id"),
            factory_id: __sdk::__query_builder::IxCol::new(table_name, "factory_id"),
            park_id: __sdk::__query_builder::IxCol::new(table_name, "park_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for DeviceAsset {}
