// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct DeviceAssetImage {
    pub id: u64,
    pub asset_id: u64,
    pub img_id: u64,
    pub created_at: __sdk::Timestamp,
    pub updated_at: Option<__sdk::Timestamp>,
}

impl __sdk::InModule for DeviceAssetImage {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `DeviceAssetImage`.
///
/// Provides typed access to columns for query building.
pub struct DeviceAssetImageCols {
    pub id: __sdk::__query_builder::Col<DeviceAssetImage, u64>,
    pub asset_id: __sdk::__query_builder::Col<DeviceAssetImage, u64>,
    pub img_id: __sdk::__query_builder::Col<DeviceAssetImage, u64>,
    pub created_at: __sdk::__query_builder::Col<DeviceAssetImage, __sdk::Timestamp>,
    pub updated_at: __sdk::__query_builder::Col<DeviceAssetImage, Option<__sdk::Timestamp>>,
}

impl __sdk::__query_builder::HasCols for DeviceAssetImage {
    type Cols = DeviceAssetImageCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        DeviceAssetImageCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            asset_id: __sdk::__query_builder::Col::new(table_name, "asset_id"),
            img_id: __sdk::__query_builder::Col::new(table_name, "img_id"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
        }
    }
}

/// Indexed column accessor struct for the table `DeviceAssetImage`.
///
/// Provides typed access to indexed columns for query building.
pub struct DeviceAssetImageIxCols {
    pub asset_id: __sdk::__query_builder::IxCol<DeviceAssetImage, u64>,
    pub id: __sdk::__query_builder::IxCol<DeviceAssetImage, u64>,
    pub img_id: __sdk::__query_builder::IxCol<DeviceAssetImage, u64>,
}

impl __sdk::__query_builder::HasIxCols for DeviceAssetImage {
    type IxCols = DeviceAssetImageIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        DeviceAssetImageIxCols {
            asset_id: __sdk::__query_builder::IxCol::new(table_name, "asset_id"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            img_id: __sdk::__query_builder::IxCol::new(table_name, "img_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for DeviceAssetImage {}
