// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Dormitory {
    pub dormitory_id: u64,
    pub customer_id: String,
    pub park_id: u64,
    pub dormitory_name: String,
    pub remark: Option<String>,
    pub is_deleted: bool,
    pub created_at: __sdk::Timestamp,
    pub updated_at: Option<__sdk::Timestamp>,
}

impl __sdk::InModule for Dormitory {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Dormitory`.
///
/// Provides typed access to columns for query building.
pub struct DormitoryCols {
    pub dormitory_id: __sdk::__query_builder::Col<Dormitory, u64>,
    pub customer_id: __sdk::__query_builder::Col<Dormitory, String>,
    pub park_id: __sdk::__query_builder::Col<Dormitory, u64>,
    pub dormitory_name: __sdk::__query_builder::Col<Dormitory, String>,
    pub remark: __sdk::__query_builder::Col<Dormitory, Option<String>>,
    pub is_deleted: __sdk::__query_builder::Col<Dormitory, bool>,
    pub created_at: __sdk::__query_builder::Col<Dormitory, __sdk::Timestamp>,
    pub updated_at: __sdk::__query_builder::Col<Dormitory, Option<__sdk::Timestamp>>,
}

impl __sdk::__query_builder::HasCols for Dormitory {
    type Cols = DormitoryCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        DormitoryCols {
            dormitory_id: __sdk::__query_builder::Col::new(table_name, "dormitory_id"),
            customer_id: __sdk::__query_builder::Col::new(table_name, "customer_id"),
            park_id: __sdk::__query_builder::Col::new(table_name, "park_id"),
            dormitory_name: __sdk::__query_builder::Col::new(table_name, "dormitory_name"),
            remark: __sdk::__query_builder::Col::new(table_name, "remark"),
            is_deleted: __sdk::__query_builder::Col::new(table_name, "is_deleted"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
        }
    }
}

/// Indexed column accessor struct for the table `Dormitory`.
///
/// Provides typed access to indexed columns for query building.
pub struct DormitoryIxCols {
    pub customer_id: __sdk::__query_builder::IxCol<Dormitory, String>,
    pub dormitory_id: __sdk::__query_builder::IxCol<Dormitory, u64>,
    pub park_id: __sdk::__query_builder::IxCol<Dormitory, u64>,
}

impl __sdk::__query_builder::HasIxCols for Dormitory {
    type IxCols = DormitoryIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        DormitoryIxCols {
            customer_id: __sdk::__query_builder::IxCol::new(table_name, "customer_id"),
            dormitory_id: __sdk::__query_builder::IxCol::new(table_name, "dormitory_id"),
            park_id: __sdk::__query_builder::IxCol::new(table_name, "park_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Dormitory {}
