// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct DormitoryFloor {
    pub dormitory_floor_id: u64,
    pub customer_id: String,
    pub dormitory_id: u64,
    pub floor_no: i32,
    pub room_count: i32,
    pub room_area_centi_square_metres: Option<i64>,
    pub floor_height_centi_metres: Option<i64>,
    pub rent_price_cents: Option<i64>,
    pub remark: Option<String>,
    pub is_deleted: bool,
    pub created_at: __sdk::Timestamp,
    pub updated_at: Option<__sdk::Timestamp>,
}

impl __sdk::InModule for DormitoryFloor {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `DormitoryFloor`.
///
/// Provides typed access to columns for query building.
pub struct DormitoryFloorCols {
    pub dormitory_floor_id: __sdk::__query_builder::Col<DormitoryFloor, u64>,
    pub customer_id: __sdk::__query_builder::Col<DormitoryFloor, String>,
    pub dormitory_id: __sdk::__query_builder::Col<DormitoryFloor, u64>,
    pub floor_no: __sdk::__query_builder::Col<DormitoryFloor, i32>,
    pub room_count: __sdk::__query_builder::Col<DormitoryFloor, i32>,
    pub room_area_centi_square_metres: __sdk::__query_builder::Col<DormitoryFloor, Option<i64>>,
    pub floor_height_centi_metres: __sdk::__query_builder::Col<DormitoryFloor, Option<i64>>,
    pub rent_price_cents: __sdk::__query_builder::Col<DormitoryFloor, Option<i64>>,
    pub remark: __sdk::__query_builder::Col<DormitoryFloor, Option<String>>,
    pub is_deleted: __sdk::__query_builder::Col<DormitoryFloor, bool>,
    pub created_at: __sdk::__query_builder::Col<DormitoryFloor, __sdk::Timestamp>,
    pub updated_at: __sdk::__query_builder::Col<DormitoryFloor, Option<__sdk::Timestamp>>,
}

impl __sdk::__query_builder::HasCols for DormitoryFloor {
    type Cols = DormitoryFloorCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        DormitoryFloorCols {
            dormitory_floor_id: __sdk::__query_builder::Col::new(table_name, "dormitory_floor_id"),
            customer_id: __sdk::__query_builder::Col::new(table_name, "customer_id"),
            dormitory_id: __sdk::__query_builder::Col::new(table_name, "dormitory_id"),
            floor_no: __sdk::__query_builder::Col::new(table_name, "floor_no"),
            room_count: __sdk::__query_builder::Col::new(table_name, "room_count"),
            room_area_centi_square_metres: __sdk::__query_builder::Col::new(
                table_name,
                "room_area_centi_square_metres",
            ),
            floor_height_centi_metres: __sdk::__query_builder::Col::new(
                table_name,
                "floor_height_centi_metres",
            ),
            rent_price_cents: __sdk::__query_builder::Col::new(table_name, "rent_price_cents"),
            remark: __sdk::__query_builder::Col::new(table_name, "remark"),
            is_deleted: __sdk::__query_builder::Col::new(table_name, "is_deleted"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
        }
    }
}

/// Indexed column accessor struct for the table `DormitoryFloor`.
///
/// Provides typed access to indexed columns for query building.
pub struct DormitoryFloorIxCols {
    pub customer_id: __sdk::__query_builder::IxCol<DormitoryFloor, String>,
    pub dormitory_floor_id: __sdk::__query_builder::IxCol<DormitoryFloor, u64>,
    pub dormitory_id: __sdk::__query_builder::IxCol<DormitoryFloor, u64>,
}

impl __sdk::__query_builder::HasIxCols for DormitoryFloor {
    type IxCols = DormitoryFloorIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        DormitoryFloorIxCols {
            customer_id: __sdk::__query_builder::IxCol::new(table_name, "customer_id"),
            dormitory_floor_id: __sdk::__query_builder::IxCol::new(
                table_name,
                "dormitory_floor_id",
            ),
            dormitory_id: __sdk::__query_builder::IxCol::new(table_name, "dormitory_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for DormitoryFloor {}
