// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct EffectivePermission {
    pub code: String,
    pub source: String,
}

impl __sdk::InModule for EffectivePermission {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `EffectivePermission`.
///
/// Provides typed access to columns for query building.
pub struct EffectivePermissionCols {
    pub code: __sdk::__query_builder::Col<EffectivePermission, String>,
    pub source: __sdk::__query_builder::Col<EffectivePermission, String>,
}

impl __sdk::__query_builder::HasCols for EffectivePermission {
    type Cols = EffectivePermissionCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        EffectivePermissionCols {
            code: __sdk::__query_builder::Col::new(table_name, "code"),
            source: __sdk::__query_builder::Col::new(table_name, "source"),
        }
    }
}
