// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct EleBill {
    pub ele_id: u64,
    pub customer_id: String,
    pub bill_id: u64,
    pub meter_id: u64,
    pub tou_tier: Option<String>,
    pub meter_name: String,
    pub previous_reading_centi: i64,
    pub current_reading_centi: i64,
    pub monthly_usage_centi: i64,
    pub multiplier_centi: i64,
    pub total_usage_centi: i64,
    pub unit_price_scaled: i64,
    pub amount_cents: i64,
    pub remark: Option<String>,
    pub receipt_time: Option<__sdk::Timestamp>,
    pub created_at: __sdk::Timestamp,
    pub updated_at: Option<__sdk::Timestamp>,
}

impl __sdk::InModule for EleBill {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `EleBill`.
///
/// Provides typed access to columns for query building.
pub struct EleBillCols {
    pub ele_id: __sdk::__query_builder::Col<EleBill, u64>,
    pub customer_id: __sdk::__query_builder::Col<EleBill, String>,
    pub bill_id: __sdk::__query_builder::Col<EleBill, u64>,
    pub meter_id: __sdk::__query_builder::Col<EleBill, u64>,
    pub tou_tier: __sdk::__query_builder::Col<EleBill, Option<String>>,
    pub meter_name: __sdk::__query_builder::Col<EleBill, String>,
    pub previous_reading_centi: __sdk::__query_builder::Col<EleBill, i64>,
    pub current_reading_centi: __sdk::__query_builder::Col<EleBill, i64>,
    pub monthly_usage_centi: __sdk::__query_builder::Col<EleBill, i64>,
    pub multiplier_centi: __sdk::__query_builder::Col<EleBill, i64>,
    pub total_usage_centi: __sdk::__query_builder::Col<EleBill, i64>,
    pub unit_price_scaled: __sdk::__query_builder::Col<EleBill, i64>,
    pub amount_cents: __sdk::__query_builder::Col<EleBill, i64>,
    pub remark: __sdk::__query_builder::Col<EleBill, Option<String>>,
    pub receipt_time: __sdk::__query_builder::Col<EleBill, Option<__sdk::Timestamp>>,
    pub created_at: __sdk::__query_builder::Col<EleBill, __sdk::Timestamp>,
    pub updated_at: __sdk::__query_builder::Col<EleBill, Option<__sdk::Timestamp>>,
}

impl __sdk::__query_builder::HasCols for EleBill {
    type Cols = EleBillCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        EleBillCols {
            ele_id: __sdk::__query_builder::Col::new(table_name, "ele_id"),
            customer_id: __sdk::__query_builder::Col::new(table_name, "customer_id"),
            bill_id: __sdk::__query_builder::Col::new(table_name, "bill_id"),
            meter_id: __sdk::__query_builder::Col::new(table_name, "meter_id"),
            tou_tier: __sdk::__query_builder::Col::new(table_name, "tou_tier"),
            meter_name: __sdk::__query_builder::Col::new(table_name, "meter_name"),
            previous_reading_centi: __sdk::__query_builder::Col::new(
                table_name,
                "previous_reading_centi",
            ),
            current_reading_centi: __sdk::__query_builder::Col::new(
                table_name,
                "current_reading_centi",
            ),
            monthly_usage_centi: __sdk::__query_builder::Col::new(
                table_name,
                "monthly_usage_centi",
            ),
            multiplier_centi: __sdk::__query_builder::Col::new(table_name, "multiplier_centi"),
            total_usage_centi: __sdk::__query_builder::Col::new(table_name, "total_usage_centi"),
            unit_price_scaled: __sdk::__query_builder::Col::new(table_name, "unit_price_scaled"),
            amount_cents: __sdk::__query_builder::Col::new(table_name, "amount_cents"),
            remark: __sdk::__query_builder::Col::new(table_name, "remark"),
            receipt_time: __sdk::__query_builder::Col::new(table_name, "receipt_time"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
        }
    }
}

/// Indexed column accessor struct for the table `EleBill`.
///
/// Provides typed access to indexed columns for query building.
pub struct EleBillIxCols {
    pub bill_id: __sdk::__query_builder::IxCol<EleBill, u64>,
    pub customer_id: __sdk::__query_builder::IxCol<EleBill, String>,
    pub ele_id: __sdk::__query_builder::IxCol<EleBill, u64>,
    pub meter_id: __sdk::__query_builder::IxCol<EleBill, u64>,
}

impl __sdk::__query_builder::HasIxCols for EleBill {
    type IxCols = EleBillIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        EleBillIxCols {
            bill_id: __sdk::__query_builder::IxCol::new(table_name, "bill_id"),
            customer_id: __sdk::__query_builder::IxCol::new(table_name, "customer_id"),
            ele_id: __sdk::__query_builder::IxCol::new(table_name, "ele_id"),
            meter_id: __sdk::__query_builder::IxCol::new(table_name, "meter_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for EleBill {}
