// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ElevatorAsset {
    pub asset_id: u64,
    pub customer_id: String,
    pub park_id: u64,
    pub factory_id: u64,
    pub elevator_name: String,
    pub location: String,
    pub size: Option<String>,
    pub load_capacity_centi_kg: u64,
    pub production_date: Option<String>,
    pub remark: Option<String>,
    pub is_deleted: bool,
    pub created_at: __sdk::Timestamp,
    pub updated_at: Option<__sdk::Timestamp>,
}

impl __sdk::InModule for ElevatorAsset {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `ElevatorAsset`.
///
/// Provides typed access to columns for query building.
pub struct ElevatorAssetCols {
    pub asset_id: __sdk::__query_builder::Col<ElevatorAsset, u64>,
    pub customer_id: __sdk::__query_builder::Col<ElevatorAsset, String>,
    pub park_id: __sdk::__query_builder::Col<ElevatorAsset, u64>,
    pub factory_id: __sdk::__query_builder::Col<ElevatorAsset, u64>,
    pub elevator_name: __sdk::__query_builder::Col<ElevatorAsset, String>,
    pub location: __sdk::__query_builder::Col<ElevatorAsset, String>,
    pub size: __sdk::__query_builder::Col<ElevatorAsset, Option<String>>,
    pub load_capacity_centi_kg: __sdk::__query_builder::Col<ElevatorAsset, u64>,
    pub production_date: __sdk::__query_builder::Col<ElevatorAsset, Option<String>>,
    pub remark: __sdk::__query_builder::Col<ElevatorAsset, Option<String>>,
    pub is_deleted: __sdk::__query_builder::Col<ElevatorAsset, bool>,
    pub created_at: __sdk::__query_builder::Col<ElevatorAsset, __sdk::Timestamp>,
    pub updated_at: __sdk::__query_builder::Col<ElevatorAsset, Option<__sdk::Timestamp>>,
}

impl __sdk::__query_builder::HasCols for ElevatorAsset {
    type Cols = ElevatorAssetCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ElevatorAssetCols {
            asset_id: __sdk::__query_builder::Col::new(table_name, "asset_id"),
            customer_id: __sdk::__query_builder::Col::new(table_name, "customer_id"),
            park_id: __sdk::__query_builder::Col::new(table_name, "park_id"),
            factory_id: __sdk::__query_builder::Col::new(table_name, "factory_id"),
            elevator_name: __sdk::__query_builder::Col::new(table_name, "elevator_name"),
            location: __sdk::__query_builder::Col::new(table_name, "location"),
            size: __sdk::__query_builder::Col::new(table_name, "size"),
            load_capacity_centi_kg: __sdk::__query_builder::Col::new(
                table_name,
                "load_capacity_centi_kg",
            ),
            production_date: __sdk::__query_builder::Col::new(table_name, "production_date"),
            remark: __sdk::__query_builder::Col::new(table_name, "remark"),
            is_deleted: __sdk::__query_builder::Col::new(table_name, "is_deleted"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
        }
    }
}

/// Indexed column accessor struct for the table `ElevatorAsset`.
///
/// Provides typed access to indexed columns for query building.
pub struct ElevatorAssetIxCols {
    pub asset_id: __sdk::__query_builder::IxCol<ElevatorAsset, u64>,
    pub customer_id: __sdk::__query_builder::IxCol<ElevatorAsset, String>,
    pub factory_id: __sdk::__query_builder::IxCol<ElevatorAsset, u64>,
    pub park_id: __sdk::__query_builder::IxCol<ElevatorAsset, u64>,
}

impl __sdk::__query_builder::HasIxCols for ElevatorAsset {
    type IxCols = ElevatorAssetIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ElevatorAssetIxCols {
            asset_id: __sdk::__query_builder::IxCol::new(table_name, "asset_id"),
            customer_id: __sdk::__query_builder::IxCol::new(table_name, "customer_id"),
            factory_id: __sdk::__query_builder::IxCol::new(table_name, "factory_id"),
            park_id: __sdk::__query_builder::IxCol::new(table_name, "park_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ElevatorAsset {}
