// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Employee {
    pub employee_id: u64,
    pub customer_id: String,
    pub name: String,
    pub gender: String,
    pub phone: String,
    pub user_id: Option<u64>,
    pub age: Option<i32>,
    pub id_number: Option<String>,
    pub address: Option<String>,
    pub education: Option<String>,
    pub department: Option<String>,
    pub hire_date: Option<__sdk::Timestamp>,
    pub leave_date: Option<__sdk::Timestamp>,
    pub remark: Option<String>,
    pub is_deleted: bool,
    pub is_resigned: bool,
    pub check_in_seconds: Option<u32>,
    pub check_out_seconds: Option<u32>,
    pub created_at: __sdk::Timestamp,
    pub updated_at: Option<__sdk::Timestamp>,
}

impl __sdk::InModule for Employee {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Employee`.
///
/// Provides typed access to columns for query building.
pub struct EmployeeCols {
    pub employee_id: __sdk::__query_builder::Col<Employee, u64>,
    pub customer_id: __sdk::__query_builder::Col<Employee, String>,
    pub name: __sdk::__query_builder::Col<Employee, String>,
    pub gender: __sdk::__query_builder::Col<Employee, String>,
    pub phone: __sdk::__query_builder::Col<Employee, String>,
    pub user_id: __sdk::__query_builder::Col<Employee, Option<u64>>,
    pub age: __sdk::__query_builder::Col<Employee, Option<i32>>,
    pub id_number: __sdk::__query_builder::Col<Employee, Option<String>>,
    pub address: __sdk::__query_builder::Col<Employee, Option<String>>,
    pub education: __sdk::__query_builder::Col<Employee, Option<String>>,
    pub department: __sdk::__query_builder::Col<Employee, Option<String>>,
    pub hire_date: __sdk::__query_builder::Col<Employee, Option<__sdk::Timestamp>>,
    pub leave_date: __sdk::__query_builder::Col<Employee, Option<__sdk::Timestamp>>,
    pub remark: __sdk::__query_builder::Col<Employee, Option<String>>,
    pub is_deleted: __sdk::__query_builder::Col<Employee, bool>,
    pub is_resigned: __sdk::__query_builder::Col<Employee, bool>,
    pub check_in_seconds: __sdk::__query_builder::Col<Employee, Option<u32>>,
    pub check_out_seconds: __sdk::__query_builder::Col<Employee, Option<u32>>,
    pub created_at: __sdk::__query_builder::Col<Employee, __sdk::Timestamp>,
    pub updated_at: __sdk::__query_builder::Col<Employee, Option<__sdk::Timestamp>>,
}

impl __sdk::__query_builder::HasCols for Employee {
    type Cols = EmployeeCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        EmployeeCols {
            employee_id: __sdk::__query_builder::Col::new(table_name, "employee_id"),
            customer_id: __sdk::__query_builder::Col::new(table_name, "customer_id"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            gender: __sdk::__query_builder::Col::new(table_name, "gender"),
            phone: __sdk::__query_builder::Col::new(table_name, "phone"),
            user_id: __sdk::__query_builder::Col::new(table_name, "user_id"),
            age: __sdk::__query_builder::Col::new(table_name, "age"),
            id_number: __sdk::__query_builder::Col::new(table_name, "id_number"),
            address: __sdk::__query_builder::Col::new(table_name, "address"),
            education: __sdk::__query_builder::Col::new(table_name, "education"),
            department: __sdk::__query_builder::Col::new(table_name, "department"),
            hire_date: __sdk::__query_builder::Col::new(table_name, "hire_date"),
            leave_date: __sdk::__query_builder::Col::new(table_name, "leave_date"),
            remark: __sdk::__query_builder::Col::new(table_name, "remark"),
            is_deleted: __sdk::__query_builder::Col::new(table_name, "is_deleted"),
            is_resigned: __sdk::__query_builder::Col::new(table_name, "is_resigned"),
            check_in_seconds: __sdk::__query_builder::Col::new(table_name, "check_in_seconds"),
            check_out_seconds: __sdk::__query_builder::Col::new(table_name, "check_out_seconds"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
        }
    }
}

/// Indexed column accessor struct for the table `Employee`.
///
/// Provides typed access to indexed columns for query building.
pub struct EmployeeIxCols {
    pub customer_id: __sdk::__query_builder::IxCol<Employee, String>,
    pub employee_id: __sdk::__query_builder::IxCol<Employee, u64>,
}

impl __sdk::__query_builder::HasIxCols for Employee {
    type IxCols = EmployeeIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        EmployeeIxCols {
            customer_id: __sdk::__query_builder::IxCol::new(table_name, "customer_id"),
            employee_id: __sdk::__query_builder::IxCol::new(table_name, "employee_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Employee {}
