// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct FactoryFloor {
    pub floor_id: u64,
    pub customer_id: String,
    pub factory_id: u64,
    pub floor_name: String,
    pub floor_height_centi_metres: Option<i64>,
    pub load_bearing_centi_units: Option<i64>,
    pub rent_price_cents: i64,
    pub total_area_centi_square_metres: i64,
    pub description: Option<String>,
    pub is_deleted: bool,
    pub created_at: __sdk::Timestamp,
    pub updated_at: Option<__sdk::Timestamp>,
}

impl __sdk::InModule for FactoryFloor {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `FactoryFloor`.
///
/// Provides typed access to columns for query building.
pub struct FactoryFloorCols {
    pub floor_id: __sdk::__query_builder::Col<FactoryFloor, u64>,
    pub customer_id: __sdk::__query_builder::Col<FactoryFloor, String>,
    pub factory_id: __sdk::__query_builder::Col<FactoryFloor, u64>,
    pub floor_name: __sdk::__query_builder::Col<FactoryFloor, String>,
    pub floor_height_centi_metres: __sdk::__query_builder::Col<FactoryFloor, Option<i64>>,
    pub load_bearing_centi_units: __sdk::__query_builder::Col<FactoryFloor, Option<i64>>,
    pub rent_price_cents: __sdk::__query_builder::Col<FactoryFloor, i64>,
    pub total_area_centi_square_metres: __sdk::__query_builder::Col<FactoryFloor, i64>,
    pub description: __sdk::__query_builder::Col<FactoryFloor, Option<String>>,
    pub is_deleted: __sdk::__query_builder::Col<FactoryFloor, bool>,
    pub created_at: __sdk::__query_builder::Col<FactoryFloor, __sdk::Timestamp>,
    pub updated_at: __sdk::__query_builder::Col<FactoryFloor, Option<__sdk::Timestamp>>,
}

impl __sdk::__query_builder::HasCols for FactoryFloor {
    type Cols = FactoryFloorCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        FactoryFloorCols {
            floor_id: __sdk::__query_builder::Col::new(table_name, "floor_id"),
            customer_id: __sdk::__query_builder::Col::new(table_name, "customer_id"),
            factory_id: __sdk::__query_builder::Col::new(table_name, "factory_id"),
            floor_name: __sdk::__query_builder::Col::new(table_name, "floor_name"),
            floor_height_centi_metres: __sdk::__query_builder::Col::new(
                table_name,
                "floor_height_centi_metres",
            ),
            load_bearing_centi_units: __sdk::__query_builder::Col::new(
                table_name,
                "load_bearing_centi_units",
            ),
            rent_price_cents: __sdk::__query_builder::Col::new(table_name, "rent_price_cents"),
            total_area_centi_square_metres: __sdk::__query_builder::Col::new(
                table_name,
                "total_area_centi_square_metres",
            ),
            description: __sdk::__query_builder::Col::new(table_name, "description"),
            is_deleted: __sdk::__query_builder::Col::new(table_name, "is_deleted"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
        }
    }
}

/// Indexed column accessor struct for the table `FactoryFloor`.
///
/// Provides typed access to indexed columns for query building.
pub struct FactoryFloorIxCols {
    pub customer_id: __sdk::__query_builder::IxCol<FactoryFloor, String>,
    pub factory_id: __sdk::__query_builder::IxCol<FactoryFloor, u64>,
    pub floor_id: __sdk::__query_builder::IxCol<FactoryFloor, u64>,
}

impl __sdk::__query_builder::HasIxCols for FactoryFloor {
    type IxCols = FactoryFloorIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        FactoryFloorIxCols {
            customer_id: __sdk::__query_builder::IxCol::new(table_name, "customer_id"),
            factory_id: __sdk::__query_builder::IxCol::new(table_name, "factory_id"),
            floor_id: __sdk::__query_builder::IxCol::new(table_name, "floor_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for FactoryFloor {}
