// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct FactoryFloorImage {
    pub id: u64,
    pub customer_id: String,
    pub floor_id: u64,
    pub img_id: u64,
    pub created_at: __sdk::Timestamp,
    pub updated_at: Option<__sdk::Timestamp>,
}

impl __sdk::InModule for FactoryFloorImage {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `FactoryFloorImage`.
///
/// Provides typed access to columns for query building.
pub struct FactoryFloorImageCols {
    pub id: __sdk::__query_builder::Col<FactoryFloorImage, u64>,
    pub customer_id: __sdk::__query_builder::Col<FactoryFloorImage, String>,
    pub floor_id: __sdk::__query_builder::Col<FactoryFloorImage, u64>,
    pub img_id: __sdk::__query_builder::Col<FactoryFloorImage, u64>,
    pub created_at: __sdk::__query_builder::Col<FactoryFloorImage, __sdk::Timestamp>,
    pub updated_at: __sdk::__query_builder::Col<FactoryFloorImage, Option<__sdk::Timestamp>>,
}

impl __sdk::__query_builder::HasCols for FactoryFloorImage {
    type Cols = FactoryFloorImageCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        FactoryFloorImageCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            customer_id: __sdk::__query_builder::Col::new(table_name, "customer_id"),
            floor_id: __sdk::__query_builder::Col::new(table_name, "floor_id"),
            img_id: __sdk::__query_builder::Col::new(table_name, "img_id"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
        }
    }
}

/// Indexed column accessor struct for the table `FactoryFloorImage`.
///
/// Provides typed access to indexed columns for query building.
pub struct FactoryFloorImageIxCols {
    pub customer_id: __sdk::__query_builder::IxCol<FactoryFloorImage, String>,
    pub floor_id: __sdk::__query_builder::IxCol<FactoryFloorImage, u64>,
    pub id: __sdk::__query_builder::IxCol<FactoryFloorImage, u64>,
    pub img_id: __sdk::__query_builder::IxCol<FactoryFloorImage, u64>,
}

impl __sdk::__query_builder::HasIxCols for FactoryFloorImage {
    type IxCols = FactoryFloorImageIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        FactoryFloorImageIxCols {
            customer_id: __sdk::__query_builder::IxCol::new(table_name, "customer_id"),
            floor_id: __sdk::__query_builder::IxCol::new(table_name, "floor_id"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            img_id: __sdk::__query_builder::IxCol::new(table_name, "img_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for FactoryFloorImage {}
