// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Feedback {
    pub id: u64,
    pub customer_id: String,
    pub category: String,
    pub content: String,
    pub contact: Option<String>,
    pub client_platform: Option<String>,
    pub source: String,
    pub user_agent: Option<String>,
    pub user_id: u64,
    pub username: String,
    pub real_name: String,
    pub center_user_id: u64,
    pub created_at: __sdk::Timestamp,
    pub updated_at: Option<__sdk::Timestamp>,
}

impl __sdk::InModule for Feedback {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Feedback`.
///
/// Provides typed access to columns for query building.
pub struct FeedbackCols {
    pub id: __sdk::__query_builder::Col<Feedback, u64>,
    pub customer_id: __sdk::__query_builder::Col<Feedback, String>,
    pub category: __sdk::__query_builder::Col<Feedback, String>,
    pub content: __sdk::__query_builder::Col<Feedback, String>,
    pub contact: __sdk::__query_builder::Col<Feedback, Option<String>>,
    pub client_platform: __sdk::__query_builder::Col<Feedback, Option<String>>,
    pub source: __sdk::__query_builder::Col<Feedback, String>,
    pub user_agent: __sdk::__query_builder::Col<Feedback, Option<String>>,
    pub user_id: __sdk::__query_builder::Col<Feedback, u64>,
    pub username: __sdk::__query_builder::Col<Feedback, String>,
    pub real_name: __sdk::__query_builder::Col<Feedback, String>,
    pub center_user_id: __sdk::__query_builder::Col<Feedback, u64>,
    pub created_at: __sdk::__query_builder::Col<Feedback, __sdk::Timestamp>,
    pub updated_at: __sdk::__query_builder::Col<Feedback, Option<__sdk::Timestamp>>,
}

impl __sdk::__query_builder::HasCols for Feedback {
    type Cols = FeedbackCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        FeedbackCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            customer_id: __sdk::__query_builder::Col::new(table_name, "customer_id"),
            category: __sdk::__query_builder::Col::new(table_name, "category"),
            content: __sdk::__query_builder::Col::new(table_name, "content"),
            contact: __sdk::__query_builder::Col::new(table_name, "contact"),
            client_platform: __sdk::__query_builder::Col::new(table_name, "client_platform"),
            source: __sdk::__query_builder::Col::new(table_name, "source"),
            user_agent: __sdk::__query_builder::Col::new(table_name, "user_agent"),
            user_id: __sdk::__query_builder::Col::new(table_name, "user_id"),
            username: __sdk::__query_builder::Col::new(table_name, "username"),
            real_name: __sdk::__query_builder::Col::new(table_name, "real_name"),
            center_user_id: __sdk::__query_builder::Col::new(table_name, "center_user_id"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
        }
    }
}

/// Indexed column accessor struct for the table `Feedback`.
///
/// Provides typed access to indexed columns for query building.
pub struct FeedbackIxCols {
    pub center_user_id: __sdk::__query_builder::IxCol<Feedback, u64>,
    pub customer_id: __sdk::__query_builder::IxCol<Feedback, String>,
    pub id: __sdk::__query_builder::IxCol<Feedback, u64>,
}

impl __sdk::__query_builder::HasIxCols for Feedback {
    type IxCols = FeedbackIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        FeedbackIxCols {
            center_user_id: __sdk::__query_builder::IxCol::new(table_name, "center_user_id"),
            customer_id: __sdk::__query_builder::IxCol::new(table_name, "customer_id"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Feedback {}
