// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct FeedbackInput {
    pub category: String,
    pub content: String,
    pub contact: Option<String>,
    pub client_platform: Option<String>,
    pub user_agent: Option<String>,
    pub image_ids: Vec<u64>,
}

impl __sdk::InModule for FeedbackInput {
    type Module = super::RemoteModule;
}
