// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Firefighting {
    pub firefighting_id: u64,
    pub customer_id: String,
    pub address: Option<String>,
    pub firefighting_name: Option<String>,
    pub extinguisher: String,
    pub hydrant: String,
    pub fire_exit: String,
    pub checker: String,
    pub check_time: __sdk::Timestamp,
    pub remark: Option<String>,
    pub factory_id: Option<u64>,
    pub park_id: u64,
    pub created_at: __sdk::Timestamp,
    pub updated_at: Option<__sdk::Timestamp>,
}

impl __sdk::InModule for Firefighting {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Firefighting`.
///
/// Provides typed access to columns for query building.
pub struct FirefightingCols {
    pub firefighting_id: __sdk::__query_builder::Col<Firefighting, u64>,
    pub customer_id: __sdk::__query_builder::Col<Firefighting, String>,
    pub address: __sdk::__query_builder::Col<Firefighting, Option<String>>,
    pub firefighting_name: __sdk::__query_builder::Col<Firefighting, Option<String>>,
    pub extinguisher: __sdk::__query_builder::Col<Firefighting, String>,
    pub hydrant: __sdk::__query_builder::Col<Firefighting, String>,
    pub fire_exit: __sdk::__query_builder::Col<Firefighting, String>,
    pub checker: __sdk::__query_builder::Col<Firefighting, String>,
    pub check_time: __sdk::__query_builder::Col<Firefighting, __sdk::Timestamp>,
    pub remark: __sdk::__query_builder::Col<Firefighting, Option<String>>,
    pub factory_id: __sdk::__query_builder::Col<Firefighting, Option<u64>>,
    pub park_id: __sdk::__query_builder::Col<Firefighting, u64>,
    pub created_at: __sdk::__query_builder::Col<Firefighting, __sdk::Timestamp>,
    pub updated_at: __sdk::__query_builder::Col<Firefighting, Option<__sdk::Timestamp>>,
}

impl __sdk::__query_builder::HasCols for Firefighting {
    type Cols = FirefightingCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        FirefightingCols {
            firefighting_id: __sdk::__query_builder::Col::new(table_name, "firefighting_id"),
            customer_id: __sdk::__query_builder::Col::new(table_name, "customer_id"),
            address: __sdk::__query_builder::Col::new(table_name, "address"),
            firefighting_name: __sdk::__query_builder::Col::new(table_name, "firefighting_name"),
            extinguisher: __sdk::__query_builder::Col::new(table_name, "extinguisher"),
            hydrant: __sdk::__query_builder::Col::new(table_name, "hydrant"),
            fire_exit: __sdk::__query_builder::Col::new(table_name, "fire_exit"),
            checker: __sdk::__query_builder::Col::new(table_name, "checker"),
            check_time: __sdk::__query_builder::Col::new(table_name, "check_time"),
            remark: __sdk::__query_builder::Col::new(table_name, "remark"),
            factory_id: __sdk::__query_builder::Col::new(table_name, "factory_id"),
            park_id: __sdk::__query_builder::Col::new(table_name, "park_id"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
        }
    }
}

/// Indexed column accessor struct for the table `Firefighting`.
///
/// Provides typed access to indexed columns for query building.
pub struct FirefightingIxCols {
    pub check_time: __sdk::__query_builder::IxCol<Firefighting, __sdk::Timestamp>,
    pub customer_id: __sdk::__query_builder::IxCol<Firefighting, String>,
    pub firefighting_id: __sdk::__query_builder::IxCol<Firefighting, u64>,
    pub park_id: __sdk::__query_builder::IxCol<Firefighting, u64>,
}

impl __sdk::__query_builder::HasIxCols for Firefighting {
    type IxCols = FirefightingIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        FirefightingIxCols {
            check_time: __sdk::__query_builder::IxCol::new(table_name, "check_time"),
            customer_id: __sdk::__query_builder::IxCol::new(table_name, "customer_id"),
            firefighting_id: __sdk::__query_builder::IxCol::new(table_name, "firefighting_id"),
            park_id: __sdk::__query_builder::IxCol::new(table_name, "park_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Firefighting {}
