// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct FirefightingInspectionImagePreview {
    pub inspection_id: u64,
    pub img_id: u64,
    pub img_url: String,
}

impl __sdk::InModule for FirefightingInspectionImagePreview {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `FirefightingInspectionImagePreview`.
///
/// Provides typed access to columns for query building.
pub struct FirefightingInspectionImagePreviewCols {
    pub inspection_id: __sdk::__query_builder::Col<FirefightingInspectionImagePreview, u64>,
    pub img_id: __sdk::__query_builder::Col<FirefightingInspectionImagePreview, u64>,
    pub img_url: __sdk::__query_builder::Col<FirefightingInspectionImagePreview, String>,
}

impl __sdk::__query_builder::HasCols for FirefightingInspectionImagePreview {
    type Cols = FirefightingInspectionImagePreviewCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        FirefightingInspectionImagePreviewCols {
            inspection_id: __sdk::__query_builder::Col::new(table_name, "inspection_id"),
            img_id: __sdk::__query_builder::Col::new(table_name, "img_id"),
            img_url: __sdk::__query_builder::Col::new(table_name, "img_url"),
        }
    }
}
