// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::mysql_billing_batch_import_type::MysqlBillingBatchImport;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ImportMysqlBillingBatchArgs {
    pub batch: MysqlBillingBatchImport,
}

impl From<ImportMysqlBillingBatchArgs> for super::Reducer {
    fn from(args: ImportMysqlBillingBatchArgs) -> Self {
        Self::ImportMysqlBillingBatch { batch: args.batch }
    }
}

impl __sdk::InModule for ImportMysqlBillingBatchArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `import_mysql_billing_batch`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait import_mysql_billing_batch {
    /// Request that the remote module invoke the reducer `import_mysql_billing_batch` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`import_mysql_billing_batch:import_mysql_billing_batch_then`] to run a callback after the reducer completes.
    fn import_mysql_billing_batch(&self, batch: MysqlBillingBatchImport) -> __sdk::Result<()> {
        self.import_mysql_billing_batch_then(batch, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `import_mysql_billing_batch` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn import_mysql_billing_batch_then(
        &self,
        batch: MysqlBillingBatchImport,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl import_mysql_billing_batch for super::RemoteReducers {
    fn import_mysql_billing_batch_then(
        &self,
        batch: MysqlBillingBatchImport,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(ImportMysqlBillingBatchArgs { batch }, callback)
    }
}
