// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Investment {
    pub investment_id: u64,
    pub customer_id: String,
    pub agent_name: Option<String>,
    pub tenant_name: Option<String>,
    pub intent_level: String,
    pub intent_area: Option<i64>,
    pub progress: String,
    pub phone_number: Option<String>,
    pub meeting_time: __sdk::Timestamp,
    pub remark: Option<String>,
    pub park_id: u64,
    pub created_at: __sdk::Timestamp,
    pub updated_at: Option<__sdk::Timestamp>,
}

impl __sdk::InModule for Investment {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Investment`.
///
/// Provides typed access to columns for query building.
pub struct InvestmentCols {
    pub investment_id: __sdk::__query_builder::Col<Investment, u64>,
    pub customer_id: __sdk::__query_builder::Col<Investment, String>,
    pub agent_name: __sdk::__query_builder::Col<Investment, Option<String>>,
    pub tenant_name: __sdk::__query_builder::Col<Investment, Option<String>>,
    pub intent_level: __sdk::__query_builder::Col<Investment, String>,
    pub intent_area: __sdk::__query_builder::Col<Investment, Option<i64>>,
    pub progress: __sdk::__query_builder::Col<Investment, String>,
    pub phone_number: __sdk::__query_builder::Col<Investment, Option<String>>,
    pub meeting_time: __sdk::__query_builder::Col<Investment, __sdk::Timestamp>,
    pub remark: __sdk::__query_builder::Col<Investment, Option<String>>,
    pub park_id: __sdk::__query_builder::Col<Investment, u64>,
    pub created_at: __sdk::__query_builder::Col<Investment, __sdk::Timestamp>,
    pub updated_at: __sdk::__query_builder::Col<Investment, Option<__sdk::Timestamp>>,
}

impl __sdk::__query_builder::HasCols for Investment {
    type Cols = InvestmentCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        InvestmentCols {
            investment_id: __sdk::__query_builder::Col::new(table_name, "investment_id"),
            customer_id: __sdk::__query_builder::Col::new(table_name, "customer_id"),
            agent_name: __sdk::__query_builder::Col::new(table_name, "agent_name"),
            tenant_name: __sdk::__query_builder::Col::new(table_name, "tenant_name"),
            intent_level: __sdk::__query_builder::Col::new(table_name, "intent_level"),
            intent_area: __sdk::__query_builder::Col::new(table_name, "intent_area"),
            progress: __sdk::__query_builder::Col::new(table_name, "progress"),
            phone_number: __sdk::__query_builder::Col::new(table_name, "phone_number"),
            meeting_time: __sdk::__query_builder::Col::new(table_name, "meeting_time"),
            remark: __sdk::__query_builder::Col::new(table_name, "remark"),
            park_id: __sdk::__query_builder::Col::new(table_name, "park_id"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
        }
    }
}

/// Indexed column accessor struct for the table `Investment`.
///
/// Provides typed access to indexed columns for query building.
pub struct InvestmentIxCols {
    pub customer_id: __sdk::__query_builder::IxCol<Investment, String>,
    pub investment_id: __sdk::__query_builder::IxCol<Investment, u64>,
    pub park_id: __sdk::__query_builder::IxCol<Investment, u64>,
    pub phone_number: __sdk::__query_builder::IxCol<Investment, Option<String>>,
}

impl __sdk::__query_builder::HasIxCols for Investment {
    type IxCols = InvestmentIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        InvestmentIxCols {
            customer_id: __sdk::__query_builder::IxCol::new(table_name, "customer_id"),
            investment_id: __sdk::__query_builder::IxCol::new(table_name, "investment_id"),
            park_id: __sdk::__query_builder::IxCol::new(table_name, "park_id"),
            phone_number: __sdk::__query_builder::IxCol::new(table_name, "phone_number"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Investment {}
