// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct InvestmentTenant {
    pub tenant_id: u64,
    pub customer_id: String,
    pub bill_name: String,
    pub bill_category: String,
    pub amount_cents: i64,
    pub transaction_type: String,
    pub transaction_time: __sdk::Timestamp,
    pub created_at: __sdk::Timestamp,
    pub updated_at: Option<__sdk::Timestamp>,
}

impl __sdk::InModule for InvestmentTenant {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `InvestmentTenant`.
///
/// Provides typed access to columns for query building.
pub struct InvestmentTenantCols {
    pub tenant_id: __sdk::__query_builder::Col<InvestmentTenant, u64>,
    pub customer_id: __sdk::__query_builder::Col<InvestmentTenant, String>,
    pub bill_name: __sdk::__query_builder::Col<InvestmentTenant, String>,
    pub bill_category: __sdk::__query_builder::Col<InvestmentTenant, String>,
    pub amount_cents: __sdk::__query_builder::Col<InvestmentTenant, i64>,
    pub transaction_type: __sdk::__query_builder::Col<InvestmentTenant, String>,
    pub transaction_time: __sdk::__query_builder::Col<InvestmentTenant, __sdk::Timestamp>,
    pub created_at: __sdk::__query_builder::Col<InvestmentTenant, __sdk::Timestamp>,
    pub updated_at: __sdk::__query_builder::Col<InvestmentTenant, Option<__sdk::Timestamp>>,
}

impl __sdk::__query_builder::HasCols for InvestmentTenant {
    type Cols = InvestmentTenantCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        InvestmentTenantCols {
            tenant_id: __sdk::__query_builder::Col::new(table_name, "tenant_id"),
            customer_id: __sdk::__query_builder::Col::new(table_name, "customer_id"),
            bill_name: __sdk::__query_builder::Col::new(table_name, "bill_name"),
            bill_category: __sdk::__query_builder::Col::new(table_name, "bill_category"),
            amount_cents: __sdk::__query_builder::Col::new(table_name, "amount_cents"),
            transaction_type: __sdk::__query_builder::Col::new(table_name, "transaction_type"),
            transaction_time: __sdk::__query_builder::Col::new(table_name, "transaction_time"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
        }
    }
}

/// Indexed column accessor struct for the table `InvestmentTenant`.
///
/// Provides typed access to indexed columns for query building.
pub struct InvestmentTenantIxCols {
    pub customer_id: __sdk::__query_builder::IxCol<InvestmentTenant, String>,
    pub tenant_id: __sdk::__query_builder::IxCol<InvestmentTenant, u64>,
    pub transaction_time: __sdk::__query_builder::IxCol<InvestmentTenant, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasIxCols for InvestmentTenant {
    type IxCols = InvestmentTenantIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        InvestmentTenantIxCols {
            customer_id: __sdk::__query_builder::IxCol::new(table_name, "customer_id"),
            tenant_id: __sdk::__query_builder::IxCol::new(table_name, "tenant_id"),
            transaction_time: __sdk::__query_builder::IxCol::new(table_name, "transaction_time"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for InvestmentTenant {}
