// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct InvestmentInput {
    pub agent_name: Option<String>,
    pub tenant_name: Option<String>,
    pub intent_level: String,
    pub intent_area: Option<i64>,
    pub progress: String,
    pub phone_number: Option<String>,
    pub meeting_time: __sdk::Timestamp,
    pub remark: Option<String>,
    pub park_id: Option<u64>,
    pub image_ids: Vec<u64>,
}

impl __sdk::InModule for InvestmentInput {
    type Module = super::RemoteModule;
}
