// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::center_app_version_type::CenterAppVersion;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `latest_center_app_version`.
///
/// Obtain a handle from the [`LatestCenterAppVersionTableAccess::latest_center_app_version`] method on [`super::RemoteTables`],
/// like `ctx.db.latest_center_app_version()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.latest_center_app_version().on_insert(...)`.
pub struct LatestCenterAppVersionTableHandle<'ctx> {
    imp: __sdk::TableHandle<CenterAppVersion>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `latest_center_app_version`.
///
/// Implemented for [`super::RemoteTables`].
pub trait LatestCenterAppVersionTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`LatestCenterAppVersionTableHandle`], which mediates access to the table `latest_center_app_version`.
    fn latest_center_app_version(&self) -> LatestCenterAppVersionTableHandle<'_>;
}

impl LatestCenterAppVersionTableAccess for super::RemoteTables {
    fn latest_center_app_version(&self) -> LatestCenterAppVersionTableHandle<'_> {
        LatestCenterAppVersionTableHandle {
            imp: self
                .imp
                .get_table::<CenterAppVersion>("latest_center_app_version"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct LatestCenterAppVersionInsertCallbackId(__sdk::CallbackId);
pub struct LatestCenterAppVersionDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for LatestCenterAppVersionTableHandle<'ctx> {
    type Row = CenterAppVersion;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = CenterAppVersion> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = LatestCenterAppVersionInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> LatestCenterAppVersionInsertCallbackId {
        LatestCenterAppVersionInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: LatestCenterAppVersionInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = LatestCenterAppVersionDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> LatestCenterAppVersionDeleteCallbackId {
        LatestCenterAppVersionDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: LatestCenterAppVersionDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<CenterAppVersion>("latest_center_app_version");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<CenterAppVersion>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<CenterAppVersion>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `CenterAppVersion`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait latest_center_app_versionQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `CenterAppVersion`.
    fn latest_center_app_version(&self) -> __sdk::__query_builder::Table<CenterAppVersion>;
}

impl latest_center_app_versionQueryTableAccess for __sdk::QueryTableAccessor {
    fn latest_center_app_version(&self) -> __sdk::__query_builder::Table<CenterAppVersion> {
        __sdk::__query_builder::Table::new("latest_center_app_version")
    }
}
