// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct LeadScoreRuleInput {
    pub rule_code: String,
    pub rule_name: String,
    pub event_type: Option<String>,
    pub keywords: Vec<String>,
    pub score_delta: i32,
    pub enabled: bool,
    pub rule_description: Option<String>,
}

impl __sdk::InModule for LeadScoreRuleInput {
    type Module = super::RemoteModule;
}
