// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct LoginWithLegacyAccessTokenArgs {
    pub access_token: String,
    pub remember_me: bool,
}

impl From<LoginWithLegacyAccessTokenArgs> for super::Reducer {
    fn from(args: LoginWithLegacyAccessTokenArgs) -> Self {
        Self::LoginWithLegacyAccessToken {
            access_token: args.access_token,
            remember_me: args.remember_me,
        }
    }
}

impl __sdk::InModule for LoginWithLegacyAccessTokenArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `login_with_legacy_access_token`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait login_with_legacy_access_token {
    /// Request that the remote module invoke the reducer `login_with_legacy_access_token` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`login_with_legacy_access_token:login_with_legacy_access_token_then`] to run a callback after the reducer completes.
    fn login_with_legacy_access_token(
        &self,
        access_token: String,
        remember_me: bool,
    ) -> __sdk::Result<()> {
        self.login_with_legacy_access_token_then(access_token, remember_me, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `login_with_legacy_access_token` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn login_with_legacy_access_token_then(
        &self,
        access_token: String,
        remember_me: bool,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl login_with_legacy_access_token for super::RemoteReducers {
    fn login_with_legacy_access_token_then(
        &self,
        access_token: String,
        remember_me: bool,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            LoginWithLegacyAccessTokenArgs {
                access_token,
                remember_me,
            },
            callback,
        )
    }
}
