// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::role_menu_type::RoleMenu;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `manageable_role_menus`.
///
/// Obtain a handle from the [`ManageableRoleMenusTableAccess::manageable_role_menus`] method on [`super::RemoteTables`],
/// like `ctx.db.manageable_role_menus()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.manageable_role_menus().on_insert(...)`.
pub struct ManageableRoleMenusTableHandle<'ctx> {
    imp: __sdk::TableHandle<RoleMenu>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `manageable_role_menus`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ManageableRoleMenusTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ManageableRoleMenusTableHandle`], which mediates access to the table `manageable_role_menus`.
    fn manageable_role_menus(&self) -> ManageableRoleMenusTableHandle<'_>;
}

impl ManageableRoleMenusTableAccess for super::RemoteTables {
    fn manageable_role_menus(&self) -> ManageableRoleMenusTableHandle<'_> {
        ManageableRoleMenusTableHandle {
            imp: self.imp.get_table::<RoleMenu>("manageable_role_menus"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ManageableRoleMenusInsertCallbackId(__sdk::CallbackId);
pub struct ManageableRoleMenusDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ManageableRoleMenusTableHandle<'ctx> {
    type Row = RoleMenu;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = RoleMenu> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ManageableRoleMenusInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ManageableRoleMenusInsertCallbackId {
        ManageableRoleMenusInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ManageableRoleMenusInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ManageableRoleMenusDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ManageableRoleMenusDeleteCallbackId {
        ManageableRoleMenusDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ManageableRoleMenusDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<RoleMenu>("manageable_role_menus");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<RoleMenu>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<RoleMenu>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `RoleMenu`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait manageable_role_menusQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `RoleMenu`.
    fn manageable_role_menus(&self) -> __sdk::__query_builder::Table<RoleMenu>;
}

impl manageable_role_menusQueryTableAccess for __sdk::QueryTableAccessor {
    fn manageable_role_menus(&self) -> __sdk::__query_builder::Table<RoleMenu> {
        __sdk::__query_builder::Table::new("manageable_role_menus")
    }
}
