// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::park_type::Park;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `manageable_parks`.
///
/// Obtain a handle from the [`ManageableParksTableAccess::manageable_parks`] method on [`super::RemoteTables`],
/// like `ctx.db.manageable_parks()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.manageable_parks().on_insert(...)`.
pub struct ManageableParksTableHandle<'ctx> {
    imp: __sdk::TableHandle<Park>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `manageable_parks`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ManageableParksTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ManageableParksTableHandle`], which mediates access to the table `manageable_parks`.
    fn manageable_parks(&self) -> ManageableParksTableHandle<'_>;
}

impl ManageableParksTableAccess for super::RemoteTables {
    fn manageable_parks(&self) -> ManageableParksTableHandle<'_> {
        ManageableParksTableHandle {
            imp: self.imp.get_table::<Park>("manageable_parks"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ManageableParksInsertCallbackId(__sdk::CallbackId);
pub struct ManageableParksDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ManageableParksTableHandle<'ctx> {
    type Row = Park;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Park> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ManageableParksInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ManageableParksInsertCallbackId {
        ManageableParksInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ManageableParksInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ManageableParksDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ManageableParksDeleteCallbackId {
        ManageableParksDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ManageableParksDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Park>("manageable_parks");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Park>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Park>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Park`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait manageable_parksQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Park`.
    fn manageable_parks(&self) -> __sdk::__query_builder::Table<Park>;
}

impl manageable_parksQueryTableAccess for __sdk::QueryTableAccessor {
    fn manageable_parks(&self) -> __sdk::__query_builder::Table<Park> {
        __sdk::__query_builder::Table::new("manageable_parks")
    }
}
