// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct MapOrganizationToTenantArgs {
    pub organization_id: u64,
    pub target_customer_id: String,
}

impl From<MapOrganizationToTenantArgs> for super::Reducer {
    fn from(args: MapOrganizationToTenantArgs) -> Self {
        Self::MapOrganizationToTenant {
            organization_id: args.organization_id,
            target_customer_id: args.target_customer_id,
        }
    }
}

impl __sdk::InModule for MapOrganizationToTenantArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `map_organization_to_tenant`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait map_organization_to_tenant {
    /// Request that the remote module invoke the reducer `map_organization_to_tenant` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`map_organization_to_tenant:map_organization_to_tenant_then`] to run a callback after the reducer completes.
    fn map_organization_to_tenant(
        &self,
        organization_id: u64,
        target_customer_id: String,
    ) -> __sdk::Result<()> {
        self.map_organization_to_tenant_then(organization_id, target_customer_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `map_organization_to_tenant` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn map_organization_to_tenant_then(
        &self,
        organization_id: u64,
        target_customer_id: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl map_organization_to_tenant for super::RemoteReducers {
    fn map_organization_to_tenant_then(
        &self,
        organization_id: u64,
        target_customer_id: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            MapOrganizationToTenantArgs {
                organization_id,
                target_customer_id,
            },
            callback,
        )
    }
}
