// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::amount_bill_type::AmountBill;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `my_amount_bills`.
///
/// Obtain a handle from the [`MyAmountBillsTableAccess::my_amount_bills`] method on [`super::RemoteTables`],
/// like `ctx.db.my_amount_bills()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.my_amount_bills().on_insert(...)`.
pub struct MyAmountBillsTableHandle<'ctx> {
    imp: __sdk::TableHandle<AmountBill>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `my_amount_bills`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MyAmountBillsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MyAmountBillsTableHandle`], which mediates access to the table `my_amount_bills`.
    fn my_amount_bills(&self) -> MyAmountBillsTableHandle<'_>;
}

impl MyAmountBillsTableAccess for super::RemoteTables {
    fn my_amount_bills(&self) -> MyAmountBillsTableHandle<'_> {
        MyAmountBillsTableHandle {
            imp: self.imp.get_table::<AmountBill>("my_amount_bills"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MyAmountBillsInsertCallbackId(__sdk::CallbackId);
pub struct MyAmountBillsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for MyAmountBillsTableHandle<'ctx> {
    type Row = AmountBill;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = AmountBill> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MyAmountBillsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyAmountBillsInsertCallbackId {
        MyAmountBillsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyAmountBillsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MyAmountBillsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyAmountBillsDeleteCallbackId {
        MyAmountBillsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyAmountBillsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<AmountBill>("my_amount_bills");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<AmountBill>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<AmountBill>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `AmountBill`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait my_amount_billsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `AmountBill`.
    fn my_amount_bills(&self) -> __sdk::__query_builder::Table<AmountBill>;
}

impl my_amount_billsQueryTableAccess for __sdk::QueryTableAccessor {
    fn my_amount_bills(&self) -> __sdk::__query_builder::Table<AmountBill> {
        __sdk::__query_builder::Table::new("my_amount_bills")
    }
}
