// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::attendance_device_binding_type::AttendanceDeviceBinding;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `my_attendance_device_bindings`.
///
/// Obtain a handle from the [`MyAttendanceDeviceBindingsTableAccess::my_attendance_device_bindings`] method on [`super::RemoteTables`],
/// like `ctx.db.my_attendance_device_bindings()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.my_attendance_device_bindings().on_insert(...)`.
pub struct MyAttendanceDeviceBindingsTableHandle<'ctx> {
    imp: __sdk::TableHandle<AttendanceDeviceBinding>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `my_attendance_device_bindings`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MyAttendanceDeviceBindingsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MyAttendanceDeviceBindingsTableHandle`], which mediates access to the table `my_attendance_device_bindings`.
    fn my_attendance_device_bindings(&self) -> MyAttendanceDeviceBindingsTableHandle<'_>;
}

impl MyAttendanceDeviceBindingsTableAccess for super::RemoteTables {
    fn my_attendance_device_bindings(&self) -> MyAttendanceDeviceBindingsTableHandle<'_> {
        MyAttendanceDeviceBindingsTableHandle {
            imp: self
                .imp
                .get_table::<AttendanceDeviceBinding>("my_attendance_device_bindings"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MyAttendanceDeviceBindingsInsertCallbackId(__sdk::CallbackId);
pub struct MyAttendanceDeviceBindingsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for MyAttendanceDeviceBindingsTableHandle<'ctx> {
    type Row = AttendanceDeviceBinding;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = AttendanceDeviceBinding> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MyAttendanceDeviceBindingsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyAttendanceDeviceBindingsInsertCallbackId {
        MyAttendanceDeviceBindingsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyAttendanceDeviceBindingsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MyAttendanceDeviceBindingsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyAttendanceDeviceBindingsDeleteCallbackId {
        MyAttendanceDeviceBindingsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyAttendanceDeviceBindingsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table =
        client_cache.get_or_make_table::<AttendanceDeviceBinding>("my_attendance_device_bindings");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<AttendanceDeviceBinding>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<AttendanceDeviceBinding>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `AttendanceDeviceBinding`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait my_attendance_device_bindingsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `AttendanceDeviceBinding`.
    fn my_attendance_device_bindings(
        &self,
    ) -> __sdk::__query_builder::Table<AttendanceDeviceBinding>;
}

impl my_attendance_device_bindingsQueryTableAccess for __sdk::QueryTableAccessor {
    fn my_attendance_device_bindings(
        &self,
    ) -> __sdk::__query_builder::Table<AttendanceDeviceBinding> {
        __sdk::__query_builder::Table::new("my_attendance_device_bindings")
    }
}
