// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::attendance_type::Attendance;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `my_attendances`.
///
/// Obtain a handle from the [`MyAttendancesTableAccess::my_attendances`] method on [`super::RemoteTables`],
/// like `ctx.db.my_attendances()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.my_attendances().on_insert(...)`.
pub struct MyAttendancesTableHandle<'ctx> {
    imp: __sdk::TableHandle<Attendance>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `my_attendances`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MyAttendancesTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MyAttendancesTableHandle`], which mediates access to the table `my_attendances`.
    fn my_attendances(&self) -> MyAttendancesTableHandle<'_>;
}

impl MyAttendancesTableAccess for super::RemoteTables {
    fn my_attendances(&self) -> MyAttendancesTableHandle<'_> {
        MyAttendancesTableHandle {
            imp: self.imp.get_table::<Attendance>("my_attendances"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MyAttendancesInsertCallbackId(__sdk::CallbackId);
pub struct MyAttendancesDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for MyAttendancesTableHandle<'ctx> {
    type Row = Attendance;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Attendance> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MyAttendancesInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyAttendancesInsertCallbackId {
        MyAttendancesInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyAttendancesInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MyAttendancesDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyAttendancesDeleteCallbackId {
        MyAttendancesDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyAttendancesDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Attendance>("my_attendances");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Attendance>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Attendance>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Attendance`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait my_attendancesQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Attendance`.
    fn my_attendances(&self) -> __sdk::__query_builder::Table<Attendance>;
}

impl my_attendancesQueryTableAccess for __sdk::QueryTableAccessor {
    fn my_attendances(&self) -> __sdk::__query_builder::Table<Attendance> {
        __sdk::__query_builder::Table::new("my_attendances")
    }
}
