// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::carryover_batch_type::CarryoverBatch;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `my_carryover_batches`.
///
/// Obtain a handle from the [`MyCarryoverBatchesTableAccess::my_carryover_batches`] method on [`super::RemoteTables`],
/// like `ctx.db.my_carryover_batches()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.my_carryover_batches().on_insert(...)`.
pub struct MyCarryoverBatchesTableHandle<'ctx> {
    imp: __sdk::TableHandle<CarryoverBatch>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `my_carryover_batches`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MyCarryoverBatchesTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MyCarryoverBatchesTableHandle`], which mediates access to the table `my_carryover_batches`.
    fn my_carryover_batches(&self) -> MyCarryoverBatchesTableHandle<'_>;
}

impl MyCarryoverBatchesTableAccess for super::RemoteTables {
    fn my_carryover_batches(&self) -> MyCarryoverBatchesTableHandle<'_> {
        MyCarryoverBatchesTableHandle {
            imp: self.imp.get_table::<CarryoverBatch>("my_carryover_batches"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MyCarryoverBatchesInsertCallbackId(__sdk::CallbackId);
pub struct MyCarryoverBatchesDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for MyCarryoverBatchesTableHandle<'ctx> {
    type Row = CarryoverBatch;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = CarryoverBatch> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MyCarryoverBatchesInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyCarryoverBatchesInsertCallbackId {
        MyCarryoverBatchesInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyCarryoverBatchesInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MyCarryoverBatchesDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyCarryoverBatchesDeleteCallbackId {
        MyCarryoverBatchesDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyCarryoverBatchesDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<CarryoverBatch>("my_carryover_batches");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<CarryoverBatch>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<CarryoverBatch>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `CarryoverBatch`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait my_carryover_batchesQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `CarryoverBatch`.
    fn my_carryover_batches(&self) -> __sdk::__query_builder::Table<CarryoverBatch>;
}

impl my_carryover_batchesQueryTableAccess for __sdk::QueryTableAccessor {
    fn my_carryover_batches(&self) -> __sdk::__query_builder::Table<CarryoverBatch> {
        __sdk::__query_builder::Table::new("my_carryover_batches")
    }
}
