// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::dormitory_image_preview_type::DormitoryImagePreview;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `my_dormitory_image_previews`.
///
/// Obtain a handle from the [`MyDormitoryImagePreviewsTableAccess::my_dormitory_image_previews`] method on [`super::RemoteTables`],
/// like `ctx.db.my_dormitory_image_previews()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.my_dormitory_image_previews().on_insert(...)`.
pub struct MyDormitoryImagePreviewsTableHandle<'ctx> {
    imp: __sdk::TableHandle<DormitoryImagePreview>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `my_dormitory_image_previews`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MyDormitoryImagePreviewsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MyDormitoryImagePreviewsTableHandle`], which mediates access to the table `my_dormitory_image_previews`.
    fn my_dormitory_image_previews(&self) -> MyDormitoryImagePreviewsTableHandle<'_>;
}

impl MyDormitoryImagePreviewsTableAccess for super::RemoteTables {
    fn my_dormitory_image_previews(&self) -> MyDormitoryImagePreviewsTableHandle<'_> {
        MyDormitoryImagePreviewsTableHandle {
            imp: self
                .imp
                .get_table::<DormitoryImagePreview>("my_dormitory_image_previews"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MyDormitoryImagePreviewsInsertCallbackId(__sdk::CallbackId);
pub struct MyDormitoryImagePreviewsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for MyDormitoryImagePreviewsTableHandle<'ctx> {
    type Row = DormitoryImagePreview;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = DormitoryImagePreview> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MyDormitoryImagePreviewsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyDormitoryImagePreviewsInsertCallbackId {
        MyDormitoryImagePreviewsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyDormitoryImagePreviewsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MyDormitoryImagePreviewsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyDormitoryImagePreviewsDeleteCallbackId {
        MyDormitoryImagePreviewsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyDormitoryImagePreviewsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table =
        client_cache.get_or_make_table::<DormitoryImagePreview>("my_dormitory_image_previews");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<DormitoryImagePreview>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<DormitoryImagePreview>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `DormitoryImagePreview`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait my_dormitory_image_previewsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `DormitoryImagePreview`.
    fn my_dormitory_image_previews(&self) -> __sdk::__query_builder::Table<DormitoryImagePreview>;
}

impl my_dormitory_image_previewsQueryTableAccess for __sdk::QueryTableAccessor {
    fn my_dormitory_image_previews(&self) -> __sdk::__query_builder::Table<DormitoryImagePreview> {
        __sdk::__query_builder::Table::new("my_dormitory_image_previews")
    }
}
