// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::device_asset_type::DeviceAsset;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `my_device_assets`.
///
/// Obtain a handle from the [`MyDeviceAssetsTableAccess::my_device_assets`] method on [`super::RemoteTables`],
/// like `ctx.db.my_device_assets()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.my_device_assets().on_insert(...)`.
pub struct MyDeviceAssetsTableHandle<'ctx> {
    imp: __sdk::TableHandle<DeviceAsset>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `my_device_assets`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MyDeviceAssetsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MyDeviceAssetsTableHandle`], which mediates access to the table `my_device_assets`.
    fn my_device_assets(&self) -> MyDeviceAssetsTableHandle<'_>;
}

impl MyDeviceAssetsTableAccess for super::RemoteTables {
    fn my_device_assets(&self) -> MyDeviceAssetsTableHandle<'_> {
        MyDeviceAssetsTableHandle {
            imp: self.imp.get_table::<DeviceAsset>("my_device_assets"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MyDeviceAssetsInsertCallbackId(__sdk::CallbackId);
pub struct MyDeviceAssetsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for MyDeviceAssetsTableHandle<'ctx> {
    type Row = DeviceAsset;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = DeviceAsset> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MyDeviceAssetsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyDeviceAssetsInsertCallbackId {
        MyDeviceAssetsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyDeviceAssetsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MyDeviceAssetsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyDeviceAssetsDeleteCallbackId {
        MyDeviceAssetsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyDeviceAssetsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<DeviceAsset>("my_device_assets");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<DeviceAsset>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<DeviceAsset>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `DeviceAsset`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait my_device_assetsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `DeviceAsset`.
    fn my_device_assets(&self) -> __sdk::__query_builder::Table<DeviceAsset>;
}

impl my_device_assetsQueryTableAccess for __sdk::QueryTableAccessor {
    fn my_device_assets(&self) -> __sdk::__query_builder::Table<DeviceAsset> {
        __sdk::__query_builder::Table::new("my_device_assets")
    }
}
