// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::device_asset_image_preview_type::DeviceAssetImagePreview;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `my_device_asset_image_previews`.
///
/// Obtain a handle from the [`MyDeviceAssetImagePreviewsTableAccess::my_device_asset_image_previews`] method on [`super::RemoteTables`],
/// like `ctx.db.my_device_asset_image_previews()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.my_device_asset_image_previews().on_insert(...)`.
pub struct MyDeviceAssetImagePreviewsTableHandle<'ctx> {
    imp: __sdk::TableHandle<DeviceAssetImagePreview>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `my_device_asset_image_previews`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MyDeviceAssetImagePreviewsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MyDeviceAssetImagePreviewsTableHandle`], which mediates access to the table `my_device_asset_image_previews`.
    fn my_device_asset_image_previews(&self) -> MyDeviceAssetImagePreviewsTableHandle<'_>;
}

impl MyDeviceAssetImagePreviewsTableAccess for super::RemoteTables {
    fn my_device_asset_image_previews(&self) -> MyDeviceAssetImagePreviewsTableHandle<'_> {
        MyDeviceAssetImagePreviewsTableHandle {
            imp: self
                .imp
                .get_table::<DeviceAssetImagePreview>("my_device_asset_image_previews"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MyDeviceAssetImagePreviewsInsertCallbackId(__sdk::CallbackId);
pub struct MyDeviceAssetImagePreviewsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for MyDeviceAssetImagePreviewsTableHandle<'ctx> {
    type Row = DeviceAssetImagePreview;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = DeviceAssetImagePreview> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MyDeviceAssetImagePreviewsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyDeviceAssetImagePreviewsInsertCallbackId {
        MyDeviceAssetImagePreviewsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyDeviceAssetImagePreviewsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MyDeviceAssetImagePreviewsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyDeviceAssetImagePreviewsDeleteCallbackId {
        MyDeviceAssetImagePreviewsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyDeviceAssetImagePreviewsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table =
        client_cache.get_or_make_table::<DeviceAssetImagePreview>("my_device_asset_image_previews");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<DeviceAssetImagePreview>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<DeviceAssetImagePreview>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `DeviceAssetImagePreview`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait my_device_asset_image_previewsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `DeviceAssetImagePreview`.
    fn my_device_asset_image_previews(
        &self,
    ) -> __sdk::__query_builder::Table<DeviceAssetImagePreview>;
}

impl my_device_asset_image_previewsQueryTableAccess for __sdk::QueryTableAccessor {
    fn my_device_asset_image_previews(
        &self,
    ) -> __sdk::__query_builder::Table<DeviceAssetImagePreview> {
        __sdk::__query_builder::Table::new("my_device_asset_image_previews")
    }
}
