// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::employee_type::Employee;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `my_employees`.
///
/// Obtain a handle from the [`MyEmployeesTableAccess::my_employees`] method on [`super::RemoteTables`],
/// like `ctx.db.my_employees()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.my_employees().on_insert(...)`.
pub struct MyEmployeesTableHandle<'ctx> {
    imp: __sdk::TableHandle<Employee>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `my_employees`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MyEmployeesTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MyEmployeesTableHandle`], which mediates access to the table `my_employees`.
    fn my_employees(&self) -> MyEmployeesTableHandle<'_>;
}

impl MyEmployeesTableAccess for super::RemoteTables {
    fn my_employees(&self) -> MyEmployeesTableHandle<'_> {
        MyEmployeesTableHandle {
            imp: self.imp.get_table::<Employee>("my_employees"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MyEmployeesInsertCallbackId(__sdk::CallbackId);
pub struct MyEmployeesDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for MyEmployeesTableHandle<'ctx> {
    type Row = Employee;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Employee> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MyEmployeesInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyEmployeesInsertCallbackId {
        MyEmployeesInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyEmployeesInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MyEmployeesDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyEmployeesDeleteCallbackId {
        MyEmployeesDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyEmployeesDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Employee>("my_employees");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Employee>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Employee>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Employee`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait my_employeesQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Employee`.
    fn my_employees(&self) -> __sdk::__query_builder::Table<Employee>;
}

impl my_employeesQueryTableAccess for __sdk::QueryTableAccessor {
    fn my_employees(&self) -> __sdk::__query_builder::Table<Employee> {
        __sdk::__query_builder::Table::new("my_employees")
    }
}
