// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::firefighting_asset_type::FirefightingAsset;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `my_firefighting_assets`.
///
/// Obtain a handle from the [`MyFirefightingAssetsTableAccess::my_firefighting_assets`] method on [`super::RemoteTables`],
/// like `ctx.db.my_firefighting_assets()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.my_firefighting_assets().on_insert(...)`.
pub struct MyFirefightingAssetsTableHandle<'ctx> {
    imp: __sdk::TableHandle<FirefightingAsset>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `my_firefighting_assets`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MyFirefightingAssetsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MyFirefightingAssetsTableHandle`], which mediates access to the table `my_firefighting_assets`.
    fn my_firefighting_assets(&self) -> MyFirefightingAssetsTableHandle<'_>;
}

impl MyFirefightingAssetsTableAccess for super::RemoteTables {
    fn my_firefighting_assets(&self) -> MyFirefightingAssetsTableHandle<'_> {
        MyFirefightingAssetsTableHandle {
            imp: self
                .imp
                .get_table::<FirefightingAsset>("my_firefighting_assets"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MyFirefightingAssetsInsertCallbackId(__sdk::CallbackId);
pub struct MyFirefightingAssetsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for MyFirefightingAssetsTableHandle<'ctx> {
    type Row = FirefightingAsset;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = FirefightingAsset> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MyFirefightingAssetsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyFirefightingAssetsInsertCallbackId {
        MyFirefightingAssetsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyFirefightingAssetsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MyFirefightingAssetsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyFirefightingAssetsDeleteCallbackId {
        MyFirefightingAssetsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyFirefightingAssetsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<FirefightingAsset>("my_firefighting_assets");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<FirefightingAsset>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<FirefightingAsset>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `FirefightingAsset`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait my_firefighting_assetsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `FirefightingAsset`.
    fn my_firefighting_assets(&self) -> __sdk::__query_builder::Table<FirefightingAsset>;
}

impl my_firefighting_assetsQueryTableAccess for __sdk::QueryTableAccessor {
    fn my_firefighting_assets(&self) -> __sdk::__query_builder::Table<FirefightingAsset> {
        __sdk::__query_builder::Table::new("my_firefighting_assets")
    }
}
