// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::factory_type::Factory;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `my_factories`.
///
/// Obtain a handle from the [`MyFactoriesTableAccess::my_factories`] method on [`super::RemoteTables`],
/// like `ctx.db.my_factories()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.my_factories().on_insert(...)`.
pub struct MyFactoriesTableHandle<'ctx> {
    imp: __sdk::TableHandle<Factory>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `my_factories`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MyFactoriesTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MyFactoriesTableHandle`], which mediates access to the table `my_factories`.
    fn my_factories(&self) -> MyFactoriesTableHandle<'_>;
}

impl MyFactoriesTableAccess for super::RemoteTables {
    fn my_factories(&self) -> MyFactoriesTableHandle<'_> {
        MyFactoriesTableHandle {
            imp: self.imp.get_table::<Factory>("my_factories"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MyFactoriesInsertCallbackId(__sdk::CallbackId);
pub struct MyFactoriesDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for MyFactoriesTableHandle<'ctx> {
    type Row = Factory;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Factory> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MyFactoriesInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyFactoriesInsertCallbackId {
        MyFactoriesInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyFactoriesInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MyFactoriesDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyFactoriesDeleteCallbackId {
        MyFactoriesDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyFactoriesDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Factory>("my_factories");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Factory>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Factory>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Factory`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait my_factoriesQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Factory`.
    fn my_factories(&self) -> __sdk::__query_builder::Table<Factory>;
}

impl my_factoriesQueryTableAccess for __sdk::QueryTableAccessor {
    fn my_factories(&self) -> __sdk::__query_builder::Table<Factory> {
        __sdk::__query_builder::Table::new("my_factories")
    }
}
