// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::factory_maintenance_type::FactoryMaintenance;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `my_factory_maintenance_records`.
///
/// Obtain a handle from the [`MyFactoryMaintenanceRecordsTableAccess::my_factory_maintenance_records`] method on [`super::RemoteTables`],
/// like `ctx.db.my_factory_maintenance_records()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.my_factory_maintenance_records().on_insert(...)`.
pub struct MyFactoryMaintenanceRecordsTableHandle<'ctx> {
    imp: __sdk::TableHandle<FactoryMaintenance>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `my_factory_maintenance_records`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MyFactoryMaintenanceRecordsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MyFactoryMaintenanceRecordsTableHandle`], which mediates access to the table `my_factory_maintenance_records`.
    fn my_factory_maintenance_records(&self) -> MyFactoryMaintenanceRecordsTableHandle<'_>;
}

impl MyFactoryMaintenanceRecordsTableAccess for super::RemoteTables {
    fn my_factory_maintenance_records(&self) -> MyFactoryMaintenanceRecordsTableHandle<'_> {
        MyFactoryMaintenanceRecordsTableHandle {
            imp: self
                .imp
                .get_table::<FactoryMaintenance>("my_factory_maintenance_records"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MyFactoryMaintenanceRecordsInsertCallbackId(__sdk::CallbackId);
pub struct MyFactoryMaintenanceRecordsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for MyFactoryMaintenanceRecordsTableHandle<'ctx> {
    type Row = FactoryMaintenance;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = FactoryMaintenance> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MyFactoryMaintenanceRecordsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyFactoryMaintenanceRecordsInsertCallbackId {
        MyFactoryMaintenanceRecordsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyFactoryMaintenanceRecordsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MyFactoryMaintenanceRecordsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyFactoryMaintenanceRecordsDeleteCallbackId {
        MyFactoryMaintenanceRecordsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyFactoryMaintenanceRecordsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table =
        client_cache.get_or_make_table::<FactoryMaintenance>("my_factory_maintenance_records");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<FactoryMaintenance>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<FactoryMaintenance>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `FactoryMaintenance`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait my_factory_maintenance_recordsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `FactoryMaintenance`.
    fn my_factory_maintenance_records(&self) -> __sdk::__query_builder::Table<FactoryMaintenance>;
}

impl my_factory_maintenance_recordsQueryTableAccess for __sdk::QueryTableAccessor {
    fn my_factory_maintenance_records(&self) -> __sdk::__query_builder::Table<FactoryMaintenance> {
        __sdk::__query_builder::Table::new("my_factory_maintenance_records")
    }
}
