// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::investment_tenant_type::InvestmentTenant;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `my_investment_tenants`.
///
/// Obtain a handle from the [`MyInvestmentTenantsTableAccess::my_investment_tenants`] method on [`super::RemoteTables`],
/// like `ctx.db.my_investment_tenants()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.my_investment_tenants().on_insert(...)`.
pub struct MyInvestmentTenantsTableHandle<'ctx> {
    imp: __sdk::TableHandle<InvestmentTenant>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `my_investment_tenants`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MyInvestmentTenantsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MyInvestmentTenantsTableHandle`], which mediates access to the table `my_investment_tenants`.
    fn my_investment_tenants(&self) -> MyInvestmentTenantsTableHandle<'_>;
}

impl MyInvestmentTenantsTableAccess for super::RemoteTables {
    fn my_investment_tenants(&self) -> MyInvestmentTenantsTableHandle<'_> {
        MyInvestmentTenantsTableHandle {
            imp: self
                .imp
                .get_table::<InvestmentTenant>("my_investment_tenants"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MyInvestmentTenantsInsertCallbackId(__sdk::CallbackId);
pub struct MyInvestmentTenantsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for MyInvestmentTenantsTableHandle<'ctx> {
    type Row = InvestmentTenant;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = InvestmentTenant> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MyInvestmentTenantsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyInvestmentTenantsInsertCallbackId {
        MyInvestmentTenantsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyInvestmentTenantsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MyInvestmentTenantsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyInvestmentTenantsDeleteCallbackId {
        MyInvestmentTenantsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyInvestmentTenantsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<InvestmentTenant>("my_investment_tenants");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<InvestmentTenant>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<InvestmentTenant>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `InvestmentTenant`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait my_investment_tenantsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `InvestmentTenant`.
    fn my_investment_tenants(&self) -> __sdk::__query_builder::Table<InvestmentTenant>;
}

impl my_investment_tenantsQueryTableAccess for __sdk::QueryTableAccessor {
    fn my_investment_tenants(&self) -> __sdk::__query_builder::Table<InvestmentTenant> {
        __sdk::__query_builder::Table::new("my_investment_tenants")
    }
}
