// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::lead_score_rule_type::LeadScoreRule;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `my_lead_score_rules`.
///
/// Obtain a handle from the [`MyLeadScoreRulesTableAccess::my_lead_score_rules`] method on [`super::RemoteTables`],
/// like `ctx.db.my_lead_score_rules()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.my_lead_score_rules().on_insert(...)`.
pub struct MyLeadScoreRulesTableHandle<'ctx> {
    imp: __sdk::TableHandle<LeadScoreRule>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `my_lead_score_rules`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MyLeadScoreRulesTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MyLeadScoreRulesTableHandle`], which mediates access to the table `my_lead_score_rules`.
    fn my_lead_score_rules(&self) -> MyLeadScoreRulesTableHandle<'_>;
}

impl MyLeadScoreRulesTableAccess for super::RemoteTables {
    fn my_lead_score_rules(&self) -> MyLeadScoreRulesTableHandle<'_> {
        MyLeadScoreRulesTableHandle {
            imp: self.imp.get_table::<LeadScoreRule>("my_lead_score_rules"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MyLeadScoreRulesInsertCallbackId(__sdk::CallbackId);
pub struct MyLeadScoreRulesDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for MyLeadScoreRulesTableHandle<'ctx> {
    type Row = LeadScoreRule;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = LeadScoreRule> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MyLeadScoreRulesInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyLeadScoreRulesInsertCallbackId {
        MyLeadScoreRulesInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyLeadScoreRulesInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MyLeadScoreRulesDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyLeadScoreRulesDeleteCallbackId {
        MyLeadScoreRulesDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyLeadScoreRulesDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<LeadScoreRule>("my_lead_score_rules");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<LeadScoreRule>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<LeadScoreRule>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `LeadScoreRule`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait my_lead_score_rulesQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `LeadScoreRule`.
    fn my_lead_score_rules(&self) -> __sdk::__query_builder::Table<LeadScoreRule>;
}

impl my_lead_score_rulesQueryTableAccess for __sdk::QueryTableAccessor {
    fn my_lead_score_rules(&self) -> __sdk::__query_builder::Table<LeadScoreRule> {
        __sdk::__query_builder::Table::new("my_lead_score_rules")
    }
}
