// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::menu_template_sync_job_type::MenuTemplateSyncJob;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `my_menu_template_sync_jobs`.
///
/// Obtain a handle from the [`MyMenuTemplateSyncJobsTableAccess::my_menu_template_sync_jobs`] method on [`super::RemoteTables`],
/// like `ctx.db.my_menu_template_sync_jobs()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.my_menu_template_sync_jobs().on_insert(...)`.
pub struct MyMenuTemplateSyncJobsTableHandle<'ctx> {
    imp: __sdk::TableHandle<MenuTemplateSyncJob>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `my_menu_template_sync_jobs`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MyMenuTemplateSyncJobsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MyMenuTemplateSyncJobsTableHandle`], which mediates access to the table `my_menu_template_sync_jobs`.
    fn my_menu_template_sync_jobs(&self) -> MyMenuTemplateSyncJobsTableHandle<'_>;
}

impl MyMenuTemplateSyncJobsTableAccess for super::RemoteTables {
    fn my_menu_template_sync_jobs(&self) -> MyMenuTemplateSyncJobsTableHandle<'_> {
        MyMenuTemplateSyncJobsTableHandle {
            imp: self
                .imp
                .get_table::<MenuTemplateSyncJob>("my_menu_template_sync_jobs"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MyMenuTemplateSyncJobsInsertCallbackId(__sdk::CallbackId);
pub struct MyMenuTemplateSyncJobsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for MyMenuTemplateSyncJobsTableHandle<'ctx> {
    type Row = MenuTemplateSyncJob;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = MenuTemplateSyncJob> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MyMenuTemplateSyncJobsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyMenuTemplateSyncJobsInsertCallbackId {
        MyMenuTemplateSyncJobsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyMenuTemplateSyncJobsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MyMenuTemplateSyncJobsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyMenuTemplateSyncJobsDeleteCallbackId {
        MyMenuTemplateSyncJobsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyMenuTemplateSyncJobsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table =
        client_cache.get_or_make_table::<MenuTemplateSyncJob>("my_menu_template_sync_jobs");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<MenuTemplateSyncJob>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<MenuTemplateSyncJob>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `MenuTemplateSyncJob`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait my_menu_template_sync_jobsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `MenuTemplateSyncJob`.
    fn my_menu_template_sync_jobs(&self) -> __sdk::__query_builder::Table<MenuTemplateSyncJob>;
}

impl my_menu_template_sync_jobsQueryTableAccess for __sdk::QueryTableAccessor {
    fn my_menu_template_sync_jobs(&self) -> __sdk::__query_builder::Table<MenuTemplateSyncJob> {
        __sdk::__query_builder::Table::new("my_menu_template_sync_jobs")
    }
}
