// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::organization_type::Organization;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `my_organizations`.
///
/// Obtain a handle from the [`MyOrganizationsTableAccess::my_organizations`] method on [`super::RemoteTables`],
/// like `ctx.db.my_organizations()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.my_organizations().on_insert(...)`.
pub struct MyOrganizationsTableHandle<'ctx> {
    imp: __sdk::TableHandle<Organization>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `my_organizations`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MyOrganizationsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MyOrganizationsTableHandle`], which mediates access to the table `my_organizations`.
    fn my_organizations(&self) -> MyOrganizationsTableHandle<'_>;
}

impl MyOrganizationsTableAccess for super::RemoteTables {
    fn my_organizations(&self) -> MyOrganizationsTableHandle<'_> {
        MyOrganizationsTableHandle {
            imp: self.imp.get_table::<Organization>("my_organizations"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MyOrganizationsInsertCallbackId(__sdk::CallbackId);
pub struct MyOrganizationsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for MyOrganizationsTableHandle<'ctx> {
    type Row = Organization;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Organization> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MyOrganizationsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyOrganizationsInsertCallbackId {
        MyOrganizationsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyOrganizationsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MyOrganizationsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyOrganizationsDeleteCallbackId {
        MyOrganizationsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyOrganizationsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Organization>("my_organizations");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Organization>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Organization>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Organization`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait my_organizationsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Organization`.
    fn my_organizations(&self) -> __sdk::__query_builder::Table<Organization>;
}

impl my_organizationsQueryTableAccess for __sdk::QueryTableAccessor {
    fn my_organizations(&self) -> __sdk::__query_builder::Table<Organization> {
        __sdk::__query_builder::Table::new("my_organizations")
    }
}
