// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::rental_tenant_meter_type::RentalTenantMeter;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `my_rental_tenant_meters`.
///
/// Obtain a handle from the [`MyRentalTenantMetersTableAccess::my_rental_tenant_meters`] method on [`super::RemoteTables`],
/// like `ctx.db.my_rental_tenant_meters()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.my_rental_tenant_meters().on_insert(...)`.
pub struct MyRentalTenantMetersTableHandle<'ctx> {
    imp: __sdk::TableHandle<RentalTenantMeter>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `my_rental_tenant_meters`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MyRentalTenantMetersTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MyRentalTenantMetersTableHandle`], which mediates access to the table `my_rental_tenant_meters`.
    fn my_rental_tenant_meters(&self) -> MyRentalTenantMetersTableHandle<'_>;
}

impl MyRentalTenantMetersTableAccess for super::RemoteTables {
    fn my_rental_tenant_meters(&self) -> MyRentalTenantMetersTableHandle<'_> {
        MyRentalTenantMetersTableHandle {
            imp: self
                .imp
                .get_table::<RentalTenantMeter>("my_rental_tenant_meters"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MyRentalTenantMetersInsertCallbackId(__sdk::CallbackId);
pub struct MyRentalTenantMetersDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for MyRentalTenantMetersTableHandle<'ctx> {
    type Row = RentalTenantMeter;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = RentalTenantMeter> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MyRentalTenantMetersInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyRentalTenantMetersInsertCallbackId {
        MyRentalTenantMetersInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyRentalTenantMetersInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MyRentalTenantMetersDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyRentalTenantMetersDeleteCallbackId {
        MyRentalTenantMetersDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyRentalTenantMetersDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<RentalTenantMeter>("my_rental_tenant_meters");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<RentalTenantMeter>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<RentalTenantMeter>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `RentalTenantMeter`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait my_rental_tenant_metersQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `RentalTenantMeter`.
    fn my_rental_tenant_meters(&self) -> __sdk::__query_builder::Table<RentalTenantMeter>;
}

impl my_rental_tenant_metersQueryTableAccess for __sdk::QueryTableAccessor {
    fn my_rental_tenant_meters(&self) -> __sdk::__query_builder::Table<RentalTenantMeter> {
        __sdk::__query_builder::Table::new("my_rental_tenant_meters")
    }
}
