// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::reimbursement_type::Reimbursement;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `my_reimbursements`.
///
/// Obtain a handle from the [`MyReimbursementsTableAccess::my_reimbursements`] method on [`super::RemoteTables`],
/// like `ctx.db.my_reimbursements()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.my_reimbursements().on_insert(...)`.
pub struct MyReimbursementsTableHandle<'ctx> {
    imp: __sdk::TableHandle<Reimbursement>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `my_reimbursements`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MyReimbursementsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MyReimbursementsTableHandle`], which mediates access to the table `my_reimbursements`.
    fn my_reimbursements(&self) -> MyReimbursementsTableHandle<'_>;
}

impl MyReimbursementsTableAccess for super::RemoteTables {
    fn my_reimbursements(&self) -> MyReimbursementsTableHandle<'_> {
        MyReimbursementsTableHandle {
            imp: self.imp.get_table::<Reimbursement>("my_reimbursements"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MyReimbursementsInsertCallbackId(__sdk::CallbackId);
pub struct MyReimbursementsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for MyReimbursementsTableHandle<'ctx> {
    type Row = Reimbursement;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Reimbursement> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MyReimbursementsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyReimbursementsInsertCallbackId {
        MyReimbursementsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyReimbursementsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MyReimbursementsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyReimbursementsDeleteCallbackId {
        MyReimbursementsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyReimbursementsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Reimbursement>("my_reimbursements");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Reimbursement>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Reimbursement>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Reimbursement`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait my_reimbursementsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Reimbursement`.
    fn my_reimbursements(&self) -> __sdk::__query_builder::Table<Reimbursement>;
}

impl my_reimbursementsQueryTableAccess for __sdk::QueryTableAccessor {
    fn my_reimbursements(&self) -> __sdk::__query_builder::Table<Reimbursement> {
        __sdk::__query_builder::Table::new("my_reimbursements")
    }
}
