// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::salary_image_preview_type::SalaryImagePreview;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `my_salary_image_previews`.
///
/// Obtain a handle from the [`MySalaryImagePreviewsTableAccess::my_salary_image_previews`] method on [`super::RemoteTables`],
/// like `ctx.db.my_salary_image_previews()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.my_salary_image_previews().on_insert(...)`.
pub struct MySalaryImagePreviewsTableHandle<'ctx> {
    imp: __sdk::TableHandle<SalaryImagePreview>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `my_salary_image_previews`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MySalaryImagePreviewsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MySalaryImagePreviewsTableHandle`], which mediates access to the table `my_salary_image_previews`.
    fn my_salary_image_previews(&self) -> MySalaryImagePreviewsTableHandle<'_>;
}

impl MySalaryImagePreviewsTableAccess for super::RemoteTables {
    fn my_salary_image_previews(&self) -> MySalaryImagePreviewsTableHandle<'_> {
        MySalaryImagePreviewsTableHandle {
            imp: self
                .imp
                .get_table::<SalaryImagePreview>("my_salary_image_previews"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MySalaryImagePreviewsInsertCallbackId(__sdk::CallbackId);
pub struct MySalaryImagePreviewsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for MySalaryImagePreviewsTableHandle<'ctx> {
    type Row = SalaryImagePreview;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = SalaryImagePreview> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MySalaryImagePreviewsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MySalaryImagePreviewsInsertCallbackId {
        MySalaryImagePreviewsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MySalaryImagePreviewsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MySalaryImagePreviewsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MySalaryImagePreviewsDeleteCallbackId {
        MySalaryImagePreviewsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MySalaryImagePreviewsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<SalaryImagePreview>("my_salary_image_previews");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<SalaryImagePreview>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<SalaryImagePreview>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `SalaryImagePreview`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait my_salary_image_previewsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `SalaryImagePreview`.
    fn my_salary_image_previews(&self) -> __sdk::__query_builder::Table<SalaryImagePreview>;
}

impl my_salary_image_previewsQueryTableAccess for __sdk::QueryTableAccessor {
    fn my_salary_image_previews(&self) -> __sdk::__query_builder::Table<SalaryImagePreview> {
        __sdk::__query_builder::Table::new("my_salary_image_previews")
    }
}
