// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::salary_image_type::SalaryImage;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `my_salary_images`.
///
/// Obtain a handle from the [`MySalaryImagesTableAccess::my_salary_images`] method on [`super::RemoteTables`],
/// like `ctx.db.my_salary_images()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.my_salary_images().on_insert(...)`.
pub struct MySalaryImagesTableHandle<'ctx> {
    imp: __sdk::TableHandle<SalaryImage>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `my_salary_images`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MySalaryImagesTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MySalaryImagesTableHandle`], which mediates access to the table `my_salary_images`.
    fn my_salary_images(&self) -> MySalaryImagesTableHandle<'_>;
}

impl MySalaryImagesTableAccess for super::RemoteTables {
    fn my_salary_images(&self) -> MySalaryImagesTableHandle<'_> {
        MySalaryImagesTableHandle {
            imp: self.imp.get_table::<SalaryImage>("my_salary_images"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MySalaryImagesInsertCallbackId(__sdk::CallbackId);
pub struct MySalaryImagesDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for MySalaryImagesTableHandle<'ctx> {
    type Row = SalaryImage;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = SalaryImage> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MySalaryImagesInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MySalaryImagesInsertCallbackId {
        MySalaryImagesInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MySalaryImagesInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MySalaryImagesDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MySalaryImagesDeleteCallbackId {
        MySalaryImagesDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MySalaryImagesDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<SalaryImage>("my_salary_images");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<SalaryImage>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<SalaryImage>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `SalaryImage`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait my_salary_imagesQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `SalaryImage`.
    fn my_salary_images(&self) -> __sdk::__query_builder::Table<SalaryImage>;
}

impl my_salary_imagesQueryTableAccess for __sdk::QueryTableAccessor {
    fn my_salary_images(&self) -> __sdk::__query_builder::Table<SalaryImage> {
        __sdk::__query_builder::Table::new("my_salary_images")
    }
}
