// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::tenant_provisioning_job_type::TenantProvisioningJob;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `my_tenant_provisioning_jobs`.
///
/// Obtain a handle from the [`MyTenantProvisioningJobsTableAccess::my_tenant_provisioning_jobs`] method on [`super::RemoteTables`],
/// like `ctx.db.my_tenant_provisioning_jobs()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.my_tenant_provisioning_jobs().on_insert(...)`.
pub struct MyTenantProvisioningJobsTableHandle<'ctx> {
    imp: __sdk::TableHandle<TenantProvisioningJob>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `my_tenant_provisioning_jobs`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MyTenantProvisioningJobsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MyTenantProvisioningJobsTableHandle`], which mediates access to the table `my_tenant_provisioning_jobs`.
    fn my_tenant_provisioning_jobs(&self) -> MyTenantProvisioningJobsTableHandle<'_>;
}

impl MyTenantProvisioningJobsTableAccess for super::RemoteTables {
    fn my_tenant_provisioning_jobs(&self) -> MyTenantProvisioningJobsTableHandle<'_> {
        MyTenantProvisioningJobsTableHandle {
            imp: self
                .imp
                .get_table::<TenantProvisioningJob>("my_tenant_provisioning_jobs"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MyTenantProvisioningJobsInsertCallbackId(__sdk::CallbackId);
pub struct MyTenantProvisioningJobsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for MyTenantProvisioningJobsTableHandle<'ctx> {
    type Row = TenantProvisioningJob;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = TenantProvisioningJob> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MyTenantProvisioningJobsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyTenantProvisioningJobsInsertCallbackId {
        MyTenantProvisioningJobsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyTenantProvisioningJobsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MyTenantProvisioningJobsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyTenantProvisioningJobsDeleteCallbackId {
        MyTenantProvisioningJobsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyTenantProvisioningJobsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table =
        client_cache.get_or_make_table::<TenantProvisioningJob>("my_tenant_provisioning_jobs");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<TenantProvisioningJob>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<TenantProvisioningJob>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `TenantProvisioningJob`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait my_tenant_provisioning_jobsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `TenantProvisioningJob`.
    fn my_tenant_provisioning_jobs(&self) -> __sdk::__query_builder::Table<TenantProvisioningJob>;
}

impl my_tenant_provisioning_jobsQueryTableAccess for __sdk::QueryTableAccessor {
    fn my_tenant_provisioning_jobs(&self) -> __sdk::__query_builder::Table<TenantProvisioningJob> {
        __sdk::__query_builder::Table::new("my_tenant_provisioning_jobs")
    }
}
