// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::tenant_invitation_type::TenantInvitation;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `my_tenant_invitations`.
///
/// Obtain a handle from the [`MyTenantInvitationsTableAccess::my_tenant_invitations`] method on [`super::RemoteTables`],
/// like `ctx.db.my_tenant_invitations()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.my_tenant_invitations().on_insert(...)`.
pub struct MyTenantInvitationsTableHandle<'ctx> {
    imp: __sdk::TableHandle<TenantInvitation>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `my_tenant_invitations`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MyTenantInvitationsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MyTenantInvitationsTableHandle`], which mediates access to the table `my_tenant_invitations`.
    fn my_tenant_invitations(&self) -> MyTenantInvitationsTableHandle<'_>;
}

impl MyTenantInvitationsTableAccess for super::RemoteTables {
    fn my_tenant_invitations(&self) -> MyTenantInvitationsTableHandle<'_> {
        MyTenantInvitationsTableHandle {
            imp: self
                .imp
                .get_table::<TenantInvitation>("my_tenant_invitations"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MyTenantInvitationsInsertCallbackId(__sdk::CallbackId);
pub struct MyTenantInvitationsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for MyTenantInvitationsTableHandle<'ctx> {
    type Row = TenantInvitation;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = TenantInvitation> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MyTenantInvitationsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyTenantInvitationsInsertCallbackId {
        MyTenantInvitationsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyTenantInvitationsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MyTenantInvitationsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyTenantInvitationsDeleteCallbackId {
        MyTenantInvitationsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyTenantInvitationsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<TenantInvitation>("my_tenant_invitations");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<TenantInvitation>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<TenantInvitation>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `TenantInvitation`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait my_tenant_invitationsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `TenantInvitation`.
    fn my_tenant_invitations(&self) -> __sdk::__query_builder::Table<TenantInvitation>;
}

impl my_tenant_invitationsQueryTableAccess for __sdk::QueryTableAccessor {
    fn my_tenant_invitations(&self) -> __sdk::__query_builder::Table<TenantInvitation> {
        __sdk::__query_builder::Table::new("my_tenant_invitations")
    }
}
