// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::customer_type::Customer;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `my_tenants`.
///
/// Obtain a handle from the [`MyTenantsTableAccess::my_tenants`] method on [`super::RemoteTables`],
/// like `ctx.db.my_tenants()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.my_tenants().on_insert(...)`.
pub struct MyTenantsTableHandle<'ctx> {
    imp: __sdk::TableHandle<Customer>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `my_tenants`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MyTenantsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MyTenantsTableHandle`], which mediates access to the table `my_tenants`.
    fn my_tenants(&self) -> MyTenantsTableHandle<'_>;
}

impl MyTenantsTableAccess for super::RemoteTables {
    fn my_tenants(&self) -> MyTenantsTableHandle<'_> {
        MyTenantsTableHandle {
            imp: self.imp.get_table::<Customer>("my_tenants"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MyTenantsInsertCallbackId(__sdk::CallbackId);
pub struct MyTenantsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for MyTenantsTableHandle<'ctx> {
    type Row = Customer;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Customer> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MyTenantsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyTenantsInsertCallbackId {
        MyTenantsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyTenantsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MyTenantsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyTenantsDeleteCallbackId {
        MyTenantsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyTenantsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Customer>("my_tenants");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Customer>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Customer>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Customer`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait my_tenantsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Customer`.
    fn my_tenants(&self) -> __sdk::__query_builder::Table<Customer>;
}

impl my_tenantsQueryTableAccess for __sdk::QueryTableAccessor {
    fn my_tenants(&self) -> __sdk::__query_builder::Table<Customer> {
        __sdk::__query_builder::Table::new("my_tenants")
    }
}
