// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::transformer_asset_type::TransformerAsset;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `my_transformer_assets`.
///
/// Obtain a handle from the [`MyTransformerAssetsTableAccess::my_transformer_assets`] method on [`super::RemoteTables`],
/// like `ctx.db.my_transformer_assets()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.my_transformer_assets().on_insert(...)`.
pub struct MyTransformerAssetsTableHandle<'ctx> {
    imp: __sdk::TableHandle<TransformerAsset>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `my_transformer_assets`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MyTransformerAssetsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MyTransformerAssetsTableHandle`], which mediates access to the table `my_transformer_assets`.
    fn my_transformer_assets(&self) -> MyTransformerAssetsTableHandle<'_>;
}

impl MyTransformerAssetsTableAccess for super::RemoteTables {
    fn my_transformer_assets(&self) -> MyTransformerAssetsTableHandle<'_> {
        MyTransformerAssetsTableHandle {
            imp: self
                .imp
                .get_table::<TransformerAsset>("my_transformer_assets"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MyTransformerAssetsInsertCallbackId(__sdk::CallbackId);
pub struct MyTransformerAssetsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for MyTransformerAssetsTableHandle<'ctx> {
    type Row = TransformerAsset;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = TransformerAsset> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MyTransformerAssetsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyTransformerAssetsInsertCallbackId {
        MyTransformerAssetsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyTransformerAssetsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MyTransformerAssetsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyTransformerAssetsDeleteCallbackId {
        MyTransformerAssetsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyTransformerAssetsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<TransformerAsset>("my_transformer_assets");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<TransformerAsset>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<TransformerAsset>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `TransformerAsset`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait my_transformer_assetsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `TransformerAsset`.
    fn my_transformer_assets(&self) -> __sdk::__query_builder::Table<TransformerAsset>;
}

impl my_transformer_assetsQueryTableAccess for __sdk::QueryTableAccessor {
    fn my_transformer_assets(&self) -> __sdk::__query_builder::Table<TransformerAsset> {
        __sdk::__query_builder::Table::new("my_transformer_assets")
    }
}
