// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::vip_membership_refund_type::VipMembershipRefund;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `my_vip_membership_refunds`.
///
/// Obtain a handle from the [`MyVipMembershipRefundsTableAccess::my_vip_membership_refunds`] method on [`super::RemoteTables`],
/// like `ctx.db.my_vip_membership_refunds()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.my_vip_membership_refunds().on_insert(...)`.
pub struct MyVipMembershipRefundsTableHandle<'ctx> {
    imp: __sdk::TableHandle<VipMembershipRefund>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `my_vip_membership_refunds`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MyVipMembershipRefundsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MyVipMembershipRefundsTableHandle`], which mediates access to the table `my_vip_membership_refunds`.
    fn my_vip_membership_refunds(&self) -> MyVipMembershipRefundsTableHandle<'_>;
}

impl MyVipMembershipRefundsTableAccess for super::RemoteTables {
    fn my_vip_membership_refunds(&self) -> MyVipMembershipRefundsTableHandle<'_> {
        MyVipMembershipRefundsTableHandle {
            imp: self
                .imp
                .get_table::<VipMembershipRefund>("my_vip_membership_refunds"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MyVipMembershipRefundsInsertCallbackId(__sdk::CallbackId);
pub struct MyVipMembershipRefundsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for MyVipMembershipRefundsTableHandle<'ctx> {
    type Row = VipMembershipRefund;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = VipMembershipRefund> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MyVipMembershipRefundsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyVipMembershipRefundsInsertCallbackId {
        MyVipMembershipRefundsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyVipMembershipRefundsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MyVipMembershipRefundsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyVipMembershipRefundsDeleteCallbackId {
        MyVipMembershipRefundsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyVipMembershipRefundsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<VipMembershipRefund>("my_vip_membership_refunds");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<VipMembershipRefund>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<VipMembershipRefund>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `VipMembershipRefund`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait my_vip_membership_refundsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `VipMembershipRefund`.
    fn my_vip_membership_refunds(&self) -> __sdk::__query_builder::Table<VipMembershipRefund>;
}

impl my_vip_membership_refundsQueryTableAccess for __sdk::QueryTableAccessor {
    fn my_vip_membership_refunds(&self) -> __sdk::__query_builder::Table<VipMembershipRefund> {
        __sdk::__query_builder::Table::new("my_vip_membership_refunds")
    }
}
