// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::vip_membership_entitlement_type::VipMembershipEntitlement;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `my_vip_membership_entitlements`.
///
/// Obtain a handle from the [`MyVipMembershipEntitlementsTableAccess::my_vip_membership_entitlements`] method on [`super::RemoteTables`],
/// like `ctx.db.my_vip_membership_entitlements()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.my_vip_membership_entitlements().on_insert(...)`.
pub struct MyVipMembershipEntitlementsTableHandle<'ctx> {
    imp: __sdk::TableHandle<VipMembershipEntitlement>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `my_vip_membership_entitlements`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MyVipMembershipEntitlementsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MyVipMembershipEntitlementsTableHandle`], which mediates access to the table `my_vip_membership_entitlements`.
    fn my_vip_membership_entitlements(&self) -> MyVipMembershipEntitlementsTableHandle<'_>;
}

impl MyVipMembershipEntitlementsTableAccess for super::RemoteTables {
    fn my_vip_membership_entitlements(&self) -> MyVipMembershipEntitlementsTableHandle<'_> {
        MyVipMembershipEntitlementsTableHandle {
            imp: self
                .imp
                .get_table::<VipMembershipEntitlement>("my_vip_membership_entitlements"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MyVipMembershipEntitlementsInsertCallbackId(__sdk::CallbackId);
pub struct MyVipMembershipEntitlementsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for MyVipMembershipEntitlementsTableHandle<'ctx> {
    type Row = VipMembershipEntitlement;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = VipMembershipEntitlement> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MyVipMembershipEntitlementsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyVipMembershipEntitlementsInsertCallbackId {
        MyVipMembershipEntitlementsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyVipMembershipEntitlementsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MyVipMembershipEntitlementsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyVipMembershipEntitlementsDeleteCallbackId {
        MyVipMembershipEntitlementsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyVipMembershipEntitlementsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache
        .get_or_make_table::<VipMembershipEntitlement>("my_vip_membership_entitlements");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<VipMembershipEntitlement>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<VipMembershipEntitlement>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `VipMembershipEntitlement`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait my_vip_membership_entitlementsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `VipMembershipEntitlement`.
    fn my_vip_membership_entitlements(
        &self,
    ) -> __sdk::__query_builder::Table<VipMembershipEntitlement>;
}

impl my_vip_membership_entitlementsQueryTableAccess for __sdk::QueryTableAccessor {
    fn my_vip_membership_entitlements(
        &self,
    ) -> __sdk::__query_builder::Table<VipMembershipEntitlement> {
        __sdk::__query_builder::Table::new("my_vip_membership_entitlements")
    }
}
