// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::vip_membership_payment_type::VipMembershipPayment;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `my_vip_membership_payments`.
///
/// Obtain a handle from the [`MyVipMembershipPaymentsTableAccess::my_vip_membership_payments`] method on [`super::RemoteTables`],
/// like `ctx.db.my_vip_membership_payments()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.my_vip_membership_payments().on_insert(...)`.
pub struct MyVipMembershipPaymentsTableHandle<'ctx> {
    imp: __sdk::TableHandle<VipMembershipPayment>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `my_vip_membership_payments`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MyVipMembershipPaymentsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MyVipMembershipPaymentsTableHandle`], which mediates access to the table `my_vip_membership_payments`.
    fn my_vip_membership_payments(&self) -> MyVipMembershipPaymentsTableHandle<'_>;
}

impl MyVipMembershipPaymentsTableAccess for super::RemoteTables {
    fn my_vip_membership_payments(&self) -> MyVipMembershipPaymentsTableHandle<'_> {
        MyVipMembershipPaymentsTableHandle {
            imp: self
                .imp
                .get_table::<VipMembershipPayment>("my_vip_membership_payments"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MyVipMembershipPaymentsInsertCallbackId(__sdk::CallbackId);
pub struct MyVipMembershipPaymentsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for MyVipMembershipPaymentsTableHandle<'ctx> {
    type Row = VipMembershipPayment;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = VipMembershipPayment> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MyVipMembershipPaymentsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyVipMembershipPaymentsInsertCallbackId {
        MyVipMembershipPaymentsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MyVipMembershipPaymentsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MyVipMembershipPaymentsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MyVipMembershipPaymentsDeleteCallbackId {
        MyVipMembershipPaymentsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MyVipMembershipPaymentsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table =
        client_cache.get_or_make_table::<VipMembershipPayment>("my_vip_membership_payments");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<VipMembershipPayment>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<VipMembershipPayment>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `VipMembershipPayment`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait my_vip_membership_paymentsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `VipMembershipPayment`.
    fn my_vip_membership_payments(&self) -> __sdk::__query_builder::Table<VipMembershipPayment>;
}

impl my_vip_membership_paymentsQueryTableAccess for __sdk::QueryTableAccessor {
    fn my_vip_membership_payments(&self) -> __sdk::__query_builder::Table<VipMembershipPayment> {
        __sdk::__query_builder::Table::new("my_vip_membership_payments")
    }
}
