// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::mysql_image_import_type::MysqlImageImport;
use super::mysql_park_import_type::MysqlParkImport;
use super::mysql_rental_tenant_import_type::MysqlRentalTenantImport;
use super::mysql_salary_image_import_type::MysqlSalaryImageImport;
use super::mysql_salary_import_type::MysqlSalaryImport;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct MysqlSalaryBatchImport {
    pub parks: Vec<MysqlParkImport>,
    pub rental_tenants: Vec<MysqlRentalTenantImport>,
    pub salaries: Vec<MysqlSalaryImport>,
    pub images: Vec<MysqlImageImport>,
    pub salary_images: Vec<MysqlSalaryImageImport>,
}

impl __sdk::InModule for MysqlSalaryBatchImport {
    type Module = super::RemoteModule;
}
