// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::mysql_media_image_import_type::MysqlMediaImageImport;
use super::mysql_tenant_image_import_type::MysqlTenantImageImport;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct MysqlContractMediaBatchImport {
    pub customer_id: String,
    pub images: Vec<MysqlMediaImageImport>,
    pub tenant_images: Vec<MysqlTenantImageImport>,
}

impl __sdk::InModule for MysqlContractMediaBatchImport {
    type Module = super::RemoteModule;
}
