// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::mysql_factory_floor_image_import_type::MysqlFactoryFloorImageImport;
use super::mysql_media_image_import_type::MysqlMediaImageImport;
use super::mysql_park_image_import_type::MysqlParkImageImport;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct MysqlMediaBatchImport {
    pub images: Vec<MysqlMediaImageImport>,
    pub park_images: Vec<MysqlParkImageImport>,
    pub factory_floor_images: Vec<MysqlFactoryFloorImageImport>,
}

impl __sdk::InModule for MysqlMediaBatchImport {
    type Module = super::RemoteModule;
}
