// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct MysqlFactoryImport {
    pub factory_id: u64,
    pub factory_name: String,
    pub park_id: u64,
    pub build_date: Option<String>,
    pub address: String,
    pub contact: String,
    pub description: Option<String>,
    pub is_own: bool,
    pub is_deleted: bool,
    pub created_at_micros: Option<i64>,
    pub updated_at_micros: Option<i64>,
}

impl __sdk::InModule for MysqlFactoryImport {
    type Module = super::RemoteModule;
}
