// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Notice {
    pub notice_id: String,
    pub global_scope: u8,
    pub title: Option<String>,
    pub date: Option<String>,
    pub notice_type: Option<String>,
    pub category: Option<String>,
    pub project_type: Option<String>,
    pub site_code: Option<String>,
    pub owner: Option<String>,
    pub platform: Option<String>,
    pub link: Option<String>,
    pub is_valid: bool,
    pub invalid_reason: Option<String>,
    pub last_checked_at: Option<__sdk::Timestamp>,
    pub created_at: __sdk::Timestamp,
    pub updated_at: __sdk::Timestamp,
}

impl __sdk::InModule for Notice {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Notice`.
///
/// Provides typed access to columns for query building.
pub struct NoticeCols {
    pub notice_id: __sdk::__query_builder::Col<Notice, String>,
    pub global_scope: __sdk::__query_builder::Col<Notice, u8>,
    pub title: __sdk::__query_builder::Col<Notice, Option<String>>,
    pub date: __sdk::__query_builder::Col<Notice, Option<String>>,
    pub notice_type: __sdk::__query_builder::Col<Notice, Option<String>>,
    pub category: __sdk::__query_builder::Col<Notice, Option<String>>,
    pub project_type: __sdk::__query_builder::Col<Notice, Option<String>>,
    pub site_code: __sdk::__query_builder::Col<Notice, Option<String>>,
    pub owner: __sdk::__query_builder::Col<Notice, Option<String>>,
    pub platform: __sdk::__query_builder::Col<Notice, Option<String>>,
    pub link: __sdk::__query_builder::Col<Notice, Option<String>>,
    pub is_valid: __sdk::__query_builder::Col<Notice, bool>,
    pub invalid_reason: __sdk::__query_builder::Col<Notice, Option<String>>,
    pub last_checked_at: __sdk::__query_builder::Col<Notice, Option<__sdk::Timestamp>>,
    pub created_at: __sdk::__query_builder::Col<Notice, __sdk::Timestamp>,
    pub updated_at: __sdk::__query_builder::Col<Notice, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for Notice {
    type Cols = NoticeCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        NoticeCols {
            notice_id: __sdk::__query_builder::Col::new(table_name, "notice_id"),
            global_scope: __sdk::__query_builder::Col::new(table_name, "global_scope"),
            title: __sdk::__query_builder::Col::new(table_name, "title"),
            date: __sdk::__query_builder::Col::new(table_name, "date"),
            notice_type: __sdk::__query_builder::Col::new(table_name, "notice_type"),
            category: __sdk::__query_builder::Col::new(table_name, "category"),
            project_type: __sdk::__query_builder::Col::new(table_name, "project_type"),
            site_code: __sdk::__query_builder::Col::new(table_name, "site_code"),
            owner: __sdk::__query_builder::Col::new(table_name, "owner"),
            platform: __sdk::__query_builder::Col::new(table_name, "platform"),
            link: __sdk::__query_builder::Col::new(table_name, "link"),
            is_valid: __sdk::__query_builder::Col::new(table_name, "is_valid"),
            invalid_reason: __sdk::__query_builder::Col::new(table_name, "invalid_reason"),
            last_checked_at: __sdk::__query_builder::Col::new(table_name, "last_checked_at"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
        }
    }
}

/// Indexed column accessor struct for the table `Notice`.
///
/// Provides typed access to indexed columns for query building.
pub struct NoticeIxCols {
    pub date: __sdk::__query_builder::IxCol<Notice, Option<String>>,
    pub global_scope: __sdk::__query_builder::IxCol<Notice, u8>,
    pub is_valid: __sdk::__query_builder::IxCol<Notice, bool>,
    pub last_checked_at: __sdk::__query_builder::IxCol<Notice, Option<__sdk::Timestamp>>,
    pub notice_id: __sdk::__query_builder::IxCol<Notice, String>,
}

impl __sdk::__query_builder::HasIxCols for Notice {
    type IxCols = NoticeIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        NoticeIxCols {
            date: __sdk::__query_builder::IxCol::new(table_name, "date"),
            global_scope: __sdk::__query_builder::IxCol::new(table_name, "global_scope"),
            is_valid: __sdk::__query_builder::IxCol::new(table_name, "is_valid"),
            last_checked_at: __sdk::__query_builder::IxCol::new(table_name, "last_checked_at"),
            notice_id: __sdk::__query_builder::IxCol::new(table_name, "notice_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Notice {}
