// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::billing_page_result_type::BillingPageResult;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
struct QueryBillingPageArgs {
    pub page: u32,
    pub page_size: u32,
    pub project_keyword: String,
    pub tenant_keyword: String,
    pub collection_status: Option<String>,
    pub park_id: Option<u64>,
    pub start_time_micros: Option<i64>,
    pub end_time_micros: Option<i64>,
}

impl __sdk::InModule for QueryBillingPageArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the procedure `query_billing_page`.
///
/// Implemented for [`super::RemoteProcedures`].
pub trait query_billing_page {
    fn query_billing_page(
        &self,
        page: u32,
        page_size: u32,
        project_keyword: String,
        tenant_keyword: String,
        collection_status: Option<String>,
        park_id: Option<u64>,
        start_time_micros: Option<i64>,
        end_time_micros: Option<i64>,
    ) {
        self.query_billing_page_then(
            page,
            page_size,
            project_keyword,
            tenant_keyword,
            collection_status,
            park_id,
            start_time_micros,
            end_time_micros,
            |_, _| {},
        );
    }

    fn query_billing_page_then(
        &self,
        page: u32,
        page_size: u32,
        project_keyword: String,
        tenant_keyword: String,
        collection_status: Option<String>,
        park_id: Option<u64>,
        start_time_micros: Option<i64>,
        end_time_micros: Option<i64>,

        __callback: impl FnOnce(&super::ProcedureEventContext, Result<BillingPageResult, __sdk::InternalError>)
            + Send
            + 'static,
    );
}

impl query_billing_page for super::RemoteProcedures {
    fn query_billing_page_then(
        &self,
        page: u32,
        page_size: u32,
        project_keyword: String,
        tenant_keyword: String,
        collection_status: Option<String>,
        park_id: Option<u64>,
        start_time_micros: Option<i64>,
        end_time_micros: Option<i64>,

        __callback: impl FnOnce(&super::ProcedureEventContext, Result<BillingPageResult, __sdk::InternalError>)
            + Send
            + 'static,
    ) {
        self.imp
            .invoke_procedure_with_callback::<_, BillingPageResult>(
                "query_billing_page",
                QueryBillingPageArgs {
                    page,
                    page_size,
                    project_keyword,
                    tenant_keyword,
                    collection_status,
                    park_id,
                    start_time_micros,
                    end_time_micros,
                },
                __callback,
            );
    }
}
