// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::salary_page_result_type::SalaryPageResult;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
struct QuerySalaryPageArgs {
    pub page: u32,
    pub page_size: u32,
    pub name_keyword: String,
    pub phone_keyword: String,
    pub issued: Option<bool>,
    pub department: String,
    pub start_time_micros: Option<i64>,
    pub end_time_micros: Option<i64>,
}

impl __sdk::InModule for QuerySalaryPageArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the procedure `query_salary_page`.
///
/// Implemented for [`super::RemoteProcedures`].
pub trait query_salary_page {
    fn query_salary_page(
        &self,
        page: u32,
        page_size: u32,
        name_keyword: String,
        phone_keyword: String,
        issued: Option<bool>,
        department: String,
        start_time_micros: Option<i64>,
        end_time_micros: Option<i64>,
    ) {
        self.query_salary_page_then(
            page,
            page_size,
            name_keyword,
            phone_keyword,
            issued,
            department,
            start_time_micros,
            end_time_micros,
            |_, _| {},
        );
    }

    fn query_salary_page_then(
        &self,
        page: u32,
        page_size: u32,
        name_keyword: String,
        phone_keyword: String,
        issued: Option<bool>,
        department: String,
        start_time_micros: Option<i64>,
        end_time_micros: Option<i64>,

        __callback: impl FnOnce(&super::ProcedureEventContext, Result<SalaryPageResult, __sdk::InternalError>)
            + Send
            + 'static,
    );
}

impl query_salary_page for super::RemoteProcedures {
    fn query_salary_page_then(
        &self,
        page: u32,
        page_size: u32,
        name_keyword: String,
        phone_keyword: String,
        issued: Option<bool>,
        department: String,
        start_time_micros: Option<i64>,
        end_time_micros: Option<i64>,

        __callback: impl FnOnce(&super::ProcedureEventContext, Result<SalaryPageResult, __sdk::InternalError>)
            + Send
            + 'static,
    ) {
        self.imp
            .invoke_procedure_with_callback::<_, SalaryPageResult>(
                "query_salary_page",
                QuerySalaryPageArgs {
                    page,
                    page_size,
                    name_keyword,
                    phone_keyword,
                    issued,
                    department,
                    start_time_micros,
                    end_time_micros,
                },
                __callback,
            );
    }
}
