// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::finance_page_result_type::FinancePageResult;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
struct QueryFinancePageArgs {
    pub page: u32,
    pub page_size: u32,
    pub keyword: String,
    pub transaction_type: Option<String>,
    pub park_id: Option<u64>,
    pub start_time_micros: Option<i64>,
    pub end_time_micros: Option<i64>,
}

impl __sdk::InModule for QueryFinancePageArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the procedure `query_finance_page`.
///
/// Implemented for [`super::RemoteProcedures`].
pub trait query_finance_page {
    fn query_finance_page(
        &self,
        page: u32,
        page_size: u32,
        keyword: String,
        transaction_type: Option<String>,
        park_id: Option<u64>,
        start_time_micros: Option<i64>,
        end_time_micros: Option<i64>,
    ) {
        self.query_finance_page_then(
            page,
            page_size,
            keyword,
            transaction_type,
            park_id,
            start_time_micros,
            end_time_micros,
            |_, _| {},
        );
    }

    fn query_finance_page_then(
        &self,
        page: u32,
        page_size: u32,
        keyword: String,
        transaction_type: Option<String>,
        park_id: Option<u64>,
        start_time_micros: Option<i64>,
        end_time_micros: Option<i64>,

        __callback: impl FnOnce(&super::ProcedureEventContext, Result<FinancePageResult, __sdk::InternalError>)
            + Send
            + 'static,
    );
}

impl query_finance_page for super::RemoteProcedures {
    fn query_finance_page_then(
        &self,
        page: u32,
        page_size: u32,
        keyword: String,
        transaction_type: Option<String>,
        park_id: Option<u64>,
        start_time_micros: Option<i64>,
        end_time_micros: Option<i64>,

        __callback: impl FnOnce(&super::ProcedureEventContext, Result<FinancePageResult, __sdk::InternalError>)
            + Send
            + 'static,
    ) {
        self.imp
            .invoke_procedure_with_callback::<_, FinancePageResult>(
                "query_finance_page",
                QueryFinancePageArgs {
                    page,
                    page_size,
                    keyword,
                    transaction_type,
                    park_id,
                    start_time_micros,
                    end_time_micros,
                },
                __callback,
            );
    }
}
