// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RecalculateCompanyLeadScoreArgs {
    pub lead_id: u64,
}

impl From<RecalculateCompanyLeadScoreArgs> for super::Reducer {
    fn from(args: RecalculateCompanyLeadScoreArgs) -> Self {
        Self::RecalculateCompanyLeadScore {
            lead_id: args.lead_id,
        }
    }
}

impl __sdk::InModule for RecalculateCompanyLeadScoreArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `recalculate_company_lead_score`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait recalculate_company_lead_score {
    /// Request that the remote module invoke the reducer `recalculate_company_lead_score` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`recalculate_company_lead_score:recalculate_company_lead_score_then`] to run a callback after the reducer completes.
    fn recalculate_company_lead_score(&self, lead_id: u64) -> __sdk::Result<()> {
        self.recalculate_company_lead_score_then(lead_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `recalculate_company_lead_score` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn recalculate_company_lead_score_then(
        &self,
        lead_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl recalculate_company_lead_score for super::RemoteReducers {
    fn recalculate_company_lead_score_then(
        &self,
        lead_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(RecalculateCompanyLeadScoreArgs { lead_id }, callback)
    }
}
