// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct RefreshToken {
    pub id: u64,
    pub user_id: u64,
    pub jti: String,
    pub token_hash: String,
    pub expires_at: __sdk::Timestamp,
    pub revoked_at: Option<__sdk::Timestamp>,
    pub replaced_by_jti: Option<String>,
    pub ip: Option<String>,
    pub user_agent: Option<String>,
    pub created_at: __sdk::Timestamp,
    pub updated_at: Option<__sdk::Timestamp>,
}

impl __sdk::InModule for RefreshToken {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `RefreshToken`.
///
/// Provides typed access to columns for query building.
pub struct RefreshTokenCols {
    pub id: __sdk::__query_builder::Col<RefreshToken, u64>,
    pub user_id: __sdk::__query_builder::Col<RefreshToken, u64>,
    pub jti: __sdk::__query_builder::Col<RefreshToken, String>,
    pub token_hash: __sdk::__query_builder::Col<RefreshToken, String>,
    pub expires_at: __sdk::__query_builder::Col<RefreshToken, __sdk::Timestamp>,
    pub revoked_at: __sdk::__query_builder::Col<RefreshToken, Option<__sdk::Timestamp>>,
    pub replaced_by_jti: __sdk::__query_builder::Col<RefreshToken, Option<String>>,
    pub ip: __sdk::__query_builder::Col<RefreshToken, Option<String>>,
    pub user_agent: __sdk::__query_builder::Col<RefreshToken, Option<String>>,
    pub created_at: __sdk::__query_builder::Col<RefreshToken, __sdk::Timestamp>,
    pub updated_at: __sdk::__query_builder::Col<RefreshToken, Option<__sdk::Timestamp>>,
}

impl __sdk::__query_builder::HasCols for RefreshToken {
    type Cols = RefreshTokenCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        RefreshTokenCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            user_id: __sdk::__query_builder::Col::new(table_name, "user_id"),
            jti: __sdk::__query_builder::Col::new(table_name, "jti"),
            token_hash: __sdk::__query_builder::Col::new(table_name, "token_hash"),
            expires_at: __sdk::__query_builder::Col::new(table_name, "expires_at"),
            revoked_at: __sdk::__query_builder::Col::new(table_name, "revoked_at"),
            replaced_by_jti: __sdk::__query_builder::Col::new(table_name, "replaced_by_jti"),
            ip: __sdk::__query_builder::Col::new(table_name, "ip"),
            user_agent: __sdk::__query_builder::Col::new(table_name, "user_agent"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
        }
    }
}

/// Indexed column accessor struct for the table `RefreshToken`.
///
/// Provides typed access to indexed columns for query building.
pub struct RefreshTokenIxCols {
    pub expires_at: __sdk::__query_builder::IxCol<RefreshToken, __sdk::Timestamp>,
    pub id: __sdk::__query_builder::IxCol<RefreshToken, u64>,
    pub jti: __sdk::__query_builder::IxCol<RefreshToken, String>,
    pub user_id: __sdk::__query_builder::IxCol<RefreshToken, u64>,
}

impl __sdk::__query_builder::HasIxCols for RefreshToken {
    type IxCols = RefreshTokenIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        RefreshTokenIxCols {
            expires_at: __sdk::__query_builder::IxCol::new(table_name, "expires_at"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            jti: __sdk::__query_builder::IxCol::new(table_name, "jti"),
            user_id: __sdk::__query_builder::IxCol::new(table_name, "user_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for RefreshToken {}
