// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RegenerateEdgeRegistrationCodeArgs {
    pub id: u64,
}

impl From<RegenerateEdgeRegistrationCodeArgs> for super::Reducer {
    fn from(args: RegenerateEdgeRegistrationCodeArgs) -> Self {
        Self::RegenerateEdgeRegistrationCode { id: args.id }
    }
}

impl __sdk::InModule for RegenerateEdgeRegistrationCodeArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `regenerate_edge_registration_code`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait regenerate_edge_registration_code {
    /// Request that the remote module invoke the reducer `regenerate_edge_registration_code` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`regenerate_edge_registration_code:regenerate_edge_registration_code_then`] to run a callback after the reducer completes.
    fn regenerate_edge_registration_code(&self, id: u64) -> __sdk::Result<()> {
        self.regenerate_edge_registration_code_then(id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `regenerate_edge_registration_code` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn regenerate_edge_registration_code_then(
        &self,
        id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl regenerate_edge_registration_code for super::RemoteReducers {
    fn regenerate_edge_registration_code_then(
        &self,
        id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(RegenerateEdgeRegistrationCodeArgs { id }, callback)
    }
}
