// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RegisterImageArgs {
    pub img_url: String,
    pub hash: String,
}

impl From<RegisterImageArgs> for super::Reducer {
    fn from(args: RegisterImageArgs) -> Self {
        Self::RegisterImage {
            img_url: args.img_url,
            hash: args.hash,
        }
    }
}

impl __sdk::InModule for RegisterImageArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `register_image`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait register_image {
    /// Request that the remote module invoke the reducer `register_image` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`register_image:register_image_then`] to run a callback after the reducer completes.
    fn register_image(&self, img_url: String, hash: String) -> __sdk::Result<()> {
        self.register_image_then(img_url, hash, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `register_image` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn register_image_then(
        &self,
        img_url: String,
        hash: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl register_image for super::RemoteReducers {
    fn register_image_then(
        &self,
        img_url: String,
        hash: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(RegisterImageArgs { img_url, hash }, callback)
    }
}
