// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct RentalTenantMeter {
    pub id: u64,
    pub customer_id: String,
    pub rental_tenant_id: u64,
    pub meter_id: u64,
    pub unit_price_scaled: Option<i64>,
    pub price_tip_scaled: Option<i64>,
    pub price_peak_scaled: Option<i64>,
    pub price_flat_scaled: Option<i64>,
    pub price_valley_scaled: Option<i64>,
    pub remark: Option<String>,
    pub created_at: __sdk::Timestamp,
    pub updated_at: Option<__sdk::Timestamp>,
}

impl __sdk::InModule for RentalTenantMeter {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `RentalTenantMeter`.
///
/// Provides typed access to columns for query building.
pub struct RentalTenantMeterCols {
    pub id: __sdk::__query_builder::Col<RentalTenantMeter, u64>,
    pub customer_id: __sdk::__query_builder::Col<RentalTenantMeter, String>,
    pub rental_tenant_id: __sdk::__query_builder::Col<RentalTenantMeter, u64>,
    pub meter_id: __sdk::__query_builder::Col<RentalTenantMeter, u64>,
    pub unit_price_scaled: __sdk::__query_builder::Col<RentalTenantMeter, Option<i64>>,
    pub price_tip_scaled: __sdk::__query_builder::Col<RentalTenantMeter, Option<i64>>,
    pub price_peak_scaled: __sdk::__query_builder::Col<RentalTenantMeter, Option<i64>>,
    pub price_flat_scaled: __sdk::__query_builder::Col<RentalTenantMeter, Option<i64>>,
    pub price_valley_scaled: __sdk::__query_builder::Col<RentalTenantMeter, Option<i64>>,
    pub remark: __sdk::__query_builder::Col<RentalTenantMeter, Option<String>>,
    pub created_at: __sdk::__query_builder::Col<RentalTenantMeter, __sdk::Timestamp>,
    pub updated_at: __sdk::__query_builder::Col<RentalTenantMeter, Option<__sdk::Timestamp>>,
}

impl __sdk::__query_builder::HasCols for RentalTenantMeter {
    type Cols = RentalTenantMeterCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        RentalTenantMeterCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            customer_id: __sdk::__query_builder::Col::new(table_name, "customer_id"),
            rental_tenant_id: __sdk::__query_builder::Col::new(table_name, "rental_tenant_id"),
            meter_id: __sdk::__query_builder::Col::new(table_name, "meter_id"),
            unit_price_scaled: __sdk::__query_builder::Col::new(table_name, "unit_price_scaled"),
            price_tip_scaled: __sdk::__query_builder::Col::new(table_name, "price_tip_scaled"),
            price_peak_scaled: __sdk::__query_builder::Col::new(table_name, "price_peak_scaled"),
            price_flat_scaled: __sdk::__query_builder::Col::new(table_name, "price_flat_scaled"),
            price_valley_scaled: __sdk::__query_builder::Col::new(
                table_name,
                "price_valley_scaled",
            ),
            remark: __sdk::__query_builder::Col::new(table_name, "remark"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
        }
    }
}

/// Indexed column accessor struct for the table `RentalTenantMeter`.
///
/// Provides typed access to indexed columns for query building.
pub struct RentalTenantMeterIxCols {
    pub customer_id: __sdk::__query_builder::IxCol<RentalTenantMeter, String>,
    pub id: __sdk::__query_builder::IxCol<RentalTenantMeter, u64>,
    pub meter_id: __sdk::__query_builder::IxCol<RentalTenantMeter, u64>,
    pub rental_tenant_id: __sdk::__query_builder::IxCol<RentalTenantMeter, u64>,
}

impl __sdk::__query_builder::HasIxCols for RentalTenantMeter {
    type IxCols = RentalTenantMeterIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        RentalTenantMeterIxCols {
            customer_id: __sdk::__query_builder::IxCol::new(table_name, "customer_id"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            meter_id: __sdk::__query_builder::IxCol::new(table_name, "meter_id"),
            rental_tenant_id: __sdk::__query_builder::IxCol::new(table_name, "rental_tenant_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for RentalTenantMeter {}
