// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct RentalTenantMeterInput {
    pub meter_id: u64,
    pub unit_price_scaled: Option<i64>,
    pub price_tip_scaled: Option<i64>,
    pub price_peak_scaled: Option<i64>,
    pub price_flat_scaled: Option<i64>,
    pub price_valley_scaled: Option<i64>,
    pub remark: Option<String>,
}

impl __sdk::InModule for RentalTenantMeterInput {
    type Module = super::RemoteModule;
}
