// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RequestVipMembershipRefundArgs {
    pub out_refund_no: String,
    pub out_trade_no: String,
    pub refund_amount: u64,
    pub reason: Option<String>,
    pub channel: Option<String>,
}

impl From<RequestVipMembershipRefundArgs> for super::Reducer {
    fn from(args: RequestVipMembershipRefundArgs) -> Self {
        Self::RequestVipMembershipRefund {
            out_refund_no: args.out_refund_no,
            out_trade_no: args.out_trade_no,
            refund_amount: args.refund_amount,
            reason: args.reason,
            channel: args.channel,
        }
    }
}

impl __sdk::InModule for RequestVipMembershipRefundArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `request_vip_membership_refund`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait request_vip_membership_refund {
    /// Request that the remote module invoke the reducer `request_vip_membership_refund` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`request_vip_membership_refund:request_vip_membership_refund_then`] to run a callback after the reducer completes.
    fn request_vip_membership_refund(
        &self,
        out_refund_no: String,
        out_trade_no: String,
        refund_amount: u64,
        reason: Option<String>,
        channel: Option<String>,
    ) -> __sdk::Result<()> {
        self.request_vip_membership_refund_then(
            out_refund_no,
            out_trade_no,
            refund_amount,
            reason,
            channel,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `request_vip_membership_refund` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn request_vip_membership_refund_then(
        &self,
        out_refund_no: String,
        out_trade_no: String,
        refund_amount: u64,
        reason: Option<String>,
        channel: Option<String>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl request_vip_membership_refund for super::RemoteReducers {
    fn request_vip_membership_refund_then(
        &self,
        out_refund_no: String,
        out_trade_no: String,
        refund_amount: u64,
        reason: Option<String>,
        channel: Option<String>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            RequestVipMembershipRefundArgs {
                out_refund_no,
                out_trade_no,
                refund_amount,
                reason,
                channel,
            },
            callback,
        )
    }
}
