// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct RoleCode {
    pub id: u64,
    pub customer_id: String,
    pub role_id: u64,
    pub code_id: u64,
    pub created_at: __sdk::Timestamp,
    pub updated_at: Option<__sdk::Timestamp>,
}

impl __sdk::InModule for RoleCode {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `RoleCode`.
///
/// Provides typed access to columns for query building.
pub struct RoleCodeCols {
    pub id: __sdk::__query_builder::Col<RoleCode, u64>,
    pub customer_id: __sdk::__query_builder::Col<RoleCode, String>,
    pub role_id: __sdk::__query_builder::Col<RoleCode, u64>,
    pub code_id: __sdk::__query_builder::Col<RoleCode, u64>,
    pub created_at: __sdk::__query_builder::Col<RoleCode, __sdk::Timestamp>,
    pub updated_at: __sdk::__query_builder::Col<RoleCode, Option<__sdk::Timestamp>>,
}

impl __sdk::__query_builder::HasCols for RoleCode {
    type Cols = RoleCodeCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        RoleCodeCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            customer_id: __sdk::__query_builder::Col::new(table_name, "customer_id"),
            role_id: __sdk::__query_builder::Col::new(table_name, "role_id"),
            code_id: __sdk::__query_builder::Col::new(table_name, "code_id"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
        }
    }
}

/// Indexed column accessor struct for the table `RoleCode`.
///
/// Provides typed access to indexed columns for query building.
pub struct RoleCodeIxCols {
    pub code_id: __sdk::__query_builder::IxCol<RoleCode, u64>,
    pub customer_id: __sdk::__query_builder::IxCol<RoleCode, String>,
    pub id: __sdk::__query_builder::IxCol<RoleCode, u64>,
    pub role_id: __sdk::__query_builder::IxCol<RoleCode, u64>,
}

impl __sdk::__query_builder::HasIxCols for RoleCode {
    type IxCols = RoleCodeIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        RoleCodeIxCols {
            code_id: __sdk::__query_builder::IxCol::new(table_name, "code_id"),
            customer_id: __sdk::__query_builder::IxCol::new(table_name, "customer_id"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            role_id: __sdk::__query_builder::IxCol::new(table_name, "role_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for RoleCode {}
