// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Salary {
    pub salary_id: u64,
    pub customer_id: String,
    pub employee_id: u64,
    pub salary_amount_cents: Option<i64>,
    pub issue_date: Option<__sdk::Timestamp>,
    pub issued: Option<bool>,
    pub remark: Option<String>,
    pub is_deleted: bool,
    pub created_at: __sdk::Timestamp,
    pub updated_at: Option<__sdk::Timestamp>,
}

impl __sdk::InModule for Salary {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Salary`.
///
/// Provides typed access to columns for query building.
pub struct SalaryCols {
    pub salary_id: __sdk::__query_builder::Col<Salary, u64>,
    pub customer_id: __sdk::__query_builder::Col<Salary, String>,
    pub employee_id: __sdk::__query_builder::Col<Salary, u64>,
    pub salary_amount_cents: __sdk::__query_builder::Col<Salary, Option<i64>>,
    pub issue_date: __sdk::__query_builder::Col<Salary, Option<__sdk::Timestamp>>,
    pub issued: __sdk::__query_builder::Col<Salary, Option<bool>>,
    pub remark: __sdk::__query_builder::Col<Salary, Option<String>>,
    pub is_deleted: __sdk::__query_builder::Col<Salary, bool>,
    pub created_at: __sdk::__query_builder::Col<Salary, __sdk::Timestamp>,
    pub updated_at: __sdk::__query_builder::Col<Salary, Option<__sdk::Timestamp>>,
}

impl __sdk::__query_builder::HasCols for Salary {
    type Cols = SalaryCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SalaryCols {
            salary_id: __sdk::__query_builder::Col::new(table_name, "salary_id"),
            customer_id: __sdk::__query_builder::Col::new(table_name, "customer_id"),
            employee_id: __sdk::__query_builder::Col::new(table_name, "employee_id"),
            salary_amount_cents: __sdk::__query_builder::Col::new(
                table_name,
                "salary_amount_cents",
            ),
            issue_date: __sdk::__query_builder::Col::new(table_name, "issue_date"),
            issued: __sdk::__query_builder::Col::new(table_name, "issued"),
            remark: __sdk::__query_builder::Col::new(table_name, "remark"),
            is_deleted: __sdk::__query_builder::Col::new(table_name, "is_deleted"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
        }
    }
}

/// Indexed column accessor struct for the table `Salary`.
///
/// Provides typed access to indexed columns for query building.
pub struct SalaryIxCols {
    pub customer_id: __sdk::__query_builder::IxCol<Salary, String>,
    pub employee_id: __sdk::__query_builder::IxCol<Salary, u64>,
    pub salary_id: __sdk::__query_builder::IxCol<Salary, u64>,
}

impl __sdk::__query_builder::HasIxCols for Salary {
    type IxCols = SalaryIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        SalaryIxCols {
            customer_id: __sdk::__query_builder::IxCol::new(table_name, "customer_id"),
            employee_id: __sdk::__query_builder::IxCol::new(table_name, "employee_id"),
            salary_id: __sdk::__query_builder::IxCol::new(table_name, "salary_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Salary {}
