// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::sms_send_result_type::SmsSendResult;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
struct SendLoginSmsCodeArgs {
    pub phone_number: String,
}

impl __sdk::InModule for SendLoginSmsCodeArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the procedure `send_login_sms_code`.
///
/// Implemented for [`super::RemoteProcedures`].
pub trait send_login_sms_code {
    fn send_login_sms_code(&self, phone_number: String) {
        self.send_login_sms_code_then(phone_number, |_, _| {});
    }

    fn send_login_sms_code_then(
        &self,
        phone_number: String,

        __callback: impl FnOnce(&super::ProcedureEventContext, Result<SmsSendResult, __sdk::InternalError>)
            + Send
            + 'static,
    );
}

impl send_login_sms_code for super::RemoteProcedures {
    fn send_login_sms_code_then(
        &self,
        phone_number: String,

        __callback: impl FnOnce(&super::ProcedureEventContext, Result<SmsSendResult, __sdk::InternalError>)
            + Send
            + 'static,
    ) {
        self.imp.invoke_procedure_with_callback::<_, SmsSendResult>(
            "send_login_sms_code",
            SendLoginSmsCodeArgs { phone_number },
            __callback,
        );
    }
}
