// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetCarryoverDispositionArgs {
    pub item_id: u64,
    pub disposition: String,
}

impl From<SetCarryoverDispositionArgs> for super::Reducer {
    fn from(args: SetCarryoverDispositionArgs) -> Self {
        Self::SetCarryoverDisposition {
            item_id: args.item_id,
            disposition: args.disposition,
        }
    }
}

impl __sdk::InModule for SetCarryoverDispositionArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_carryover_disposition`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_carryover_disposition {
    /// Request that the remote module invoke the reducer `set_carryover_disposition` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`set_carryover_disposition:set_carryover_disposition_then`] to run a callback after the reducer completes.
    fn set_carryover_disposition(&self, item_id: u64, disposition: String) -> __sdk::Result<()> {
        self.set_carryover_disposition_then(item_id, disposition, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `set_carryover_disposition` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn set_carryover_disposition_then(
        &self,
        item_id: u64,
        disposition: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl set_carryover_disposition for super::RemoteReducers {
    fn set_carryover_disposition_then(
        &self,
        item_id: u64,
        disposition: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            SetCarryoverDispositionArgs {
                item_id,
                disposition,
            },
            callback,
        )
    }
}
