// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetAccessDoorStatusArgs {
    pub device_id: u64,
    pub status: i8,
}

impl From<SetAccessDoorStatusArgs> for super::Reducer {
    fn from(args: SetAccessDoorStatusArgs) -> Self {
        Self::SetAccessDoorStatus {
            device_id: args.device_id,
            status: args.status,
        }
    }
}

impl __sdk::InModule for SetAccessDoorStatusArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_access_door_status`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_access_door_status {
    /// Request that the remote module invoke the reducer `set_access_door_status` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`set_access_door_status:set_access_door_status_then`] to run a callback after the reducer completes.
    fn set_access_door_status(&self, device_id: u64, status: i8) -> __sdk::Result<()> {
        self.set_access_door_status_then(device_id, status, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `set_access_door_status` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn set_access_door_status_then(
        &self,
        device_id: u64,
        status: i8,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl set_access_door_status for super::RemoteReducers {
    fn set_access_door_status_then(
        &self,
        device_id: u64,
        status: i8,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(SetAccessDoorStatusArgs { device_id, status }, callback)
    }
}
