// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetNoticeValidityArgs {
    pub notice_id: String,
    pub is_valid: bool,
    pub invalid_reason: Option<String>,
}

impl From<SetNoticeValidityArgs> for super::Reducer {
    fn from(args: SetNoticeValidityArgs) -> Self {
        Self::SetNoticeValidity {
            notice_id: args.notice_id,
            is_valid: args.is_valid,
            invalid_reason: args.invalid_reason,
        }
    }
}

impl __sdk::InModule for SetNoticeValidityArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_notice_validity`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_notice_validity {
    /// Request that the remote module invoke the reducer `set_notice_validity` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`set_notice_validity:set_notice_validity_then`] to run a callback after the reducer completes.
    fn set_notice_validity(
        &self,
        notice_id: String,
        is_valid: bool,
        invalid_reason: Option<String>,
    ) -> __sdk::Result<()> {
        self.set_notice_validity_then(notice_id, is_valid, invalid_reason, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `set_notice_validity` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn set_notice_validity_then(
        &self,
        notice_id: String,
        is_valid: bool,
        invalid_reason: Option<String>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl set_notice_validity for super::RemoteReducers {
    fn set_notice_validity_then(
        &self,
        notice_id: String,
        is_valid: bool,
        invalid_reason: Option<String>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            SetNoticeValidityArgs {
                notice_id,
                is_valid,
                invalid_reason,
            },
            callback,
        )
    }
}
