// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::rental_tenant_dormitory_floor_input_type::RentalTenantDormitoryFloorInput;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetRentalTenantDormitoryFloorsArgs {
    pub rental_tenant_id: u64,
    pub floors: Vec<RentalTenantDormitoryFloorInput>,
}

impl From<SetRentalTenantDormitoryFloorsArgs> for super::Reducer {
    fn from(args: SetRentalTenantDormitoryFloorsArgs) -> Self {
        Self::SetRentalTenantDormitoryFloors {
            rental_tenant_id: args.rental_tenant_id,
            floors: args.floors,
        }
    }
}

impl __sdk::InModule for SetRentalTenantDormitoryFloorsArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_rental_tenant_dormitory_floors`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_rental_tenant_dormitory_floors {
    /// Request that the remote module invoke the reducer `set_rental_tenant_dormitory_floors` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`set_rental_tenant_dormitory_floors:set_rental_tenant_dormitory_floors_then`] to run a callback after the reducer completes.
    fn set_rental_tenant_dormitory_floors(
        &self,
        rental_tenant_id: u64,
        floors: Vec<RentalTenantDormitoryFloorInput>,
    ) -> __sdk::Result<()> {
        self.set_rental_tenant_dormitory_floors_then(rental_tenant_id, floors, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `set_rental_tenant_dormitory_floors` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn set_rental_tenant_dormitory_floors_then(
        &self,
        rental_tenant_id: u64,
        floors: Vec<RentalTenantDormitoryFloorInput>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl set_rental_tenant_dormitory_floors for super::RemoteReducers {
    fn set_rental_tenant_dormitory_floors_then(
        &self,
        rental_tenant_id: u64,
        floors: Vec<RentalTenantDormitoryFloorInput>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            SetRentalTenantDormitoryFloorsArgs {
                rental_tenant_id,
                floors,
            },
            callback,
        )
    }
}
