// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetSignalEventStatusArgs {
    pub event_id: u64,
    pub status: String,
}

impl From<SetSignalEventStatusArgs> for super::Reducer {
    fn from(args: SetSignalEventStatusArgs) -> Self {
        Self::SetSignalEventStatus {
            event_id: args.event_id,
            status: args.status,
        }
    }
}

impl __sdk::InModule for SetSignalEventStatusArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_signal_event_status`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_signal_event_status {
    /// Request that the remote module invoke the reducer `set_signal_event_status` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`set_signal_event_status:set_signal_event_status_then`] to run a callback after the reducer completes.
    fn set_signal_event_status(&self, event_id: u64, status: String) -> __sdk::Result<()> {
        self.set_signal_event_status_then(event_id, status, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `set_signal_event_status` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn set_signal_event_status_then(
        &self,
        event_id: u64,
        status: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl set_signal_event_status for super::RemoteReducers {
    fn set_signal_event_status_then(
        &self,
        event_id: u64,
        status: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(SetSignalEventStatusArgs { event_id, status }, callback)
    }
}
