// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct SignalEvidence {
    pub evidence_id: u64,
    pub customer_id: String,
    pub event_id: u64,
    pub evidence_type: String,
    pub source_title: Option<String>,
    pub source_link: String,
    pub raw_text: Option<String>,
    pub matched_keywords_json: Option<String>,
    pub matched_sentences_json: Option<String>,
    pub score_delta: i32,
    pub content_hash: String,
    pub published_at: Option<__sdk::Timestamp>,
    pub crawled_at: Option<__sdk::Timestamp>,
    pub is_deleted: bool,
    pub created_at: __sdk::Timestamp,
    pub updated_at: __sdk::Timestamp,
}

impl __sdk::InModule for SignalEvidence {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `SignalEvidence`.
///
/// Provides typed access to columns for query building.
pub struct SignalEvidenceCols {
    pub evidence_id: __sdk::__query_builder::Col<SignalEvidence, u64>,
    pub customer_id: __sdk::__query_builder::Col<SignalEvidence, String>,
    pub event_id: __sdk::__query_builder::Col<SignalEvidence, u64>,
    pub evidence_type: __sdk::__query_builder::Col<SignalEvidence, String>,
    pub source_title: __sdk::__query_builder::Col<SignalEvidence, Option<String>>,
    pub source_link: __sdk::__query_builder::Col<SignalEvidence, String>,
    pub raw_text: __sdk::__query_builder::Col<SignalEvidence, Option<String>>,
    pub matched_keywords_json: __sdk::__query_builder::Col<SignalEvidence, Option<String>>,
    pub matched_sentences_json: __sdk::__query_builder::Col<SignalEvidence, Option<String>>,
    pub score_delta: __sdk::__query_builder::Col<SignalEvidence, i32>,
    pub content_hash: __sdk::__query_builder::Col<SignalEvidence, String>,
    pub published_at: __sdk::__query_builder::Col<SignalEvidence, Option<__sdk::Timestamp>>,
    pub crawled_at: __sdk::__query_builder::Col<SignalEvidence, Option<__sdk::Timestamp>>,
    pub is_deleted: __sdk::__query_builder::Col<SignalEvidence, bool>,
    pub created_at: __sdk::__query_builder::Col<SignalEvidence, __sdk::Timestamp>,
    pub updated_at: __sdk::__query_builder::Col<SignalEvidence, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for SignalEvidence {
    type Cols = SignalEvidenceCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        SignalEvidenceCols {
            evidence_id: __sdk::__query_builder::Col::new(table_name, "evidence_id"),
            customer_id: __sdk::__query_builder::Col::new(table_name, "customer_id"),
            event_id: __sdk::__query_builder::Col::new(table_name, "event_id"),
            evidence_type: __sdk::__query_builder::Col::new(table_name, "evidence_type"),
            source_title: __sdk::__query_builder::Col::new(table_name, "source_title"),
            source_link: __sdk::__query_builder::Col::new(table_name, "source_link"),
            raw_text: __sdk::__query_builder::Col::new(table_name, "raw_text"),
            matched_keywords_json: __sdk::__query_builder::Col::new(
                table_name,
                "matched_keywords_json",
            ),
            matched_sentences_json: __sdk::__query_builder::Col::new(
                table_name,
                "matched_sentences_json",
            ),
            score_delta: __sdk::__query_builder::Col::new(table_name, "score_delta"),
            content_hash: __sdk::__query_builder::Col::new(table_name, "content_hash"),
            published_at: __sdk::__query_builder::Col::new(table_name, "published_at"),
            crawled_at: __sdk::__query_builder::Col::new(table_name, "crawled_at"),
            is_deleted: __sdk::__query_builder::Col::new(table_name, "is_deleted"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
        }
    }
}

/// Indexed column accessor struct for the table `SignalEvidence`.
///
/// Provides typed access to indexed columns for query building.
pub struct SignalEvidenceIxCols {
    pub content_hash: __sdk::__query_builder::IxCol<SignalEvidence, String>,
    pub customer_id: __sdk::__query_builder::IxCol<SignalEvidence, String>,
    pub event_id: __sdk::__query_builder::IxCol<SignalEvidence, u64>,
    pub evidence_id: __sdk::__query_builder::IxCol<SignalEvidence, u64>,
}

impl __sdk::__query_builder::HasIxCols for SignalEvidence {
    type IxCols = SignalEvidenceIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        SignalEvidenceIxCols {
            content_hash: __sdk::__query_builder::IxCol::new(table_name, "content_hash"),
            customer_id: __sdk::__query_builder::IxCol::new(table_name, "customer_id"),
            event_id: __sdk::__query_builder::IxCol::new(table_name, "event_id"),
            evidence_id: __sdk::__query_builder::IxCol::new(table_name, "evidence_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for SignalEvidence {}
