// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SkipCrawlerTaskItemArgs {
    pub item_id: u64,
    pub reason: String,
}

impl From<SkipCrawlerTaskItemArgs> for super::Reducer {
    fn from(args: SkipCrawlerTaskItemArgs) -> Self {
        Self::SkipCrawlerTaskItem {
            item_id: args.item_id,
            reason: args.reason,
        }
    }
}

impl __sdk::InModule for SkipCrawlerTaskItemArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `skip_crawler_task_item`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait skip_crawler_task_item {
    /// Request that the remote module invoke the reducer `skip_crawler_task_item` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`skip_crawler_task_item:skip_crawler_task_item_then`] to run a callback after the reducer completes.
    fn skip_crawler_task_item(&self, item_id: u64, reason: String) -> __sdk::Result<()> {
        self.skip_crawler_task_item_then(item_id, reason, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `skip_crawler_task_item` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn skip_crawler_task_item_then(
        &self,
        item_id: u64,
        reason: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl skip_crawler_task_item for super::RemoteReducers {
    fn skip_crawler_task_item_then(
        &self,
        item_id: u64,
        reason: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(SkipCrawlerTaskItemArgs { item_id, reason }, callback)
    }
}
