// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SyncTenantProfilesFromContractsArgs {}

impl From<SyncTenantProfilesFromContractsArgs> for super::Reducer {
    fn from(args: SyncTenantProfilesFromContractsArgs) -> Self {
        Self::SyncTenantProfilesFromContracts
    }
}

impl __sdk::InModule for SyncTenantProfilesFromContractsArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `sync_tenant_profiles_from_contracts`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait sync_tenant_profiles_from_contracts {
    /// Request that the remote module invoke the reducer `sync_tenant_profiles_from_contracts` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`sync_tenant_profiles_from_contracts:sync_tenant_profiles_from_contracts_then`] to run a callback after the reducer completes.
    fn sync_tenant_profiles_from_contracts(&self) -> __sdk::Result<()> {
        self.sync_tenant_profiles_from_contracts_then(|_, _| {})
    }

    /// Request that the remote module invoke the reducer `sync_tenant_profiles_from_contracts` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn sync_tenant_profiles_from_contracts_then(
        &self,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl sync_tenant_profiles_from_contracts for super::RemoteReducers {
    fn sync_tenant_profiles_from_contracts_then(
        &self,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(SyncTenantProfilesFromContractsArgs {}, callback)
    }
}
