// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct TenantProvisioningJobInput {
    pub target_customer_id: Option<String>,
    pub target_city: Option<String>,
    pub target_company_short_name: Option<String>,
    pub target_db_name: Option<String>,
    pub last_payment_out_trade_no: Option<String>,
}

impl __sdk::InModule for TenantProvisioningJobInput {
    type Module = super::RemoteModule;
}
