// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct TenantInvitationJoinLog {
    pub id: u64,
    pub invitation_id: u64,
    pub code: String,
    pub customer_id: String,
    pub center_user_id: u64,
    pub customer_user_id: Option<u64>,
    pub previous_customer_id: Option<String>,
    pub status: String,
    pub error_message: Option<String>,
    pub joined_at: Option<__sdk::Timestamp>,
    pub created_at: __sdk::Timestamp,
    pub updated_at: Option<__sdk::Timestamp>,
}

impl __sdk::InModule for TenantInvitationJoinLog {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `TenantInvitationJoinLog`.
///
/// Provides typed access to columns for query building.
pub struct TenantInvitationJoinLogCols {
    pub id: __sdk::__query_builder::Col<TenantInvitationJoinLog, u64>,
    pub invitation_id: __sdk::__query_builder::Col<TenantInvitationJoinLog, u64>,
    pub code: __sdk::__query_builder::Col<TenantInvitationJoinLog, String>,
    pub customer_id: __sdk::__query_builder::Col<TenantInvitationJoinLog, String>,
    pub center_user_id: __sdk::__query_builder::Col<TenantInvitationJoinLog, u64>,
    pub customer_user_id: __sdk::__query_builder::Col<TenantInvitationJoinLog, Option<u64>>,
    pub previous_customer_id: __sdk::__query_builder::Col<TenantInvitationJoinLog, Option<String>>,
    pub status: __sdk::__query_builder::Col<TenantInvitationJoinLog, String>,
    pub error_message: __sdk::__query_builder::Col<TenantInvitationJoinLog, Option<String>>,
    pub joined_at: __sdk::__query_builder::Col<TenantInvitationJoinLog, Option<__sdk::Timestamp>>,
    pub created_at: __sdk::__query_builder::Col<TenantInvitationJoinLog, __sdk::Timestamp>,
    pub updated_at: __sdk::__query_builder::Col<TenantInvitationJoinLog, Option<__sdk::Timestamp>>,
}

impl __sdk::__query_builder::HasCols for TenantInvitationJoinLog {
    type Cols = TenantInvitationJoinLogCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        TenantInvitationJoinLogCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            invitation_id: __sdk::__query_builder::Col::new(table_name, "invitation_id"),
            code: __sdk::__query_builder::Col::new(table_name, "code"),
            customer_id: __sdk::__query_builder::Col::new(table_name, "customer_id"),
            center_user_id: __sdk::__query_builder::Col::new(table_name, "center_user_id"),
            customer_user_id: __sdk::__query_builder::Col::new(table_name, "customer_user_id"),
            previous_customer_id: __sdk::__query_builder::Col::new(
                table_name,
                "previous_customer_id",
            ),
            status: __sdk::__query_builder::Col::new(table_name, "status"),
            error_message: __sdk::__query_builder::Col::new(table_name, "error_message"),
            joined_at: __sdk::__query_builder::Col::new(table_name, "joined_at"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
        }
    }
}

/// Indexed column accessor struct for the table `TenantInvitationJoinLog`.
///
/// Provides typed access to indexed columns for query building.
pub struct TenantInvitationJoinLogIxCols {
    pub center_user_id: __sdk::__query_builder::IxCol<TenantInvitationJoinLog, u64>,
    pub customer_id: __sdk::__query_builder::IxCol<TenantInvitationJoinLog, String>,
    pub id: __sdk::__query_builder::IxCol<TenantInvitationJoinLog, u64>,
    pub invitation_id: __sdk::__query_builder::IxCol<TenantInvitationJoinLog, u64>,
    pub status: __sdk::__query_builder::IxCol<TenantInvitationJoinLog, String>,
}

impl __sdk::__query_builder::HasIxCols for TenantInvitationJoinLog {
    type IxCols = TenantInvitationJoinLogIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        TenantInvitationJoinLogIxCols {
            center_user_id: __sdk::__query_builder::IxCol::new(table_name, "center_user_id"),
            customer_id: __sdk::__query_builder::IxCol::new(table_name, "customer_id"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            invitation_id: __sdk::__query_builder::IxCol::new(table_name, "invitation_id"),
            status: __sdk::__query_builder::IxCol::new(table_name, "status"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for TenantInvitationJoinLog {}
