// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct TenantInvitation {
    pub id: u64,
    pub code: String,
    pub customer_id: String,
    pub created_by_center_user_id: u64,
    pub role_ids: Vec<u64>,
    pub max_uses: Option<u32>,
    pub used_count: u32,
    pub expires_at: Option<__sdk::Timestamp>,
    pub status: String,
    pub remark: Option<String>,
    pub created_at: __sdk::Timestamp,
    pub updated_at: Option<__sdk::Timestamp>,
}

impl __sdk::InModule for TenantInvitation {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `TenantInvitation`.
///
/// Provides typed access to columns for query building.
pub struct TenantInvitationCols {
    pub id: __sdk::__query_builder::Col<TenantInvitation, u64>,
    pub code: __sdk::__query_builder::Col<TenantInvitation, String>,
    pub customer_id: __sdk::__query_builder::Col<TenantInvitation, String>,
    pub created_by_center_user_id: __sdk::__query_builder::Col<TenantInvitation, u64>,
    pub role_ids: __sdk::__query_builder::Col<TenantInvitation, Vec<u64>>,
    pub max_uses: __sdk::__query_builder::Col<TenantInvitation, Option<u32>>,
    pub used_count: __sdk::__query_builder::Col<TenantInvitation, u32>,
    pub expires_at: __sdk::__query_builder::Col<TenantInvitation, Option<__sdk::Timestamp>>,
    pub status: __sdk::__query_builder::Col<TenantInvitation, String>,
    pub remark: __sdk::__query_builder::Col<TenantInvitation, Option<String>>,
    pub created_at: __sdk::__query_builder::Col<TenantInvitation, __sdk::Timestamp>,
    pub updated_at: __sdk::__query_builder::Col<TenantInvitation, Option<__sdk::Timestamp>>,
}

impl __sdk::__query_builder::HasCols for TenantInvitation {
    type Cols = TenantInvitationCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        TenantInvitationCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            code: __sdk::__query_builder::Col::new(table_name, "code"),
            customer_id: __sdk::__query_builder::Col::new(table_name, "customer_id"),
            created_by_center_user_id: __sdk::__query_builder::Col::new(
                table_name,
                "created_by_center_user_id",
            ),
            role_ids: __sdk::__query_builder::Col::new(table_name, "role_ids"),
            max_uses: __sdk::__query_builder::Col::new(table_name, "max_uses"),
            used_count: __sdk::__query_builder::Col::new(table_name, "used_count"),
            expires_at: __sdk::__query_builder::Col::new(table_name, "expires_at"),
            status: __sdk::__query_builder::Col::new(table_name, "status"),
            remark: __sdk::__query_builder::Col::new(table_name, "remark"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
        }
    }
}

/// Indexed column accessor struct for the table `TenantInvitation`.
///
/// Provides typed access to indexed columns for query building.
pub struct TenantInvitationIxCols {
    pub code: __sdk::__query_builder::IxCol<TenantInvitation, String>,
    pub created_by_center_user_id: __sdk::__query_builder::IxCol<TenantInvitation, u64>,
    pub customer_id: __sdk::__query_builder::IxCol<TenantInvitation, String>,
    pub expires_at: __sdk::__query_builder::IxCol<TenantInvitation, Option<__sdk::Timestamp>>,
    pub id: __sdk::__query_builder::IxCol<TenantInvitation, u64>,
}

impl __sdk::__query_builder::HasIxCols for TenantInvitation {
    type IxCols = TenantInvitationIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        TenantInvitationIxCols {
            code: __sdk::__query_builder::IxCol::new(table_name, "code"),
            created_by_center_user_id: __sdk::__query_builder::IxCol::new(
                table_name,
                "created_by_center_user_id",
            ),
            customer_id: __sdk::__query_builder::IxCol::new(table_name, "customer_id"),
            expires_at: __sdk::__query_builder::IxCol::new(table_name, "expires_at"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for TenantInvitation {}
