// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UnbindImageFromFactoryFloorArgs {
    pub floor_id: u64,
    pub img_id: u64,
}

impl From<UnbindImageFromFactoryFloorArgs> for super::Reducer {
    fn from(args: UnbindImageFromFactoryFloorArgs) -> Self {
        Self::UnbindImageFromFactoryFloor {
            floor_id: args.floor_id,
            img_id: args.img_id,
        }
    }
}

impl __sdk::InModule for UnbindImageFromFactoryFloorArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `unbind_image_from_factory_floor`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait unbind_image_from_factory_floor {
    /// Request that the remote module invoke the reducer `unbind_image_from_factory_floor` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`unbind_image_from_factory_floor:unbind_image_from_factory_floor_then`] to run a callback after the reducer completes.
    fn unbind_image_from_factory_floor(&self, floor_id: u64, img_id: u64) -> __sdk::Result<()> {
        self.unbind_image_from_factory_floor_then(floor_id, img_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `unbind_image_from_factory_floor` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn unbind_image_from_factory_floor_then(
        &self,
        floor_id: u64,
        img_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl unbind_image_from_factory_floor for super::RemoteReducers {
    fn unbind_image_from_factory_floor_then(
        &self,
        floor_id: u64,
        img_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            UnbindImageFromFactoryFloorArgs { floor_id, img_id },
            callback,
        )
    }
}
