// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::factory_input_type::FactoryInput;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdateFactoryArgs {
    pub factory_id: u64,
    pub input: FactoryInput,
}

impl From<UpdateFactoryArgs> for super::Reducer {
    fn from(args: UpdateFactoryArgs) -> Self {
        Self::UpdateFactory {
            factory_id: args.factory_id,
            input: args.input,
        }
    }
}

impl __sdk::InModule for UpdateFactoryArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_factory`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_factory {
    /// Request that the remote module invoke the reducer `update_factory` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`update_factory:update_factory_then`] to run a callback after the reducer completes.
    fn update_factory(&self, factory_id: u64, input: FactoryInput) -> __sdk::Result<()> {
        self.update_factory_then(factory_id, input, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `update_factory` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn update_factory_then(
        &self,
        factory_id: u64,
        input: FactoryInput,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl update_factory for super::RemoteReducers {
    fn update_factory_then(
        &self,
        factory_id: u64,
        input: FactoryInput,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(UpdateFactoryArgs { factory_id, input }, callback)
    }
}
