// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::hygiene_check_input_type::HygieneCheckInput;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdateHygieneCheckArgs {
    pub id: u64,
    pub input: HygieneCheckInput,
}

impl From<UpdateHygieneCheckArgs> for super::Reducer {
    fn from(args: UpdateHygieneCheckArgs) -> Self {
        Self::UpdateHygieneCheck {
            id: args.id,
            input: args.input,
        }
    }
}

impl __sdk::InModule for UpdateHygieneCheckArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_hygiene_check`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_hygiene_check {
    /// Request that the remote module invoke the reducer `update_hygiene_check` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`update_hygiene_check:update_hygiene_check_then`] to run a callback after the reducer completes.
    fn update_hygiene_check(&self, id: u64, input: HygieneCheckInput) -> __sdk::Result<()> {
        self.update_hygiene_check_then(id, input, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `update_hygiene_check` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn update_hygiene_check_then(
        &self,
        id: u64,
        input: HygieneCheckInput,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl update_hygiene_check for super::RemoteReducers {
    fn update_hygiene_check_then(
        &self,
        id: u64,
        input: HygieneCheckInput,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(UpdateHygieneCheckArgs { id, input }, callback)
    }
}
