// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::center_app_version_input_type::CenterAppVersionInput;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdateCenterAppVersionArgs {
    pub id: u64,
    pub input: CenterAppVersionInput,
}

impl From<UpdateCenterAppVersionArgs> for super::Reducer {
    fn from(args: UpdateCenterAppVersionArgs) -> Self {
        Self::UpdateCenterAppVersion {
            id: args.id,
            input: args.input,
        }
    }
}

impl __sdk::InModule for UpdateCenterAppVersionArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_center_app_version`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_center_app_version {
    /// Request that the remote module invoke the reducer `update_center_app_version` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`update_center_app_version:update_center_app_version_then`] to run a callback after the reducer completes.
    fn update_center_app_version(
        &self,
        id: u64,
        input: CenterAppVersionInput,
    ) -> __sdk::Result<()> {
        self.update_center_app_version_then(id, input, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `update_center_app_version` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn update_center_app_version_then(
        &self,
        id: u64,
        input: CenterAppVersionInput,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl update_center_app_version for super::RemoteReducers {
    fn update_center_app_version_then(
        &self,
        id: u64,
        input: CenterAppVersionInput,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(UpdateCenterAppVersionArgs { id, input }, callback)
    }
}
