// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::factory_maintenance_input_type::FactoryMaintenanceInput;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdateFactoryMaintenanceArgs {
    pub id: u64,
    pub input: FactoryMaintenanceInput,
}

impl From<UpdateFactoryMaintenanceArgs> for super::Reducer {
    fn from(args: UpdateFactoryMaintenanceArgs) -> Self {
        Self::UpdateFactoryMaintenance {
            id: args.id,
            input: args.input,
        }
    }
}

impl __sdk::InModule for UpdateFactoryMaintenanceArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_factory_maintenance`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_factory_maintenance {
    /// Request that the remote module invoke the reducer `update_factory_maintenance` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`update_factory_maintenance:update_factory_maintenance_then`] to run a callback after the reducer completes.
    fn update_factory_maintenance(
        &self,
        id: u64,
        input: FactoryMaintenanceInput,
    ) -> __sdk::Result<()> {
        self.update_factory_maintenance_then(id, input, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `update_factory_maintenance` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn update_factory_maintenance_then(
        &self,
        id: u64,
        input: FactoryMaintenanceInput,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl update_factory_maintenance for super::RemoteReducers {
    fn update_factory_maintenance_then(
        &self,
        id: u64,
        input: FactoryMaintenanceInput,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(UpdateFactoryMaintenanceArgs { id, input }, callback)
    }
}
