// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::finance_input_type::FinanceInput;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdateFinanceArgs {
    pub finance_id: u64,
    pub input: FinanceInput,
}

impl From<UpdateFinanceArgs> for super::Reducer {
    fn from(args: UpdateFinanceArgs) -> Self {
        Self::UpdateFinance {
            finance_id: args.finance_id,
            input: args.input,
        }
    }
}

impl __sdk::InModule for UpdateFinanceArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_finance`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_finance {
    /// Request that the remote module invoke the reducer `update_finance` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`update_finance:update_finance_then`] to run a callback after the reducer completes.
    fn update_finance(&self, finance_id: u64, input: FinanceInput) -> __sdk::Result<()> {
        self.update_finance_then(finance_id, input, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `update_finance` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn update_finance_then(
        &self,
        finance_id: u64,
        input: FinanceInput,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl update_finance for super::RemoteReducers {
    fn update_finance_then(
        &self,
        finance_id: u64,
        input: FinanceInput,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(UpdateFinanceArgs { finance_id, input }, callback)
    }
}
