// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::uploaded_avatar_input_type::UploadedAvatarInput;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdateMyAvatarArgs {
    pub upload: UploadedAvatarInput,
}

impl From<UpdateMyAvatarArgs> for super::Reducer {
    fn from(args: UpdateMyAvatarArgs) -> Self {
        Self::UpdateMyAvatar {
            upload: args.upload,
        }
    }
}

impl __sdk::InModule for UpdateMyAvatarArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_my_avatar`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_my_avatar {
    /// Request that the remote module invoke the reducer `update_my_avatar` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`update_my_avatar:update_my_avatar_then`] to run a callback after the reducer completes.
    fn update_my_avatar(&self, upload: UploadedAvatarInput) -> __sdk::Result<()> {
        self.update_my_avatar_then(upload, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `update_my_avatar` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn update_my_avatar_then(
        &self,
        upload: UploadedAvatarInput,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl update_my_avatar for super::RemoteReducers {
    fn update_my_avatar_then(
        &self,
        upload: UploadedAvatarInput,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(UpdateMyAvatarArgs { upload }, callback)
    }
}
