// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::investment_input_type::InvestmentInput;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdateInvestmentArgs {
    pub investment_id: u64,
    pub input: InvestmentInput,
}

impl From<UpdateInvestmentArgs> for super::Reducer {
    fn from(args: UpdateInvestmentArgs) -> Self {
        Self::UpdateInvestment {
            investment_id: args.investment_id,
            input: args.input,
        }
    }
}

impl __sdk::InModule for UpdateInvestmentArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_investment`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_investment {
    /// Request that the remote module invoke the reducer `update_investment` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`update_investment:update_investment_then`] to run a callback after the reducer completes.
    fn update_investment(&self, investment_id: u64, input: InvestmentInput) -> __sdk::Result<()> {
        self.update_investment_then(investment_id, input, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `update_investment` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn update_investment_then(
        &self,
        investment_id: u64,
        input: InvestmentInput,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl update_investment for super::RemoteReducers {
    fn update_investment_then(
        &self,
        investment_id: u64,
        input: InvestmentInput,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            UpdateInvestmentArgs {
                investment_id,
                input,
            },
            callback,
        )
    }
}
