// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::factory_floor_input_type::FactoryFloorInput;
use super::uploaded_floor_image_input_type::UploadedFloorImageInput;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdateFactoryFloorWithImagesArgs {
    pub floor_id: u64,
    pub input: FactoryFloorInput,
    pub existing_image_ids: Vec<u64>,
    pub uploads: Vec<UploadedFloorImageInput>,
}

impl From<UpdateFactoryFloorWithImagesArgs> for super::Reducer {
    fn from(args: UpdateFactoryFloorWithImagesArgs) -> Self {
        Self::UpdateFactoryFloorWithImages {
            floor_id: args.floor_id,
            input: args.input,
            existing_image_ids: args.existing_image_ids,
            uploads: args.uploads,
        }
    }
}

impl __sdk::InModule for UpdateFactoryFloorWithImagesArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_factory_floor_with_images`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_factory_floor_with_images {
    /// Request that the remote module invoke the reducer `update_factory_floor_with_images` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`update_factory_floor_with_images:update_factory_floor_with_images_then`] to run a callback after the reducer completes.
    fn update_factory_floor_with_images(
        &self,
        floor_id: u64,
        input: FactoryFloorInput,
        existing_image_ids: Vec<u64>,
        uploads: Vec<UploadedFloorImageInput>,
    ) -> __sdk::Result<()> {
        self.update_factory_floor_with_images_then(
            floor_id,
            input,
            existing_image_ids,
            uploads,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `update_factory_floor_with_images` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn update_factory_floor_with_images_then(
        &self,
        floor_id: u64,
        input: FactoryFloorInput,
        existing_image_ids: Vec<u64>,
        uploads: Vec<UploadedFloorImageInput>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl update_factory_floor_with_images for super::RemoteReducers {
    fn update_factory_floor_with_images_then(
        &self,
        floor_id: u64,
        input: FactoryFloorInput,
        existing_image_ids: Vec<u64>,
        uploads: Vec<UploadedFloorImageInput>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            UpdateFactoryFloorWithImagesArgs {
                floor_id,
                input,
                existing_image_ids,
                uploads,
            },
            callback,
        )
    }
}
