// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::investment_tenant_input_type::InvestmentTenantInput;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdateInvestmentTenantArgs {
    pub tenant_id: u64,
    pub input: InvestmentTenantInput,
}

impl From<UpdateInvestmentTenantArgs> for super::Reducer {
    fn from(args: UpdateInvestmentTenantArgs) -> Self {
        Self::UpdateInvestmentTenant {
            tenant_id: args.tenant_id,
            input: args.input,
        }
    }
}

impl __sdk::InModule for UpdateInvestmentTenantArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_investment_tenant`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_investment_tenant {
    /// Request that the remote module invoke the reducer `update_investment_tenant` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`update_investment_tenant:update_investment_tenant_then`] to run a callback after the reducer completes.
    fn update_investment_tenant(
        &self,
        tenant_id: u64,
        input: InvestmentTenantInput,
    ) -> __sdk::Result<()> {
        self.update_investment_tenant_then(tenant_id, input, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `update_investment_tenant` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn update_investment_tenant_then(
        &self,
        tenant_id: u64,
        input: InvestmentTenantInput,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl update_investment_tenant for super::RemoteReducers {
    fn update_investment_tenant_then(
        &self,
        tenant_id: u64,
        input: InvestmentTenantInput,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(UpdateInvestmentTenantArgs { tenant_id, input }, callback)
    }
}
