// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::finance_input_type::FinanceInput;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdateFinanceWithImagesArgs {
    pub finance_id: u64,
    pub input: FinanceInput,
    pub image_urls: Vec<String>,
}

impl From<UpdateFinanceWithImagesArgs> for super::Reducer {
    fn from(args: UpdateFinanceWithImagesArgs) -> Self {
        Self::UpdateFinanceWithImages {
            finance_id: args.finance_id,
            input: args.input,
            image_urls: args.image_urls,
        }
    }
}

impl __sdk::InModule for UpdateFinanceWithImagesArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_finance_with_images`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_finance_with_images {
    /// Request that the remote module invoke the reducer `update_finance_with_images` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`update_finance_with_images:update_finance_with_images_then`] to run a callback after the reducer completes.
    fn update_finance_with_images(
        &self,
        finance_id: u64,
        input: FinanceInput,
        image_urls: Vec<String>,
    ) -> __sdk::Result<()> {
        self.update_finance_with_images_then(finance_id, input, image_urls, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `update_finance_with_images` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn update_finance_with_images_then(
        &self,
        finance_id: u64,
        input: FinanceInput,
        image_urls: Vec<String>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl update_finance_with_images for super::RemoteReducers {
    fn update_finance_with_images_then(
        &self,
        finance_id: u64,
        input: FinanceInput,
        image_urls: Vec<String>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            UpdateFinanceWithImagesArgs {
                finance_id,
                input,
                image_urls,
            },
            callback,
        )
    }
}
