// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::factory_floor_input_type::FactoryFloorInput;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdateFactoryFloorArgs {
    pub floor_id: u64,
    pub input: FactoryFloorInput,
}

impl From<UpdateFactoryFloorArgs> for super::Reducer {
    fn from(args: UpdateFactoryFloorArgs) -> Self {
        Self::UpdateFactoryFloor {
            floor_id: args.floor_id,
            input: args.input,
        }
    }
}

impl __sdk::InModule for UpdateFactoryFloorArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_factory_floor`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_factory_floor {
    /// Request that the remote module invoke the reducer `update_factory_floor` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`update_factory_floor:update_factory_floor_then`] to run a callback after the reducer completes.
    fn update_factory_floor(&self, floor_id: u64, input: FactoryFloorInput) -> __sdk::Result<()> {
        self.update_factory_floor_then(floor_id, input, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `update_factory_floor` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn update_factory_floor_then(
        &self,
        floor_id: u64,
        input: FactoryFloorInput,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl update_factory_floor for super::RemoteReducers {
    fn update_factory_floor_then(
        &self,
        floor_id: u64,
        input: FactoryFloorInput,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(UpdateFactoryFloorArgs { floor_id, input }, callback)
    }
}
