// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::park_input_type::ParkInput;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdateParkArgs {
    pub park_id: u64,
    pub input: ParkInput,
}

impl From<UpdateParkArgs> for super::Reducer {
    fn from(args: UpdateParkArgs) -> Self {
        Self::UpdatePark {
            park_id: args.park_id,
            input: args.input,
        }
    }
}

impl __sdk::InModule for UpdateParkArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_park`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_park {
    /// Request that the remote module invoke the reducer `update_park` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`update_park:update_park_then`] to run a callback after the reducer completes.
    fn update_park(&self, park_id: u64, input: ParkInput) -> __sdk::Result<()> {
        self.update_park_then(park_id, input, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `update_park` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn update_park_then(
        &self,
        park_id: u64,
        input: ParkInput,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl update_park for super::RemoteReducers {
    fn update_park_then(
        &self,
        park_id: u64,
        input: ParkInput,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(UpdateParkArgs { park_id, input }, callback)
    }
}
