// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::transformer_asset_input_type::TransformerAssetInput;
use super::uploaded_maintenance_image_input_type::UploadedMaintenanceImageInput;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdateTransformerAssetArgs {
    pub id: u64,
    pub input: TransformerAssetInput,
    pub existing_image_ids: Vec<u64>,
    pub uploads: Vec<UploadedMaintenanceImageInput>,
}

impl From<UpdateTransformerAssetArgs> for super::Reducer {
    fn from(args: UpdateTransformerAssetArgs) -> Self {
        Self::UpdateTransformerAsset {
            id: args.id,
            input: args.input,
            existing_image_ids: args.existing_image_ids,
            uploads: args.uploads,
        }
    }
}

impl __sdk::InModule for UpdateTransformerAssetArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_transformer_asset`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_transformer_asset {
    /// Request that the remote module invoke the reducer `update_transformer_asset` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`update_transformer_asset:update_transformer_asset_then`] to run a callback after the reducer completes.
    fn update_transformer_asset(
        &self,
        id: u64,
        input: TransformerAssetInput,
        existing_image_ids: Vec<u64>,
        uploads: Vec<UploadedMaintenanceImageInput>,
    ) -> __sdk::Result<()> {
        self.update_transformer_asset_then(id, input, existing_image_ids, uploads, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `update_transformer_asset` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn update_transformer_asset_then(
        &self,
        id: u64,
        input: TransformerAssetInput,
        existing_image_ids: Vec<u64>,
        uploads: Vec<UploadedMaintenanceImageInput>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl update_transformer_asset for super::RemoteReducers {
    fn update_transformer_asset_then(
        &self,
        id: u64,
        input: TransformerAssetInput,
        existing_image_ids: Vec<u64>,
        uploads: Vec<UploadedMaintenanceImageInput>,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            UpdateTransformerAssetArgs {
                id,
                input,
                existing_image_ids,
                uploads,
            },
            callback,
        )
    }
}
