// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::dormitory_input_type::DormitoryInput;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdateDormitoryArgs {
    pub dormitory_id: u64,
    pub input: DormitoryInput,
}

impl From<UpdateDormitoryArgs> for super::Reducer {
    fn from(args: UpdateDormitoryArgs) -> Self {
        Self::UpdateDormitory {
            dormitory_id: args.dormitory_id,
            input: args.input,
        }
    }
}

impl __sdk::InModule for UpdateDormitoryArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_dormitory`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_dormitory {
    /// Request that the remote module invoke the reducer `update_dormitory` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`update_dormitory:update_dormitory_then`] to run a callback after the reducer completes.
    fn update_dormitory(&self, dormitory_id: u64, input: DormitoryInput) -> __sdk::Result<()> {
        self.update_dormitory_then(dormitory_id, input, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `update_dormitory` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn update_dormitory_then(
        &self,
        dormitory_id: u64,
        input: DormitoryInput,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl update_dormitory for super::RemoteReducers {
    fn update_dormitory_then(
        &self,
        dormitory_id: u64,
        input: DormitoryInput,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            UpdateDormitoryArgs {
                dormitory_id,
                input,
            },
            callback,
        )
    }
}
