// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct UserCredential {
    pub center_user_id: u64,
    pub password_hash: String,
    pub password_updated_at: __sdk::Timestamp,
    pub created_at: __sdk::Timestamp,
    pub updated_at: Option<__sdk::Timestamp>,
}

impl __sdk::InModule for UserCredential {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `UserCredential`.
///
/// Provides typed access to columns for query building.
pub struct UserCredentialCols {
    pub center_user_id: __sdk::__query_builder::Col<UserCredential, u64>,
    pub password_hash: __sdk::__query_builder::Col<UserCredential, String>,
    pub password_updated_at: __sdk::__query_builder::Col<UserCredential, __sdk::Timestamp>,
    pub created_at: __sdk::__query_builder::Col<UserCredential, __sdk::Timestamp>,
    pub updated_at: __sdk::__query_builder::Col<UserCredential, Option<__sdk::Timestamp>>,
}

impl __sdk::__query_builder::HasCols for UserCredential {
    type Cols = UserCredentialCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        UserCredentialCols {
            center_user_id: __sdk::__query_builder::Col::new(table_name, "center_user_id"),
            password_hash: __sdk::__query_builder::Col::new(table_name, "password_hash"),
            password_updated_at: __sdk::__query_builder::Col::new(
                table_name,
                "password_updated_at",
            ),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
        }
    }
}

/// Indexed column accessor struct for the table `UserCredential`.
///
/// Provides typed access to indexed columns for query building.
pub struct UserCredentialIxCols {
    pub center_user_id: __sdk::__query_builder::IxCol<UserCredential, u64>,
}

impl __sdk::__query_builder::HasIxCols for UserCredential {
    type IxCols = UserCredentialIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        UserCredentialIxCols {
            center_user_id: __sdk::__query_builder::IxCol::new(table_name, "center_user_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for UserCredential {}
