// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct UserRole {
    pub id: u64,
    pub user_id: u64,
    pub role_id: u64,
    pub created_at: __sdk::Timestamp,
    pub updated_at: Option<__sdk::Timestamp>,
}

impl __sdk::InModule for UserRole {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `UserRole`.
///
/// Provides typed access to columns for query building.
pub struct UserRoleCols {
    pub id: __sdk::__query_builder::Col<UserRole, u64>,
    pub user_id: __sdk::__query_builder::Col<UserRole, u64>,
    pub role_id: __sdk::__query_builder::Col<UserRole, u64>,
    pub created_at: __sdk::__query_builder::Col<UserRole, __sdk::Timestamp>,
    pub updated_at: __sdk::__query_builder::Col<UserRole, Option<__sdk::Timestamp>>,
}

impl __sdk::__query_builder::HasCols for UserRole {
    type Cols = UserRoleCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        UserRoleCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            user_id: __sdk::__query_builder::Col::new(table_name, "user_id"),
            role_id: __sdk::__query_builder::Col::new(table_name, "role_id"),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
        }
    }
}

/// Indexed column accessor struct for the table `UserRole`.
///
/// Provides typed access to indexed columns for query building.
pub struct UserRoleIxCols {
    pub id: __sdk::__query_builder::IxCol<UserRole, u64>,
    pub role_id: __sdk::__query_builder::IxCol<UserRole, u64>,
    pub user_id: __sdk::__query_builder::IxCol<UserRole, u64>,
}

impl __sdk::__query_builder::HasIxCols for UserRole {
    type IxCols = UserRoleIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        UserRoleIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            role_id: __sdk::__query_builder::IxCol::new(table_name, "role_id"),
            user_id: __sdk::__query_builder::IxCol::new(table_name, "user_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for UserRole {}
