// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct UtilityBillInput {
    pub meter_id: u64,
    pub tou_tier: Option<String>,
    pub meter_name: String,
    pub previous_reading_centi: i64,
    pub current_reading_centi: i64,
    pub monthly_usage_centi: i64,
    pub multiplier_centi: i64,
    pub total_usage_centi: i64,
    pub unit_price_scaled: i64,
    pub amount_cents: i64,
    pub remark: Option<String>,
    pub receipt_time: Option<__sdk::Timestamp>,
}

impl __sdk::InModule for UtilityBillInput {
    type Module = super::RemoteModule;
}
