// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::notice_type::Notice;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `valid_notices`.
///
/// Obtain a handle from the [`ValidNoticesTableAccess::valid_notices`] method on [`super::RemoteTables`],
/// like `ctx.db.valid_notices()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.valid_notices().on_insert(...)`.
pub struct ValidNoticesTableHandle<'ctx> {
    imp: __sdk::TableHandle<Notice>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `valid_notices`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ValidNoticesTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ValidNoticesTableHandle`], which mediates access to the table `valid_notices`.
    fn valid_notices(&self) -> ValidNoticesTableHandle<'_>;
}

impl ValidNoticesTableAccess for super::RemoteTables {
    fn valid_notices(&self) -> ValidNoticesTableHandle<'_> {
        ValidNoticesTableHandle {
            imp: self.imp.get_table::<Notice>("valid_notices"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ValidNoticesInsertCallbackId(__sdk::CallbackId);
pub struct ValidNoticesDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ValidNoticesTableHandle<'ctx> {
    type Row = Notice;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Notice> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ValidNoticesInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ValidNoticesInsertCallbackId {
        ValidNoticesInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ValidNoticesInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ValidNoticesDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ValidNoticesDeleteCallbackId {
        ValidNoticesDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ValidNoticesDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Notice>("valid_notices");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Notice>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Notice>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Notice`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait valid_noticesQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Notice`.
    fn valid_notices(&self) -> __sdk::__query_builder::Table<Notice>;
}

impl valid_noticesQueryTableAccess for __sdk::QueryTableAccessor {
    fn valid_notices(&self) -> __sdk::__query_builder::Table<Notice> {
        __sdk::__query_builder::Table::new("valid_notices")
    }
}
