// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct VipMembershipEntitlement {
    pub id: u64,
    pub center_scope: u8,
    pub customer_id: String,
    pub center_user_id: Option<u64>,
    pub out_trade_no: String,
    pub transaction_id: Option<String>,
    pub amount_total: u64,
    pub duration_months: u32,
    pub start_at: __sdk::Timestamp,
    pub end_at: __sdk::Timestamp,
    pub status: String,
    pub refunded_at: Option<__sdk::Timestamp>,
    pub refunded_out_refund_no: Option<String>,
    pub created_at: Option<__sdk::Timestamp>,
    pub updated_at: Option<__sdk::Timestamp>,
}

impl __sdk::InModule for VipMembershipEntitlement {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `VipMembershipEntitlement`.
///
/// Provides typed access to columns for query building.
pub struct VipMembershipEntitlementCols {
    pub id: __sdk::__query_builder::Col<VipMembershipEntitlement, u64>,
    pub center_scope: __sdk::__query_builder::Col<VipMembershipEntitlement, u8>,
    pub customer_id: __sdk::__query_builder::Col<VipMembershipEntitlement, String>,
    pub center_user_id: __sdk::__query_builder::Col<VipMembershipEntitlement, Option<u64>>,
    pub out_trade_no: __sdk::__query_builder::Col<VipMembershipEntitlement, String>,
    pub transaction_id: __sdk::__query_builder::Col<VipMembershipEntitlement, Option<String>>,
    pub amount_total: __sdk::__query_builder::Col<VipMembershipEntitlement, u64>,
    pub duration_months: __sdk::__query_builder::Col<VipMembershipEntitlement, u32>,
    pub start_at: __sdk::__query_builder::Col<VipMembershipEntitlement, __sdk::Timestamp>,
    pub end_at: __sdk::__query_builder::Col<VipMembershipEntitlement, __sdk::Timestamp>,
    pub status: __sdk::__query_builder::Col<VipMembershipEntitlement, String>,
    pub refunded_at:
        __sdk::__query_builder::Col<VipMembershipEntitlement, Option<__sdk::Timestamp>>,
    pub refunded_out_refund_no:
        __sdk::__query_builder::Col<VipMembershipEntitlement, Option<String>>,
    pub created_at: __sdk::__query_builder::Col<VipMembershipEntitlement, Option<__sdk::Timestamp>>,
    pub updated_at: __sdk::__query_builder::Col<VipMembershipEntitlement, Option<__sdk::Timestamp>>,
}

impl __sdk::__query_builder::HasCols for VipMembershipEntitlement {
    type Cols = VipMembershipEntitlementCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        VipMembershipEntitlementCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            center_scope: __sdk::__query_builder::Col::new(table_name, "center_scope"),
            customer_id: __sdk::__query_builder::Col::new(table_name, "customer_id"),
            center_user_id: __sdk::__query_builder::Col::new(table_name, "center_user_id"),
            out_trade_no: __sdk::__query_builder::Col::new(table_name, "out_trade_no"),
            transaction_id: __sdk::__query_builder::Col::new(table_name, "transaction_id"),
            amount_total: __sdk::__query_builder::Col::new(table_name, "amount_total"),
            duration_months: __sdk::__query_builder::Col::new(table_name, "duration_months"),
            start_at: __sdk::__query_builder::Col::new(table_name, "start_at"),
            end_at: __sdk::__query_builder::Col::new(table_name, "end_at"),
            status: __sdk::__query_builder::Col::new(table_name, "status"),
            refunded_at: __sdk::__query_builder::Col::new(table_name, "refunded_at"),
            refunded_out_refund_no: __sdk::__query_builder::Col::new(
                table_name,
                "refunded_out_refund_no",
            ),
            created_at: __sdk::__query_builder::Col::new(table_name, "created_at"),
            updated_at: __sdk::__query_builder::Col::new(table_name, "updated_at"),
        }
    }
}

/// Indexed column accessor struct for the table `VipMembershipEntitlement`.
///
/// Provides typed access to indexed columns for query building.
pub struct VipMembershipEntitlementIxCols {
    pub center_scope: __sdk::__query_builder::IxCol<VipMembershipEntitlement, u8>,
    pub center_user_id: __sdk::__query_builder::IxCol<VipMembershipEntitlement, Option<u64>>,
    pub customer_id: __sdk::__query_builder::IxCol<VipMembershipEntitlement, String>,
    pub id: __sdk::__query_builder::IxCol<VipMembershipEntitlement, u64>,
    pub out_trade_no: __sdk::__query_builder::IxCol<VipMembershipEntitlement, String>,
    pub status: __sdk::__query_builder::IxCol<VipMembershipEntitlement, String>,
}

impl __sdk::__query_builder::HasIxCols for VipMembershipEntitlement {
    type IxCols = VipMembershipEntitlementIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        VipMembershipEntitlementIxCols {
            center_scope: __sdk::__query_builder::IxCol::new(table_name, "center_scope"),
            center_user_id: __sdk::__query_builder::IxCol::new(table_name, "center_user_id"),
            customer_id: __sdk::__query_builder::IxCol::new(table_name, "customer_id"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            out_trade_no: __sdk::__query_builder::IxCol::new(table_name, "out_trade_no"),
            status: __sdk::__query_builder::IxCol::new(table_name, "status"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for VipMembershipEntitlement {}
